### ISSUE TITLE
Not showing on lock screen

### ISSUE THREAD

**Issue by z4c99** [himynameisubik/Kalm-support#1]
![E78BC0E9-C427-4FA0-826D-6607B4420A17](https://user-images.githubusercontent.com/60616228/73667809-d0071d80-46df-11ea-90f6-3529cfcc3e76.png)
![C32A8876-3421-413F-8EA2-851019C27B6B](https://user-images.githubusercontent.com/60616228/73667810-d09fb400-46df-11ea-9e2f-3554a50a8379.png)
![A10E399F-7A69-4EEF-B1FB-6743ECFD7C99](https://user-images.githubusercontent.com/60616228/73667811-d09fb400-46df-11ea-8edd-3af6cb1180eb.png)
![6CD4BD42-760A-4721-ABEF-34A421398B0A](https://user-images.githubusercontent.com/60616228/73667813-d09fb400-46df-11ea-8f11-ad005acca6e6.png)
![6B37EF32-2422-4BC5-9122-DE505CEE56F7](https://user-images.githubusercontent.com/60616228/73667814-d1384a80-46df-11ea-8516-6ea6de89dfcb.png)

**Describe the bug**
Kalm doesn't show on lockscreen

**How to reproduce**

**Expected behavior**
I expected kalm to show on my lock screen but..:

**Screenshots**

iPhone X, iOS 12.4

**Tweak list:**
Either attach it as a text file or put it on e.g. pastebin.com

**Crashlog:**
Either attach it as a text file or put it on e.g. pastebin.com

**Additional context**
Previously had XenHTML and A-Font and Grupi on my lock screen to replace the stock clock and notifications. Kalm doesn't work despite disabling them tweaks.

**Comment by himynameisubik** [comment]
Sorry for the inconvenience. Looks like a conflicting tweak, did you try disabling **all** other tweaks except Kalm?

**Comment by z4c99** [comment]
> Sorry for the inconvenience. Looks like a conflicting tweak, did you try disabling **all** other tweaks except Kalm?

I'll give it a go and then update you

**Comment by z4c99** [comment]
> > Sorry for the inconvenience. Looks like a conflicting tweak, did you try disabling **all** other tweaks except Kalm?
> 
> I'll give it a go and then update you

Update: disabling all tweaks makes it work. I'll try to find out which tweak it is when I'm not busy

**Comment by himynameisubik** [comment]
Thanks for the testing. Strangely I use Choicy myself so I think it might be a setting - not Choicy itself. What are your Choicy settings?

**Comment by himynameisubik** [comment]
No worries, enjoy!
