### ISSUE TITLE
Alignement not working on iPad

### ISSUE THREAD

**Issue by diamkil** [himynameisubik/Kalm-support#10]
**Describe the bug**
When using the alignment setting on iPad it simply does nothing

**How to reproduce**
1. Go to 'Kalm Settings'
2. Click on 'Appearance'
3. Change alignement setting
4. Respring
5. Watch as the setting does nothin

**Expected behavior**
The time should align to what is set in settings (left/right)

**Screenshots**
Can’t upload since I’m on iPad

**iOS Version:**
13.2.3
**Device:**
iPad 6
**Tweak list:**
https://pastebin.com/2gK2nNmE

**Crashlog:**
N/A

**Additional context**

**Comment by himynameisubik** [comment]
Did you try disabling all other Tweaks in iCleaner except Kalm?

**Comment by diamkil** [comment]
I tried and it does the same

**Comment by himynameisubik** [comment]
Will try to look into it, I don't have an iPad at hand but I'll cross test it with a friend. Sorry for the inconvenience.

**Comment by himynameisubik** [comment]
Does this happen in landscape and portrait mode?

**Comment by diamkil** [comment]
It doesn’t work in landscape but didn’t test in portrait yet, will test tonight

**Comment by himynameisubik** [comment]
Closing this issue as no more information was provided.

**Comment by diamkil** [comment]
> Closing this issue as no more information was provided.

Sorry I had forgot, works in Portrait but not in landscape, weirdly if device is oppened in portrait then switched to landscape, it works

**Comment by himynameisubik** [comment]
Okay thanks for the update. Will check if I can find something. Sorry for the inconvenience.

**Comment by himynameisubik** [comment]
Fixed in 1.2.2

**Comment by diamkil** [comment]
Thank you
