### ISSUE TITLE
Feature request: Custom gap between events in Up Next view

### ISSUE THREAD

**Issue by blankster** [himynameisubik/Kalm-support#101]
First of all: Thanks for the latest version and the privacy mode!

I don't know if I overlook something, but is there a setting, for the gap between each appointment? (the space between the location of one entry and the title of the next one)

At least in my installation, this gap is bigger than the default-gap before "up next".

In general, changing the gap values by hand feels like impossible as it's reacting far too much for movement. It would help if it would be less sensitive or an option available to enter a value.

Next to this: It looks like Kalm has a problem with Harbor 3, as I can't click the button after respring to go to settings (the dock is blocking it after unlock) and if I swipe it away it re-appears after every respring now. _I can fill a separate bug-report if you consider this as helpful and if it isn't clear what happens!_

**Comment by himynameisubik** [comment]
Cheers!

Please update to 1.4.1 to fix the bug with Harbor. If you just swipe it down, it will not show again. Or you can just disable Harbor and click it like that. It's an issue coming from Harbor.

Yes the gap is different than in the older version.

Install "Shuffle" Tweak it lets you click on the slider and you can then set a value yourself.

**Comment by blankster** [comment]
@himynameisubik wow that was fast :)

**Changelog Bug:** ✔️ fixed - thanks a lot!

**Preferences Tweak:** I've replaced other preferences tweak with the (better) "Shuffle" (for others don't confuse with the random wallpaper tweak with the same name). That works exactly as you say! ✔️ 

**Appointment Gap:** Is there also a solution for this? I prefer the detailed view as I need to see the location of the appointments and always use 5 appointments to have a feeling what appointments are in near-term important, but that gap consumes far too much space. _Personaly_ I would like to have no gap (=> next line) as the bullet points themselves separate the appointments and space on lock screen - especially for notifications - is valuable.

**Comment by himynameisubik** [comment]
You could use the "Compact mode" for that?

**Comment by blankster** [comment]
No, as it doesn't display then the locations. But the spacing of it between the appointment would be perfect :)

**Comment by himynameisubik** [comment]
I'll see if I can add an option for that.

**Comment by blankster** [comment]
That would be perfect and highly appreciated :)

**Comment by blankster** [comment]
Sorry, my bad, didn't want to close it.
