### ISSUE TITLE
Battery % showing 0 when charging

### ISSUE THREAD

**Issue by gkeep** [himynameisubik/Kalm-support#102]
General information:
===

**Kalm version:**
1.4.1

**Kalm preferences file:**
https://pastebin.com/tyrMJM5j

Device information:
===

**iOS version and language:** 12.4.7

**Device:** iPhone 5s

**Jailbreak:** checkra1n

Bug description:
===

**Describe the bug:**
Kalm displays 0% instead of current percentage when device is charging.

**Expected behavior:**
Kalm should display current percentage.

**Screenshots:**
https://i.imgur.com/xKcqyAP.jpg

**Comment by himynameisubik** [comment]
That's odd. Does it happen on 1.3.4?

**Comment by gkeep** [comment]
Nope. Works fine on 1.3.4.

**Comment by himynameisubik** [comment]
Will look into it. Thanks for the report.

**Comment by RedenticDev** [comment]
Same problem here, iPhone X🅂 13.5, Kalm 1.4.1, worked before 1.4.0, prefs: https://pastebin.com/0LRbDR2X

**Comment by himynameisubik** [comment]
Should be fixed with the next version.

**Comment by CySxL** [comment]
same. iPhoneX, iOS13.3, Kalm 1.4.1

**Comment by gkeep** [comment]
Fixed in 1.4.2. 👍

**Comment by himynameisubik** [comment]
Thanks!
