### ISSUE TITLE
Respring loop with unknown tweak conflict (Activator?)

### ISSUE THREAD

**Issue by nullslwx** [himynameisubik/Kalm-support#103]
General information:
===

**Kalm version:**
1.4.0

**Kalm preferences file:**
Fresh install

Device information:
===

**iOS version and language:**
13.5 English

**Device:**
iPhone XS Max

**Jailbreak:**
uncover 5.0.1

Bug description:
===

**Describe the bug:**
Fresh install of Kalm. Stuck in respring loop

**How to reproduce:**
Install and enable both Kalm - 1.4.0 , Activator - 1.9.13~beta11

I'm assuming this is something the Developer of Activator will have to fix.

**Comment by himynameisubik** [comment]
First of all, sorry for the inconvenience, but don't worry. 

What you need to do is the following:
- Go into unc0ver Settings and turn off "Load tweaks"
- Rejailbreak
- Uninstall Kalm
- Reboot and rejailbreak with the "Load tweaks" on and you're back.

Now for fixing this issue with Kalm, have you tried these steps?
https://github.com/himynameisubik/Kalm-support#general-steps-to-try-before-creating-an-issue

Also what Tweaks have you got installed?

**Comment by nullslwx** [comment]
Hey, I didn't know uncover had that option. Will try that in a sec, thanks!

I'll try those things listed as I couldn't do them before. I'll make another reply with all my tweaks listed.

Again, thanks!

**Comment by himynameisubik** [comment]
Good luck :) And let me know!

**Comment by nullslwx** [comment]
Hello again

Tried the steps in the initial troubleshoot page. Kalm works with everything disabled. I can go one by one to see which app is causing the error unless you can see something in this list that would cause compatibility issues.

https://pastebin.com/N7U3jZDH

**Comment by himynameisubik** [comment]
Okay, great news firstly.

Hmm unfortunately I can't see anything specific. At the moment there are two tweaks that might cause an issue and they are LockPlus Pro and OneNotify.

**Comment by nullslwx** [comment]
That was a lot faster than I thought..., Dayn seems to cause the problem I was having earlier. It's a notification banner tweak so I'm not exactly sure what could be conflicting with a Lock Screen tweak. I'll continue to check the rest one-by-one to see if there's any others.

**Comment by himynameisubik** [comment]
That's weird yeah. I'll try to get in contact with the dev of it to see if we can find something.

**Comment by himynameisubik** [comment]
I just tested it with Dayn and have no issue with it.

**Comment by nullslwx** [comment]
My mistake. I'd left Activator enabled along with Dayn; Dayn and Kalm do work together.

my best guess is this: I had an activator function that turned on the flashlight by volup and voldown being pressed. I'm assuming since the flashlight button is on the LS it had something to do with it? I'll disable Kalm and delete that function and see if that resolves the issue.

**Comment by himynameisubik** [comment]
All right, I'll look into that. Thanks for the follow up!

**Comment by nullslwx** [comment]
Interesting. Even after resetting all values inside of Activator I still have the same issue. I can't think of anything else.

**Comment by himynameisubik** [comment]
Which version of Activator do you have? And have you updated it to the latest?

**Comment by nullslwx** [comment]
I was using the latest beta build 1.9.13~beta11. I was thinking it might be another tweak dependent on preference loader. I had a few, Dayn included. All of those remain active and working along with Kalm but I cannot enable the beta version of Activator. I'll downgrade and use the stable build.

**Comment by nullslwx** [comment]
Updated my initial post to better reflect the issue I was having.

**Comment by himynameisubik** [comment]
Does the stable version of Activator work?

**Comment by himynameisubik** [comment]
Just tested. Activator 1.9.13~beta12 works fine with Kalm installed.

**Comment by nullslwx** [comment]
Stable works. Updated to beta12. And am still having the issue.

**Comment by himynameisubik** [comment]
That's really weird. I think there is another Tweak playing a part in this.

**Comment by himynameisubik** [comment]
LockPlus Pro & OneNotify are the conflicting tweaks. Version 1.4.2 coming soon which fixes that issue. Sorry for the inconvenience.

**Comment by nullslwx** [comment]
I don't have either of those :( but thank you for looking into this for me!

I've tried to reinstall both Kalm and Activator but haven't had any luck with getting them to work with each other for some reason.

**Comment by himynameisubik** [comment]
Oh sorry, could you provide me with your Tweaklist?

**Comment by nullslwx** [comment]
Absolutely! I haven't added any tweaks since I opened this thread
https://pastebin.com/N7U3jZDH

Only thing that has changed is Activator has been uninstalled and that has fixed my issue. Stable version of activator still works. beta11 and beta12 still give me issues. Not a huge issue, especially if I'm the only one having this problem. I'd much rather have Kalm than activator as I only used it for a flashlight shortcut and respring shortcut. lol

**Comment by himynameisubik** [comment]
All right, thanks! Hmm, I can't see anything particular that I would suggest disabling. But just for the test, could you disable all other tweaks in iCleaner and only enable Kalm and Activator? Only tweaks, not Substrate Safemode or something like that.

Also make sure to update to 1.4.2 as this might already fixes the issue.

**Comment by himynameisubik** [comment]
Thanks for the time your spending trying to find the culprit, much appreciated!

**Comment by JasonXGaming** [comment]
Also having the respring/reboot loop. After that i had to disable the tweaks and re-jailbreak. De-install Kalm and the phone works normally. Also in Filza I removed all old folders wich associate with Kalm. 

The problem started with tweaking Kalm in the settings. I wanna to use Kalm, so I re-installed it. But problem keeps popping up. 

Reading above, i will try to delete activator and see what happens! 

Keep you posted.

Greets Jason

**Comment by himynameisubik** [comment]
Closing this for now. Feel free to reopen if you have an issue.
