### ISSUE TITLE
Font weight of date doesn't change with Photon installed

### ISSUE THREAD

**Issue by PuniTsubakiHime** [himynameisubik/Kalm-support#104]
[General](url
![IMG_0088](https://user-images.githubusercontent.com/64231337/83436697-e09e8900-a470-11ea-88df-46058542abed.jpeg) This is 1.3.4

![IMG_0089](https://user-images.githubusercontent.com/64231337/83436760-04fa6580-a471-11ea-9732-13cacd4e6c0c.jpeg)
This is 1.4.1

information:
The font weight of my date doesn't change at either side of the slider (thick or thin). My phone is currently in Japanese.
===

**Kalm version:**
1.4.0 and 1.4.1

**Kalm preferences file:**
https://pastebin.com/F1K02Ddd

Device information:
===

iOS version and language: 13.5, Japanese

Device: iPhone 8 plus

Jailbreak: Checkra1n 0.10.2

Bug description:
===

**Describe the bug:**
Font weight of my date is not changing. It stays the same regardless of the slider position.

**How to reproduce:**

Change to japanese language
change the date font weight.

**Expected behavior:**

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Can you try respringing?

**Comment by himynameisubik** [comment]
Only work with a respring. Will be fixed with the next version without respring.

**Comment by PuniTsubakiHime** [comment]
Yup i resprang a few times, but the font weight doesn't change on either side for japanese. I feel the difference between the ends of english is quite subtle.

**Comment by PuniTsubakiHime** [comment]
The lowest setting for font weight for english is thicker than that of 1.3.4. Is there a way to reproduce the 1.3.4 look?

**Comment by himynameisubik** [comment]
Works fine for me when switching to Japanese and respringing after changing the font weight.

**Comment by himynameisubik** [comment]
Nothing has changed for the lowest and highest settings. Might be something interfering with Kalm?

**Comment by PuniTsubakiHime** [comment]
Ok, ill to try find anything that could've cause the conflict.

**Comment by PuniTsubakiHime** [comment]
Yah the font weight for date doesnt change at all

**Comment by himynameisubik** [comment]
If you go into Kalm Settings, change the font weight of Date to the lowest and respring it should work. It works on my phone perfectly – with a respring.

**Comment by PuniTsubakiHime** [comment]
I found the issue. Its the apple watch font setting under adjust modular style in photon. After disabling it, i can change the size of the date font weight. It changes for me without a respring though.

**Comment by PuniTsubakiHime** [comment]
The setting keeps date font weight at the max setting and wont be able to change for japanese. For english, the change is quite subtle, more of size change and not the font weight.

**Comment by himynameisubik** [comment]
Did you enable Kalm mode in Photon?

**Comment by PuniTsubakiHime** [comment]
Yes it’s on it’s the Apple Watch font causing the conflict.

**Comment by himynameisubik** [comment]
Just confirmed. With Photon it does not update correctly. Will do a workaround. Will be fixed in the next version.

**Comment by PuniTsubakiHime** [comment]
Thank you for your time!

**Comment by himynameisubik** [comment]
Fixed as of 1.4.2.
