### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by kandoory** [himynameisubik/Kalm-support#106]
**Request:**
#72 `colors issue`
I would prefer the ability to save the accent color I choose when I switch back and forth between dark and light mode. It chooses a new default accent color, not the one I set.

**Comment by himynameisubik** [comment]
This happens because the wallpaper changes and the colors need to be recalculated. If you want a fixed color use the "Custom color" toggle.

**Comment by kandoory** [comment]
I tried that, but I can only set one custom color. Can we get an option to set two? One for dark mode and one light mode.
That would be awesome! Much appreciated and thank you for such an amazing tweak

**Comment by himynameisubik** [comment]
I'm looking into a good way to implement this for a user
