### ISSUE TITLE
Feature request: Reset button

### ISSUE THREAD

**Issue by Mindstorm95** [himynameisubik/Kalm-support#108]
**Request:**
A reset button to reset the settings of the app. Perhas 2 different, one for font and one for color on each of their page and a master reset to reset the whole tweak

Thanks!

**Comment by himynameisubik** [comment]
Will look into it, no ETA.

**Comment by himynameisubik** [comment]
This was more or less implemented with the new appearances which reset Kalm partially. A full reset is not planned.
