### ISSUE TITLE
Feature request: Set separate color for light and dark mode

### ISSUE THREAD

**Issue by CySxL** [himynameisubik/Kalm-support#109]
**Request:**
Ability to set independent separately color for light and dark mode wallpaper.

(because I'm using Wallpaperloader from Skitty, the dark mode wallpaper is different from light mode wallpaper which makes the color of Kalm weird 😂)

**Comment by himynameisubik** [comment]
Looking into that. What you can do is adjust the brigthness and saturation in Colors. Kalm will automatically recalculate the colors if the wallpaper changes, so that's why this happens.

**Comment by CySxL** [comment]
Yeah I've tried to set different colors between light and dark mode LS wallpaper but whenever I enabled the dark mode toggle everything will stay the same as before.

**Comment by himynameisubik** [comment]
Yes. That's what I am saying.
