### ISSUE TITLE
Feature request: DND icon

### ISSUE THREAD

**Issue by lucio97** [himynameisubik/Kalm-support#11]
Hi man, 
can you add a dnd little icon to Kalm? It would work very good with NoDNDBanner to know when dnd is on.
Thanks

**Comment by himynameisubik** [comment]
Good idea, will look into it. No ETA yet.

**Comment by himynameisubik** [comment]
Hey there! I suggest using Lune by Litten it suits really well!

https://reddit.com/r/jailbreak/comments/f3ymrq/release_lune_show_a_little_moon_icon_on_your/

Does that work for you? If so, feel free to close this enhancement :)

**Comment by lucio97** [comment]
![7EB388E7-D161-478D-A6F6-6833CD8B5AD8](https://user-images.githubusercontent.com/9356159/74587088-92af6380-4fee-11ea-9624-b1df48e7b8b7.png)
Yayyy 🥳🥳
Thank you so much, i think I found also a neat spot ahah

**Comment by himynameisubik** [comment]
Sweet! Glad it works out for you and thanks for using Kalm! 😊
