### ISSUE TITLE
Conflict with Latchkey

### ISSUE THREAD

**Issue by FakeRayBanz** [himynameisubik/Kalm-support#110]
General information:
===

**Kalm version:**
1.4.1
**Kalm preferences file:**
https://pastebin.com/BEDBVycC

Device information:
===

**iOS version and language:**
iOS 13.3, English
**Device:**
iPhone XS
**Jailbreak:**
Unc0ver 5.0.1

Bug description:
===

**Describe the bug:**
When using the tweak Latchkey (https://repo.daus.ch) with Kalm, Kalm conflicts and sets the location of the FaceID lock, disallowing Latchkey from working properly.

I have disabled Kalm via iCleaner and the issue is no longer present.

Kalm appears to control the location of the FaceID Lock which Latchkey attempts to override which causes a visual bug of the FaceID lock jumping across the screen when the animation changes. Steps to reproduce provides more detail.

**How to reproduce:**

1. Install Kalm
2. Install Latchkey via the repo https://repo.daus.ch
3. Enable Kalm
4. Enable Latchkey and set Position to Status Bar, or any position other than default. (Although default still exhibits the bug it is far less noticeable. Respring to apply.
5. Lock the screen. 
6. Unlock the screen without your face in view - the FaceID Lock is in the correct position as set by Latchkey, mine being the Statusbar.
7. Notice that as you bring your face into view and your phone unlocks, the FaceID Lock disappears momentarily from the Statusbar, appears at the default stock position, then slides back to the Latchkey position.   

**Expected behavior:**
The FaceID Lock icon should remain in the location set in the Latchkey preferences at all times.

**Screenshots:**
https://imgur.com/a/SS8tefK
It is a bit difficult to see due to the Screen Recording icon that is present in the Statusbar, however this video shows the issue.

**Comment by himynameisubik** [comment]
Will be fixed in the next update. Sorry for the inconvenience was introduced with the latest fix for Quart. My bad.

**Comment by FakeRayBanz** [comment]
No worries, thank you!

**Comment by himynameisubik** [comment]
Fixed as of 1.4.2.

**Comment by FakeRayBanz** [comment]
This bug has been reintroduced in the latest version of Kalm

**Comment by himynameisubik** [comment]
Seems to be working on my end and nothing was changed on the LatchKey fix. 

If LatchKey is installed, enabled, and the position is not default, Kalm does nothing to the lock icon.
Can you try disabling & enabling LatchKey?
And can you attach your LatchKey prefs file (/var/mobile/Library/Preferences/ch.mdaus.latchkey.plist)?

**Comment by FakeRayBanz** [comment]
Disabling and reenabling latchkey worked, thank you
