### ISSUE TITLE
Conflicts with Saw

### ISSUE THREAD

**Issue by CySxL** [himynameisubik/Kalm-support#112]
General information:
===

**Kalm version:**
1.4.1
**Kalm preferences file:**
Put it on www.pastebin.com.

https://pastebin.com/84NeFmLR

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
iOS13.3. Chinese(Traditional)
**Device:**
iPhoneX
**Jailbreak:**
CheckRa1n 0.10.1

Bug description:
===

**Describe the bug:**
Notifications are not at the right place.
**How to reproduce:**
Enable Saw.
Respring once, don't open NC. Launch an app with landscape mode support, turn to landscape mode, drag down NC.

**Expected behavior:**
Notifications should be at the right place.
**Screenshots:**
![92560354-5E35-4255-833E-62F4FB15C20E](https://user-images.githubusercontent.com/15531137/83501879-5fd4a100-a4f3-11ea-87e4-ad37f761344f.png)

Additional information:
===

've already debugged with iCleaner Pro among my almost 200 tweaks and found that only Saw did this, which never appeared with the previous version of Kalm(before 1.4.0).

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by CySxL** [comment]
First time u drag down NC the notifications would be at wrong place, and the second time it would repair itself tho.

**Comment by himynameisubik** [comment]
Hmm, could you try enabling Up Next?

**Comment by CySxL** [comment]
Oh! Wow! Enabled Up Next and it really solve that 🤔🤔 so weird.    If disable Up Next, only disable Saw in iCleanerPro would fix this.

**Comment by CySxL** [comment]
Is this problem gonna be fixed?

**Comment by CySxL** [comment]
appreciate a lot!

**Comment by himynameisubik** [comment]
This should be fixed as of 2.0.0. Could you confirm?

**Comment by CySxL** [comment]
I can't confirm it because I'm still using 1.4.3.

2.0.0 and up cause various issues for me and I'm tired to point them out.(gap misleading, Grupi fades out, etc..)

Sorry. Maybe next tIme.

**Comment by himynameisubik** [comment]
Closing this then since it's fixed.
