### ISSUE TITLE
Scrolling glitch

### ISSUE THREAD

**Issue by libertig** [himynameisubik/Kalm-support#113]
General information:
===

Kalm version: 1.4.1

Kalm preferences file: https://pastebin.com/ba5xBEkZ

Device information:
===

iOS version and language: 13.4.1, English

Device: iPhone 7

Jailbreak: Checkra1n

Bug description:
===

When you have a few notifications and try to scroll through them, the animation does like a bounce up.

How to reproduce: I think it depends on the numbers of notifications you have, and just scroll down.

Preview of bug: https://drive.google.com/file/d/1rMAUz7_ukCc8i828PSF7LaBZmv_mcZdJ

**Comment by himynameisubik** [comment]
Hmm, does this happen if only Kalm is installed? I can't seem to reproduce this behavior. And does it happen with 1.3.4 as well?

**Comment by libertig** [comment]
I don’t remember this issue happening on that version. What I noticed too is that when I have a notification that doesn’t cover the screen the scroll seems to be limited, but if I get more that covers the screen the scrolling is enabled (maybe a resolution limit?).

Stock iOS doesn’t do this either. I have a tweak to disable the notification header "KeepItSimple", but I was using it with the previous versions so I don’t think that is an issue 🤔

**Comment by himynameisubik** [comment]
So this didn't happen with which version?

**Comment by libertig** [comment]
1.3.4 But it seems that on 1.4.2 you fixed it now. Maybe it was a conflict with the tweak OneNotify, the KeepItSimple tweak I’m using is based on that code.

Another thing I would like to report, I already sent you as a "Feature" before, but I noticed that when you enable "Up Next" option, the notifications received when they move down to display correctly the animation doesn’t look natural, is it possible that you directly disable the animation when pulling down the Notification Center? Sometimes it does this animation, and sometimes it doesn’t. Just happens with Up Next enabled, it’s like it exceeds the limit of stock iOS padding and forces the notifications to accommodate.

**Comment by himynameisubik** [comment]
I know what you mean, but I wasn't able to "remove" this yet. Something I have on my "Try to do" list.

**Comment by himynameisubik** [comment]
Ah, thanks, good to know.
