### ISSUE TITLE
Feature Request: Kalm for Homescreen

### ISSUE THREAD

**Issue by theprestigext** [himynameisubik/Kalm-support#114]
Hi, thank you for making Kalm! I’d love it if you could somehow implement Kalm to be used on the home screen. A tweak called HomeTime already puts the lockscreen clock on the home screen but it is very buggy with Kalm. I’m a designer myself and I just created a little concept of how it could look like on the home screen. See image below. 

Thank you for all your hard work! Appreciate it :)

![275A4057-65F9-48B1-A625-8D366421A46E](https://user-images.githubusercontent.com/66316651/83528012-7de4d600-a4e0-11ea-9942-9fc3c198cf7b.png)

**Comment by himynameisubik** [comment]
Thanks for the request, however this is not planned at the moment.

**Comment by theprestigext** [comment]
> Thanks for the request, however this is not planned at the moment.

Ok, no problem. If it wouldn’t be too much trouble could you make it compatible with HomeTime? I get this issue of Kalm reloading when going into the notification centre. iOS 13.5, iPhone X [https://twitter.com/theprestigext/status/1267268741953458178?s=21]()

**Comment by himynameisubik** [comment]
This is the normal behavior of HomeTime since it takes the original view of the lockscreen date view and puts it on the home screen.
