### ISSUE TITLE
No longer works with Counted tweak

### ISSUE THREAD

**Issue by ItsADZZOOO** [himynameisubik/Kalm-support#115]
**General information:**
Tweak no longer works with the Counted tweak to have countdown on lock screen, worked fine before the recent update. 

**Kalm version:** 1.4.1

**Device information:**

iOS version and language:13.5 English

Device:iPhone XS

Jailbreak:Unc0ver

**Bug description:**
Counted simply doesn’t work anymore with the new Kalon update, it doesn’t show anywhere on the lock screen. 

**How to reproduce:** Install Kalm and Counted.

**Comment by himynameisubik** [comment]
Works fine for me. Just click the time.

**Comment by ItsADZZOOO** [comment]
Can’t seem to get it working. Will just have to use a downgraded version, thanks anyway.
