### ISSUE TITLE
Feature request: Batter Indicator

### ISSUE THREAD

**Issue by Kohmei358** [himynameisubik/Kalm-support#116]
**Request:**
![image](https://user-images.githubusercontent.com/19924289/83539758-6df5e200-a532-11ea-86ec-cf2323eee3f3.png)
Something like this but more polished design.
It’s helpful when you want the kalm interface to be your always on display. Right now, I have to get a separate tweak and position it just right get time, date, and battery.

**Comment by himynameisubik** [comment]
Not planned. Might want to ask your favorite always on display tweak dev to add a toggle to replace the date view with the battery percantage.
