### ISSUE TITLE
Conflict with OneNotify - Respring loop

### ISSUE THREAD

**Issue by sippinjuice247** [himynameisubik/Kalm-support#117]
General information:
I was on a previous version of Kalm which I believe to be the one just before 1.4. I had not updated to version 1.4

**Kalm version:**
1.4.1

**Kalm preferences file:**
Just deleted preferences file from Filza

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
13.5 English

**Device:**
iPhone X

**Jailbreak:**
Checkra1n

Bug description:
===

**Describe the bug:**
I had an available update for Kalm. This was the 1.4.1 update. I've had to go into iCleaner to manually disable the tweak as it results in an infinite respring, ultimately resulting in a reboot.

**How to reproduce:**

**Expected behavior:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by sippinjuice247** [comment]
Narrowing down the problem, I believe it may be the tweak "OneNotify" or "PreferenceOrganizer 2."

**Comment by himynameisubik** [comment]
It's OneNotify, should be fixed soon.

**Comment by sippinjuice247** [comment]
Awesome thank you for the quick response man. Great work as always!

**Comment by himynameisubik** [comment]
Fixed as of 1.4.2.
