### ISSUE TITLE
I have a problem in landscape 

### ISSUE THREAD

**Issue by skapein** [himynameisubik/Kalm-support#120]
Kalm 1.4.1
![978059F4-E4CA-416C-B38F-8BDB7CB808BE](https://user-images.githubusercontent.com/44177473/83771706-2e211e80-a648-11ea-8f26-95840050cadd.png)

Kalm 1.3.4
![D958C8EF-F6DB-4B73-8129-F092378E7A8E](https://user-images.githubusercontent.com/44177473/83771932-6cb6d900-a648-11ea-9653-4dd391ceeacc.png)

Iphone 7, 12.4 Unc0ver

**Comment by himynameisubik** [comment]
Please report the issue with the required info.
