### ISSUE TITLE
Kalm shows up while playing media

### ISSUE THREAD

**Issue by samwllson9478** [himynameisubik/Kalm-support#121]
Hey I have been using kalm for months and i seem to be having a problem hiding the location and weather behind the album art, is there anyway you could add a switch to hide it when media is playing? 
I linked a photo to show you what i’m talking about. Thanks love the update 
![4AFDF23C-0476-41A2-B8CE-9FEE33538E6A](https://user-images.githubusercontent.com/62081609/83800383-5d01b980-a675-11ea-8ee2-7be2631b54cc.png)

**Comment by himynameisubik** [comment]
What tweak are you using for that?

**Comment by samwllson9478** [comment]
ColorFlow5 for lockscreen

**Comment by himynameisubik** [comment]
What settings?

**Comment by CySxL** [comment]
u need to turn on the "show date view" of ColorFlow 5, and it will be like this:
![7C138DE7-246F-418C-9D8F-7F077CBBC905](https://user-images.githubusercontent.com/15531137/84029959-d2e38900-a9c5-11ea-90c4-d987b8c10709.png)

**Comment by samwllson9478** [comment]
I don’t want it to show any of it and it was showing the date, what phone do you have because that nicebar x setup is clean

**Comment by himynameisubik** [comment]
Can you disable other tweaks except colorflow, because this does not happen to me.

**Comment by CySxL** [comment]
> I don’t want it to show any of it and it was showing the date, what phone do you have because that nicebar x setup is clean
> […](#)

I'm using iPhoneX.
Thanks! Designed by me (?

**Comment by himynameisubik** [comment]
Closing as of no more information was provided.
