### ISSUE TITLE
Quart with disabled Widget breaks Padlock alignment

### ISSUE THREAD

**Issue by Bradley0419** [himynameisubik/Kalm-support#122]
General information:
===
The Face ID padlock no longer aligns after the newest update. A quick downgrade fixed for the moment.
**Kalm version:**
Newest Version 

**iOS version and language:**
13.3 
**Device:**
iPhone X 
**Jailbreak:**
Checkra1n

**Comment by himynameisubik** [comment]
Please provide a tweak list

**Comment by ljuul646** [comment]
I’m having the same issue. Here is my tweak list. Tried disabling all tweaks dealing with LS

AppList (applist) v1.5.16 by Ryan Petrich  via Local Repository
APT (apt) v1.8.2-3 by Unknown via Local Repository
APT (apt-key) (apt-key) v1.8.2-1 by Unknown via Local Repository
APT 1.4 Transitional (apt1.4) v1:0 by Unknown via Local Repository
Base Structure (base) v1-5 by Unknown via Local Repository
Bourne-Again SHell (bash) v5.0.3-2 by Unknown via Local Repository
Berkeley DB (berkeleydb) v6.2.32-1 by Unknown via Local Repository
bzip2 (bzip2) v1.0.6-1 by Unknown via Local Repository
CA Certs (ca-certificates) v0.0.2 by Unknown via Local Repository
ShortLook (co.dynastic.ios.tweak.shortlook) v1.0.17 by Dynastic via Local Repository
Notchification (com.c1d3r.notchification) v2.0.2-3 by c1d3r  via Local Repository
libnotifications (com.cokepokes.libnotifications) v0.3 by CokePokes  via Local Repository
libCSPreferences (com.creaturecoding.libcspreferences) v1.4.5 by CreatureSurvive  via Local Repository
shuffle (com.creaturecoding.shuffle) v1.2.8 by CreatureSurvive  via Local Repository
libCSColorPicker (com.creaturesurvive.libcscolorpicker) v1.0.3 by CreatureSurvive  via Local Repository
QuickLS (com.daveapps.quickls) v2.5.2 by Dave Van Wijk  via Local Repository
Substitute (com.ex.substitute) v0.1.13 by comex  via Local Repository
noNotch (com.jakeashacks.nonotch) v1.1.2 by Jake James  via Local Repository
PrefixUI (com.laughingquoll.prefixui) v1.2.6 by LaughingQuoll via Local Repository
Quart (com.laughingquoll.quart) v1.1.2 by LaughingQuoll via Local Repository
ReProvision (com.matchstic.reprovision) v0.5.2~EOL by Matt Clarke  via Local Repository
Cr4shed (com.muirey03.cr4shed) v4.1.3 by Muirey03 via Local Repository
libMRYIPC (com.muirey03.libmryipc) v1.0 by Muirey03 via Local Repository
RocketBootstrap (com.rpetrich.rocketbootstrap) v1.0.9 by Ryan Petrich  via Local Repository
Notifica (BawAppie) (com.rpgfarm.notifica) v0.4.1 by Nepeta & BawAppie  via Local Repository
Substrate Safe Mode (com.saurik.substrate.safemode) v0.9.6003 by Jay Freeman (saurik)  via Local Repository
libSparkAppList (com.spark.libsparkapplist) v1.0.9 by Spark via Local Repository
libsparkcolourpicker (com.spark.libsparkcolourpicker) v1.0.0 by Spark via Local Repository
SnowBoard (com.spark.snowboard) v1.2.94~Beta2 by Spark & Dennis D. Bednarz via Local Repository
Docktyle (com.thatmarcel.tweaks.docktyle) v1.0.2 by Marcel Braun via Local Repository
Bohemic (com.thetimeloop.bohemic) v1.1.4 by Timeloop via Local Repository
Lynx (com.twickd.mtac.lynx) v1.4-3 by MTAC  via Local Repository
BetterWidgets (com.twickd.shadowdev.betterwidgets) v1.3 by ShadowDev  via Local Repository
Core Utilities (coreutils) v8.31-1 by Unknown via Local Repository
Core Utilities (/bin) (coreutils-bin) v8.31-1 by Unknown via Local Repository
Cydia Installer (cydia) v1.1.33 by Jay Freeman (saurik)  via Local Repository
Cydia Translations (cydia-lproj) v1.1.32~b1 by Jay Freeman (saurik)  via Local Repository
Darwin Tools (darwintools) v1.1-1 by Unknown via Local Repository
Debian Utilities (debianutils) v4.8.6-1 by Unknown via Local Repository
Diff Utilities (diffutils) v3.6-1 by Unknown via Local Repository
diskdev-cmds (diskdev-cmds) v593.221.1-1 by Unknown via Local Repository
Debian Packager (dpkg) v1.19.7-1 by Unknown via Local Repository
Essential (essential) v0-2 by Unknown via Local Repository
file (file) v5.35-2 by Unknown via Local Repository
Find Utilities (findutils) v4.6.0-2 by Unknown via Local Repository
iPhone Firmware (/sbin) (firmware-sbin) v0-1 by Unknown via Local Repository
GNU Cryptography (gcrypt) v1.8.3-1 by Unknown via Local Repository
gettext (gettext) v0.19.8-1 by Unknown via Local Repository
GnuPG (gnupg) v2.2.11-2 by Unknown via Local Repository
GnuTLS (gnutls) v3.5.19-1 by Unknown via Local Repository
grep (grep) v3.1-1 by Unknown via Local Repository
gzip (gzip) v1.9-1 by Unknown via Local Repository
Kalm (hi.my.name.is.ubik.kalm) v1.4.2 by ubik  via Local Repository
Launch Daemon Controller (launchctl) v23-1 by Unknown via Local Repository
Link Identity Editor (ldid) v2:2.1.2+g5420cb5-1 by Jay Freeman (saurik)  via Local Repository
APT Strict (lib) (libapt) v1.8.2-1 by Unknown via Local Repository
APT (libapt-pkg) (libapt-pkg5.0) v1.8.2-1 by Unknown via Local Repository
Assuan (libassuan) v2.5.1-1 by Unknown via Local Repository
GNU Multiple Precision Arithmetic Library (libgmp10) v6.1.2-1 by Unknown via Local Repository
GnuPG Errors (libgpg-error) v1.32-1 by Unknown via Local Repository
libidn2 (libidn2) v6.1.2-1 by Unknown via Local Repository
KSBA (libksba) v1.3.5-1 by Unknown via Local Repository
libplist (libplist) v2.0.0-2 by Unknown via Local Repository
OpenSSL 1.0 Libraries (libssl1.0) v1.0.2s-1 by Unknown via Local Repository
OpenSSL 1.1.1 Libraries (libssl1.1.1) v1.1.1c-1 by Unknown via Local Repository
libtasn1 (libtasn1) v4.13-1 by Unknown via Local Repository
libunistring (libunistring) v0.9.10-1 by Unknown via Local Repository
LZ4 (lz4) v1.7.5-1 by Unknown via Local Repository
LZMA Utils (lzma) v2:4.32.7-2 by Unknown via Local Repository
dotto+ (me.conorthedev.dotto+) v1.0.3 by ConorTheDev & Mirac via Local Repository
New Curses (ncurses) v6.1+20181013-1 by Unknown via Local Repository
New Curses (ncurses5-libs) v5.9-1 by Unknown via Local Repository
Nettle (nettle) v3.4.1-1 by Unknown via Local Repository
New GNU Portable Threads (npth) v1.6-1 by Unknown via Local Repository
iCleaner (org.altervista.exilecom.icleaner) v7.8.2 by Ivano Bilenchi  via Local Repository
BigBoss Icon Set (org.thebigboss.repo.icons) v1.0 by Unknown via Local Repository
p11-kit (p11-kit) v0.23.12-1 by Unknown via Local Repository
PreferenceLoader (preferenceloader) v2.2.4 by Sam Bingner  via Local Repository
Profile Directory (profile.d) v0-1 by Unknown via Local Repository
readline (readline) v8.0-1 by Unknown via Local Repository
Unc0ver Policy Softener (science.xnu.substituted) v1.0.0 by pwn20wnd  via Local Repository
Graphite Library (se.geometric.graphite) v1.1.2 by Geometric Software via Local Repository
TweakRestrictor (se.geometric.tweakrestrictor) v1.0.2 by Geometric Software via Local Repository
sed (sed) v4.5-1 by Unknown via Local Repository
shell-cmds (shell-cmds) v118-8 by Unknown via Local Repository
system-cmds (system-cmds) v790.30.1-2 by Unknown via Local Repository
Tape Archive (tar) v1.30-2 by Unknown via Local Repository
UIKit Tools (uikittools) v1.1.17-1 by Unknown via Local Repository
Alderis Color Picker (ws.hbang.alderis) v1.0.1 by HASHBANG Productions  via Local Repository
Cephei Tweak Support (ws.hbang.common) v1.15.1 by HASHBANG Productions  via Local Repository
Zebra (xyz.willy.zebra) v1.1.10 by Wilson Styres  via Zebra
System Info (xyz.xninja.systeminfo) v2.7.2-1 by ARX8x via Local Repository
XZ Utils (xz) v5.2.4-4 by Unknown via Local Repository

**Comment by Bradley0419** [comment]
> Please provide a tweak list

AppList (applist) v1.5.16 by Ryan Petrich  via BigBoss
APT (apt) v1.8.2-3 by Unknown via Bingner/Elucubratus
APT (apt-key) (apt-key) v1.8.2-1 by Unknown via Bingner/Elucubratus
APT 1.4 Transitional (apt1.4) v1:0 by Unknown via Bingner/Elucubratus
APT 0.7 Transitional (apt-key) (apt7-key) v1:0 by Unknown via Bingner/Elucubratus
Base Structure (base) v1-5 by Unknown via Bingner/Elucubratus
Bourne-Again SHell (bash) v5.0.3-2 by Unknown via Bingner/Elucubratus
Berkeley DB (berkeleydb) v6.2.32-1 by Unknown via Bingner/Elucubratus
RomanPad (beta.simalary.romanpad) v1.0 by Simalary (Chris)  via Packix
bzip2 (bzip2) v1.0.6-1 by Unknown via Bingner/Elucubratus
CA Certs (ca-certificates) v0.0.2 by Unknown via Bingner/Elucubratus
MDausch Utils (ch.mdaus.utils) v0.0.4 by Maxwell Dausch  via Maxwell Dausch's Repository
ShortLook (co.dynastic.ios.tweak.shortlook) v1.0.17 by Dynastic via Dynastic Repo
Flipswitch (com.a3tweaks.flipswitch) v1.0.16~beta8 by rpetrich  via rpetrich
AnimationsBeFastPlus (com.adamseiter.animationsbefastplus) v4.8 by eXqusic via Packix
PanCake (com.anthopak.pancake) v1.1 by AnthoPak via Packix
DigitalBattery13 (com.asterix.digitalbattery13) v1.0.0 by Asterix  via BigBoss
Snappy (com.bingner.snappy) v1.3.0 by Sam Bingner  via Bingner/Elucubratus
Batchomatic (com.captinc.batchomatic) v4.3.1 by Capt Inc  via BigBoss
libnotifications (com.cokepokes.libnotifications) v0.3-1 by CokePokes  via Phantom Apps LLC 
libCSPreferences (com.creaturecoding.libcspreferences) v1.4.5 by CreatureSurvive  via https://creaturecoding.com/repo/
shuffle (com.creaturecoding.shuffle) v1.2.8 by CreatureSurvive  via https://creaturecoding.com/repo/
libCSColorPicker (com.creaturesurvive.libcscolorpicker) v1.0.3 by CreatureSurvive  via https://creaturecoding.com/repo/
iCleaner Pro (com.exile90.icleanerpro) v7.8.3~beta1 by Ivano Bilenchi  via Ivano Bilenchi's Beta Repo
Zenumbra (com.foxfort.zenumbra) v1.0.3 by FoxfortMobile  via Foxfort Repo
Reddit No Ads (com.haoict.redditnoads) v0.0.1 by Hao Nguyen  via BigBoss
MImport (com.julioverne.mimport) v0.0~beta38 by julioverne  via julioverne
Noctis Neo (com.laughingquoll.noctis13) v1.2.4 by LaughingQuoll  via Chariz
PrefixUI (com.laughingquoll.prefixui) v1.2.6 by LaughingQuoll via Packix
Prysm (com.laughingquoll.prysm) v1.7.5 by LaughingQuoll via Packix
Quart (com.laughingquoll.quart) v1.1.2 by LaughingQuoll via Packix
Locale Profiles in UTF-8 (com.linusyang.localeutf8) v1.0-1 by Linus Yang  via BigBoss
Cr4shed (com.muirey03.cr4shed) v4.1.3 by Muirey03 via Packix
libimagepicker (com.muirey03.libimagepicker) v1.0.4 by Muirey03 via Packix
libMRYIPC (com.muirey03.libmryipc) v1.0 by Muirey03 via Dynastic Repo
Snapchat Bitmoji for ShortLook (com.neinzedd9.shortlook.plugin.contact-photo.snapchat) v1.0.4.1 by Dynastic via Dynastic Repo
Magma Evo (com.noisyflake.magmaevo) v2.0.1 by NoisyFlake  via Chariz
BetterWidgets (com.obumbravit.betterwidgets) v1.3-1+debug by 0ver$hadowed via Local Repository
CCSupport (com.opa334.ccsupport) v1.2.2 by opa334 via opa334's Repo
Choicy (com.opa334.choicy) v1.2.1 by opa334  via opa334's Repo
powerlogHelperdFix (com.opa334.powerloghelperdfix) v1.0 by opa334 via opa334's Repo
Ares (com.phoenix-dev.ares) v1.0 by Phoenix Dev via Dynastic Repo
Muze 4 (com.purdix.muze4) v1.04 by Kogulan (Purdix) via Packix
Cylinder (com.r333d.cylinder) v1.1 by Reed Weichler  via BigBoss
MailMend (com.rpetrich.mailmend) v0.2.1 by Ryan Petrich  via rpetrich
RocketBootstrap (com.rpetrich.rocketbootstrap) v1.0.9 by Ryan Petrich  via rpetrich
Substrate Safe Mode (com.saurik.substrate.safemode) v0.9.6003 by Jay Freeman (saurik)  via Bingner/Elucubratus
SettingsWidgets (com.shepgoba.settingswidgets) v1.1.2 by shepgoba via shepgoba's repo
PencilChargingIndicator (com.shiftcmdk.pencilchargingindicator) v1.2~b7 by shiftcmdk via shiftcmdk
AutoUnlockX (com.spark.autounlockx) v1.0.16 by Spark via SparkDev
CircleSettings (com.spark.circlesettings) v1.0.1 by Spark via SparkDev
libsparkapplist (com.spark.libsparkapplist) v1.0.9 by SparkDev via Dynastic Repo
libsparkcolourpicker (com.spark.libsparkcolourpicker) v1.0.0 by SparkDev via Dynastic Repo
SnowBoard (com.spark.snowboard) v1.3.2~Beta3 by Spark via SparkDev
Filza File Manager (com.tigisoftware.filza) v3.7.5-9 by TIGI Software  via BigBoss
MeltedCrayons (com.twickd.bermudalocket.meltedcrayons) v1.0.7 by bermudalocket  via Twickd
DopeConvos (com.twickd.ethan-whited.dopeconvos) v2.8 by Ethan Whited  via Twickd
Central (com.twickd.jake.central) v1.0.6 by Jake  via Twickd
BadgeBar (com.twickd.jannikcrack.badgebar) v1.2.0 by JannikCrack  via Twickd
Lynx (com.twickd.mtac.lynx) v1.4-3 by MTAC  via Twickd
BatchInstall - Online (com.you.batchinstall) v2019.12.14-22.54.23 by You via Local Repository
YKAdb (com.yourepo.ikghd.adb) v1.5 by iKG_HD  via iKG_HD - YouRepo
YouTubeKiller (com.yourepo.ikghd.youtubekiller) v3.2-6 by iKG_HD  via iKG_HD - YouRepo
Core Utilities (coreutils) v8.31-1 by Unknown via Bingner/Elucubratus
Core Utilities (/bin) (coreutils-bin) v8.31-1 by Unknown via Bingner/Elucubratus
Cydia Installer (cydia) v1.1.33 by Jay Freeman (saurik)  via Bingner/Elucubratus
Cydia Translations (cydia-lproj) v1.1.32~b1 by Jay Freeman (saurik)  via Bingner/Elucubratus
Darwin Tools (darwintools) v1.1-1 by Unknown via Bingner/Elucubratus
Debian Utilities (debianutils) v4.8.6-1 by Unknown via Bingner/Elucubratus
Diff Utilities (diffutils) v3.6-1 by Unknown via Bingner/Elucubratus
diskdev-cmds (diskdev-cmds) v593.221.1-1 by Unknown via Bingner/Elucubratus
Debian Packager (dpkg) v1.19.7-1 by Unknown via Bingner/Elucubratus
Essential (essential) v0-2 by Unknown via Bingner/Elucubratus
file (file) v5.35-2 by Unknown via Bingner/Elucubratus
Find Utilities (findutils) v4.6.0-2 by Unknown via Bingner/Elucubratus
iPhone Firmware (/sbin) (firmware-sbin) v0-1 by Unknown via Bingner/Elucubratus
GNU Cryptography (gcrypt) v1.8.3-1 by Unknown via Bingner/Elucubratus
gettext (gettext) v0.19.8-1 by Unknown via Bingner/Elucubratus
GnuPG (gnupg) v2.2.11-2 by Unknown via Bingner/Elucubratus
GnuTLS (gnutls) v3.5.19-1 by Unknown via Bingner/Elucubratus
grep (grep) v3.1-1 by Unknown via Bingner/Elucubratus
gzip (gzip) v1.9-1 by Unknown via Bingner/Elucubratus
Kalm (hi.my.name.is.ubik.kalm) v1.4.1 by ubik  via Chariz
Launch Daemon Controller (launchctl) v23-1 by Unknown via Bingner/Elucubratus
Link Identity Editor (ldid) v2:2.1.2+g5420cb5-1 by Jay Freeman (saurik)  via Bingner/Elucubratus
Activator (libactivator) v1.9.13~beta12 by Ryan Petrich  via rpetrich
APT (lib) (libapt) v1.8.2-3 by Unknown via Local Repository
APT (libapt-pkg) (libapt-pkg5.0) v1.8.2-3 by Unknown via Local Repository
Assuan (libassuan) v2.5.1-1 by Unknown via Bingner/Elucubratus
GNU Multiple Precision Arithmetic Library (libgmp10) v6.1.2-1 by Unknown via Bingner/Elucubratus
GnuPG Errors (libgpg-error) v1.32-1 by Unknown via Bingner/Elucubratus
libidn2 (libidn2) v6.1.2-1 by Unknown via Bingner/Elucubratus
KSBA (libksba) v1.3.5-1 by Unknown via Bingner/Elucubratus
libplist (libplist) v2.0.0-2 by Unknown via Bingner/Elucubratus
libskittycolor (libskittycolor) v1.0 by Skitty via Skitty's Repo
OpenSSL 1.0 Libraries (libssl1.0) v1.0.2s-1 by Unknown via Bingner/Elucubratus
OpenSSL 1.1.1 Libraries (libssl1.1.1) v1.1.1c-1 by Unknown via Bingner/Elucubratus
libtasn1 (libtasn1) v4.13-1 by Unknown via Bingner/Elucubratus
libunistring (libunistring) v0.9.10-1 by Unknown via Bingner/Elucubratus
LZ4 (lz4) v1.7.5-1 by Unknown via Bingner/Elucubratus
LZMA Utils (lzma) v2:4.32.7-2 by Unknown via Bingner/Elucubratus
Cercube for YouTube (me.alfhaily.cercube) v5.1.18 by Majd Alfhaily via Alfhaily APT
Rocket for Instagram (me.alfhaily.rocket) v3.7.1 by Majd Alfhaily via Alfhaily APT
peep (me.conorthedev.peep) v2.0.1 by ConorTheDev  via ConorTheDev's Repo
HomePlus Pro (me.kritanta.homepluspro) v1.2.2 by Kritanta  via kritanta's repo
Axon (me.nepeta.axon) v1.2 by Nepeta & Baw Appie via MERONA Repository
BegoneCIA (iOS 11, 12 and 13) (me.nepeta.begonecia-11) v0.3.2 by Nepeta  via alex_png's Repository
IconState (me.nepeta.iconstate) v0.1.0 by Nepeta  via Openpack Repo
Cydia Substrate (mobilesubstrate) v0.9.7101 by Jay Freeman (saurik)  via Bingner/Elucubratus
New Curses (ncurses) v6.1+20181013-1 by Unknown via Bingner/Elucubratus
New Curses (ncurses5-libs) v5.9-1 by Unknown via Bingner/Elucubratus
AppSync Unified (net.angelxwind.appsyncunified) v76.0 by Linus Yang, Karen/あけみ  via Karen/あけみ's Repo
SimpleActivationActions (net.limneos.simpleactivationactions) v0.1-1 by Elias Limneos  via BigBoss
Nettle (nettle) v3.4.1-1 by Unknown via Bingner/Elucubratus
New GNU Portable Threads (npth) v1.6-1 by Unknown via Bingner/Elucubratus
OpenSSH (openssh) v8.1-1 by Unknown via Bingner/Elucubratus
libcolorpicker (org.thebigboss.libcolorpicker) v1.6.8 by PixelFire  via BigBoss
BigBoss Icon Set (org.thebigboss.repo.icons) v1.0 by Unknown via Bingner/Elucubratus
p11-kit (p11-kit) v0.23.12-1 by Unknown via Bingner/Elucubratus
7-zip (POSIX) (p7zip) v16.02-1 by Unknown via Bingner/Elucubratus
PreferenceLoader (preferenceloader) v2.2.4 by Sam Bingner  via BigBoss
Profile Directory (profile.d) v0-1 by Unknown via Bingner/Elucubratus
readline (readline) v8.0-1 by Unknown via Bingner/Elucubratus
CocoaTop (ru.domo.cocoatop64) v2.0.2 by Domo via Local Repository
RoadRunner (se.nosskirneh.roadrunner) v1.0~beta2 by Andreas Henriksson via henrikssonbrothers
sed (sed) v4.5-1 by Unknown via Bingner/Elucubratus
shell-cmds (shell-cmds) v118-8 by Unknown via Bingner/Elucubratus
system-cmds (system-cmds) v790.30.1-2 by Unknown via Bingner/Elucubratus
Tape Archive (tar) v1.30-2 by Unknown via Bingner/Elucubratus
UIKit Tools (uikittools) v1.1.17-1 by Unknown via Bingner/Elucubratus
unrar (unrar) v5.6.4-1 by Unknown via Bingner/Elucubratus
unzip (unzip) v6.0+deb9u1-1 by Unknown via Bingner/Elucubratus
WallpaperLoader (wallpaperloader) v1.0 by Skitty via Skitty's Repo
wget (wget) v1.19.5-2 by Unknown via Bingner/Elucubratus
Cephei Tweak Support (ws.hbang.common) v1.15.1 by HASHBANG Productions  via Chariz
NewTerm (iOS 10 – 13) (ws.hbang.newterm2) v2.4 by HASHBANG Productions  via Chariz
Zebra (xyz.willy.zebra) v1.2~beta1b by Wilson Styres  via Zebra Beta
System Info (xyz.xninja.systeminfo) v2.7.2-1 by ARX8x via ARX8x
XZ Utils (xz) v5.2.4-4 by Unknown via Bingner/Elucubratus
zip (zip) v2.32-1 by Unknown via Bingner/Elucubratus

**Comment by ljuul646** [comment]
> Please provide a tweak list

Updated my comment with list

**Comment by ljuul646** [comment]
I Need to learn to read instructions better. Went through iCleaner and looks like it’s quart for me causing the issue

**Comment by himynameisubik** [comment]
All good :) It's Quart with disabled widget. Working on a fix.

**Comment by himynameisubik** [comment]
Will be fixed with 1.4.3.
