### ISSUE TITLE
Do not disturb icon

### ISSUE THREAD

**Issue by itsmekilla** [himynameisubik/Kalm-support#123]
The dnd icon is to close to the date
![69886BBF-4038-4051-B631-05E6ACE0B877](https://user-images.githubusercontent.com/66363807/83849190-804f5780-a6bb-11ea-8e8e-27ac4f42828c.jpeg)

**Comment by himynameisubik** [comment]
Kalm Preferences?
Did you add "Date gap"?

**Comment by itsmekilla** [comment]
No is there an option on the preference im gonna check


Sent from Yahoo Mail for iPhone


On Friday, June 5, 2020, 12:35 AM, ubik <notifications@github.com> wrote:




Kalm Preferences?
Did you add "Date gap"?

**Comment by itsmekilla** [comment]
My bad thanks next time ill look until i dont have options then i go to you.


Sent from Yahoo Mail for iPhone


On Friday, June 5, 2020, 12:37 AM, Carlos Guadarrama <carlos.guad76@gmail.com> wrote:

No is there an option on the preference im gonna check


Sent from Yahoo Mail for iPhone


On Friday, June 5, 2020, 12:35 AM, ubik <notifications@github.com> wrote:




Kalm Preferences?
Did you add "Date gap"?
