### ISSUE TITLE
The third party first-color is not much precise.

### ISSUE THREAD

**Issue by CySxL** [himynameisubik/Kalm-support#124]
General information:
===

**Kalm version:**
1.4.2
**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

https://pastebin.com/13ki28sP

https://pastebin.com/SBMpTJHz

Device information:
===

**iOS version and language:**
iOS13.3, Chinese(Traditional)
**Device:**
iPhoneX
**Jailbreak:**
Checkra1n 0.10.1

Bug description:
===

**Describe the bug:**

Third party color's first color does not correspond to ColorFlow5's color.

**How to reproduce:**
Just play a music with album cover

**Expected behavior:**
Correspond to ColorFlow5
**Screenshots:**
![DBE2EEAA-F653-4C64-A493-E60CE21E70FC](https://user-images.githubusercontent.com/15531137/83853809-63ad3100-a748-11ea-9bf7-e517998f34af.jpeg)
![DBCF6EE2-BA54-4A57-85C6-75C7C0C3AF8D](https://user-images.githubusercontent.com/15531137/83853825-6871e500-a748-11ea-8ec0-b494e0df6670.jpeg)

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Could you try disabling "Auto adjust brightness" and try if that fixes the issue?

**Comment by CySxL** [comment]
Sorry there were too much exciting new features so I didn't notice this! It works! Cheers!! 🥰🥰🥰
