### ISSUE TITLE
Option to color Kalm like this

### ISSUE THREAD

**Issue by samwllson9478** [himynameisubik/Kalm-support#127]
When you slide all the way down Kalm goes back to normal coloring but when you pull down at first the coloring is so beautiful. Just check the screenshots out with vibrancy on

![image](https://user-images.githubusercontent.com/62081609/83884729-53c72a00-a713-11ea-9b13-e7436c2a1a05.png)
![6B847E5E-E41E-4ABE-905E-37292F6E0898](https://user-images.githubusercontent.com/62081609/83884782-69d4ea80-a713-11ea-928d-d4d071ac7dd5.png)

**Comment by himynameisubik** [comment]
Vibrancy basically mask's off the text with the wallpaper as kinda "blurred bcolor". It will always look like the background of the text looks. You'd have to align your wallpaper, to get the same "color" you want when not pulled down completely.

**Comment by samwllson9478** [comment]
so there’s no way to make that the permanent color? because it goes away after pulling down all the way

**Comment by himynameisubik** [comment]
No. It's not a single color. Its your background image blurred and masked with the content. You can check that if you change the wallpaper position.
