### ISSUE TITLE
Customising 'Maximum Time Ahead'

### ISSUE THREAD

**Issue by imdadkadir** [himynameisubik/Kalm-support#128]
Is there any way instead of using the set time values, I can use my own specific time values for 'maximum time ahead' in 'Up Next'? Is there anyway to go into filza and do it myself?

**Comment by himynameisubik** [comment]
What do you mean by that? There is maxDaysAhead in your Preferences file, which is in hours. Does that help?

**Comment by imdadkadir** [comment]
![IMG_CB7E30C6B3BD-1](https://user-images.githubusercontent.com/51536591/83925521-3fb91200-a77f-11ea-9c6f-b3cb4fce396c.jpeg)

Instead of these times I'd like to have my own times such as 2 hours. I'm not sure how to change this in Filza could you guide me?

**Comment by himynameisubik** [comment]
No sorry. If you want to modify it, use the preferences file that is referred to in the main page of this issue tracker and change maxDaysAhead to how many hours you want.
