### ISSUE TITLE
Feature request: change order of time/date/weather

### ISSUE THREAD

**Issue by Chr1s97** [himynameisubik/Kalm-support#129]
**Request:**
Hi, 
I am missing out a function where I can resort time/date/weather. Especially the weather function. For time/date I still can ‚misuse‘ custom format. I would appreciate if the lock symbol (faceid) could get vertically adjustable as well. 
Best wishes

**Comment by himynameisubik** [comment]
Thanks for the request. This is not planned at the moment.

**Comment by himynameisubik** [comment]
A different implementation as it is compared to 2.0.0 with the three custom appearances will not be added. Sorry for the inconvenience, hope you understand.
