### ISSUE TITLE
Feature request: Custom text size 

### ISSUE THREAD

**Issue by domgregori** [himynameisubik/Kalm-support#13]
Is it possible to add a feature to change the font size? At the moment, the text seems too small.

**Comment by himynameisubik** [comment]
Will add it to enhancements, but not sure if this will be added any time soon.

**Comment by himynameisubik** [comment]
Overall custom scaling will be added in the next version.

**Comment by himynameisubik** [comment]
Putting this in 1.3.0 since it still needs some adjustments and will be one of a few major enhancements.

**Comment by himynameisubik** [comment]
Added in 1.3.0. Submitted to Packix.
