### ISSUE TITLE
Feature request: Kalm on Wallpaper Preview

### ISSUE THREAD

**Issue by libertig** [himynameisubik/Kalm-support#130]
Is it possible to improve how Kalm is displayed on the wallpaper preview? since it’s misaligned on that section. It would be a great detail for the tweak.

**Comment by himynameisubik** [comment]
Thanks for your request. However, this is not planned at the moment.

**Comment by himynameisubik** [comment]
It would require to much effort to fix this view as well. This will not be added. Sorry, hope you understand.
