### ISSUE TITLE
In landscape mode, the displacement bug that appears after opening the notification center.

### ISSUE THREAD

**Issue by w6511** [himynameisubik/Kalm-support#131]
General information:
===

**Kalm version:** 1.4.3

Device information:
===

**iOS version:** 13.5

**Device:** iPhone 8

**Jailbreak:** unc0ver 5.0.1

Bug description:
===

**Describe the bug:**
When the video is in landscape mode, open the notification center, the control module will shift.

**How to reproduce:**

1. Open a video
2. Horizontal screen
3. Open the notification center

**Expected behavior:**
No displacement.

**Screenshots:**
![20200607-154932000-iOS](https://user-images.githubusercontent.com/65994118/83973888-fbaf4400-a91b-11ea-8e21-99b68f0579ed.gif)

**Comment by w6511** [comment]
I found the reason, it is related to SmartRotate.

**Comment by himynameisubik** [comment]
Closing.

**Comment by w6511** [comment]
After many tests, it was found that the displacement bug is a problem of Kalm itself, not a tweak conflict.
