### ISSUE TITLE
Moves up too high when receiving a notification

### ISSUE THREAD

**Issue by w6511** [himynameisubik/Kalm-support#133]
General information:
===

**Kalm version:** 1.4.3

Device information:
===

**iOS version :** 13.5

**Device:** iPhone 8

**Jailbreak:** unc0ver 5.0.1

Bug description:
===

**Describe the bug:**
After a notification appears in the notification center, Kalm will move up as a whole, resulting in the weather not being displayed. If you slide the notification to the left, Kalm will return to its original position.

**How to reproduce:**

1. Notification appears in the notification center
2. Open the notification center
3. See error

**Expected behavior:**
Kalm does not move up overall.

**Screenshots:**
![20200608_032450000_iOS](https://user-images.githubusercontent.com/65994118/83990324-d9e5a980-a97b-11ea-8af1-ba2315694e5e.jpg)
![20200608-032336000-iOS](https://user-images.githubusercontent.com/65994118/83990389-10232900-a97c-11ea-871c-61db5d1562bb.gif)

Additional information:
===

**Tweak list:**
https://pastebin.com/RjvMzhni

**Comment by himynameisubik** [comment]
Can you enable "Up next" with an empty schedule to see if your problem persists?

**Comment by w6511** [comment]
When I turned on "Up next" with an empty schedule, my problem was solved. Should I always turn on this option?

**Comment by himynameisubik** [comment]
Please do so until the next version. I will fix this soon. Thanks for your cooperation and understanding! :)
