### ISSUE TITLE
Dots 2 incompatibility 

### ISSUE THREAD

**Issue by chrismonster13** [himynameisubik/Kalm-support#134]
Hello there! I have really been enjoying your Kalm tweak. I have also been enjoying how other devs have tried to integrate their tweaks into yours for the best lock screen experience. I recently have ran into an issue when I have Dots 2 installed. I noticed that when I have Dots 2 installed, when I get a notification, Kalm disappears until I unlock, and re-lock my device again, which can be seen by my included screenshots.

I know that Dots 2 isn't your tweak, but I have tried to contact the developer numerous times about this bug, but I can't seem to get into contact with them. Even if you are unable to do anything about this bug from your end with Kalm, is there a small possibility  you could possibly reach out to the developers of Dots 2 about this? They are @DavidJGoldman and @shyam_lad
I can provide any proof of purchase for anyone that needs to see it, if necessary.  The screenshot on the left is how Kalm is supposed to be, and the screenshot on the right is what happens if I get a notification while I have Dots 2 installed.
![IMG_2870](https://user-images.githubusercontent.com/26782418/84002518-8c931900-a936-11ea-9089-af1721f0c54c.png)
![IMG_2869](https://user-images.githubusercontent.com/26782418/84002529-9026a000-a936-11ea-9588-0f6aba20aa7c.png)

As i said previously, I know that Dots 2 is not your tweak, but they are all very beautiful together and I really appreciate everyone's work on all of them, I just wanted to make sure that someone was seeing my bug reports, as I didn't seen an issue tracker available for Dots 2. I hope you understand, thank you so much. Have a great day!!!

**Comment by himynameisubik** [comment]
Completely understand, however I'm probably not able to do anything on this case.

If I'm correct dots is here to hide everything besides the dots. No?
Maybe look into something like "hide/show clock"?

**Comment by chrismonster13** [comment]
Not as of recently. Recently Dots is meant to work with lots of other Lockscreen tweaks. Is there a possibility you could reach out to the developers about this? I know all of you guys have tons on your plate, I’m just a little lost as to how else I’m supposed to reach out to the devs of this tweak. I try my best to keep Kalm 😉 when reaching out to developers, but I feel like my messages get buried. Especially to these developers 😞

**Comment by himynameisubik** [comment]
I did reach out to them; https://twitter.com/HiMyNameIsUbik/status/1269920410151329792

And thanks for understanding, it's not the highest priority for me at the moment.

**Comment by himynameisubik** [comment]
Did you ever get an update @chrismonster13 ?

**Comment by chrismonster13** [comment]
Unfortunately not my friend. I haven’t been able to reach out to either developer about the tweak. It’s a shame, it’s one of my favorites! Reminds me, I forgot to close my Kalm issue. I’ll do it right now.
