### ISSUE TITLE
Feature request: Add an option to toggle auto choose dynamic coloring like version 1.3.4 and an option to disable Complications alignment

### ISSUE THREAD

**Issue by metyl2945** [himynameisubik/Kalm-support#135]
**Request:**
As i said, on version 1.4.3 you have to choose the accent color based on the wallpaper but i really don't like it. I like the way it used to be on 1.3.4. Auto choose the color to match your wallpaper. But not everybody like that so it should make into a toggle for everyone who like to use it.
About Complications alignment. I don't know it is from Kallm or Complications but I set Complications to the right screen where Kalm would be on the left screen side-by-side so it look nice. But whenever Kalm is in Up Next view Complications alignment downward so in the middle, it supposed to alignment with the Time and Date not in the middle. Hope you can do that. Best Wishes :))

**Comment by himynameisubik** [comment]
1.4.3 still selects a fitting color. Might not be the same as <1.4.0 but still matching your wallpaper. 

Not sure, what you mean with the Complications issue you're mentioning.

**Comment by metyl2945** [comment]
Oh, i will get you a pic for that
https://imgur.com/a/ABUpqE5

**Comment by himynameisubik** [comment]
I can't fix that unfortunately since this is coming from Complications.

**Comment by metyl2945** [comment]
Oh ok, i will contact Ben

**Comment by himynameisubik** [comment]
This only happens because Up Next is showing up vs not. Since if it's showing up, it needs more space.
