### ISSUE TITLE
When Vibrancy Effect is turned on, the edges of the time fonts will be jagged.

### ISSUE THREAD

**Issue by w6511** [himynameisubik/Kalm-support#136]
General information:
===

**Kalm version:** 1.4.3

Device information:
===

**iOS version:** 13.5

**Device:** iPhone 8

**Jailbreak:** unc0ver 5.0.1

Bug description:
===

**Describe the bug:**
When Vibrancy Effect is turned on, the edges of the time fonts will be jagged.

**How to reproduce:**

1. Go to Kalm's settings
2. Turn on Vibrancy Effect
3. Respring

**Expected behavior:**
The edges of the time font are not jagged.
**Screenshots:**
![20200608_105156000_iOS](https://user-images.githubusercontent.com/65994118/84023127-1e903580-a9ba-11ea-8f96-471b92b66241.png)
Turn on Vibrancy Effect

![20200608_105230000_iOS](https://user-images.githubusercontent.com/65994118/84023164-2cde5180-a9ba-11ea-9eb4-8c5f194f6650.png)
Turn off Vibrancy Effect

**Comment by himynameisubik** [comment]
Could you provide me your wallpaper?

**Comment by w6511** [comment]
![20200530_124923719_iOS](https://user-images.githubusercontent.com/65994118/84024351-500a0080-a9bc-11ea-9d9f-39c9440db056.jpg)

**Comment by himynameisubik** [comment]
This happens because of the really bright color unfortunately. If you change the color to something else and color all elements, this won't happen.
