### ISSUE TITLE
Feature request: custom gap below “up next” section.

### ISSUE THREAD

**Issue by DChannan** [himynameisubik/Kalm-support#138]
**Request:**

There is some space underneath the up next section that is inconsistent with the space underneath the time and date, causing either clipping in privacy mode or too much of a gap after being face id’d.

So I was thinking that a custom gap for the up next section could fix this?

**Comment by himynameisubik** [comment]
Change the notification padding to adjust that space.

**Comment by DChannan** [comment]
Apologies if I didn’t explain my issue properly.

The “up next” section has a bit of empty space at the bottom (atleast in compact mode). I want to move my complications closely to the Kalm elements. Gap from kalm -> complications is about 1/3rd of the gap in  non-privacy mode.
![71C7D091-C6ED-4040-A9F3-F3FB5E16D8B2](https://user-images.githubusercontent.com/7825301/84248681-0fb89880-ab0a-11ea-9a37-111f4a4cec2c.jpeg)
![4867B675-DB56-4D15-9187-B034DACC2971](https://user-images.githubusercontent.com/7825301/84248689-11825c00-ab0a-11ea-840d-0fbe15c7eccb.jpeg)

I don’t know if this is intentional, but I’d like to be able to move them closer in non-privacy mode, while keeping the same gap in privacy mode.

**Comment by himynameisubik** [comment]
Hmm, could you show me your Kalm Font Settings? And "More" padding?

**Comment by himynameisubik** [comment]
Will look into it but no ETA atm.

**Comment by DChannan** [comment]
No rush, already a great tweak. Anything extra is bonus :) thanks!

**Comment by DChannan** [comment]
If easier, I would be happy with a fixed total height of the tweak as well, so my other tweaks dont get moved down when I get face-ID’d.

**Comment by RiDDiX** [comment]
Any fix already planned?

**Comment by himynameisubik** [comment]
This is an additional feature. This is not a bug. And feature requests are currently on hold.

**Comment by RiDDiX** [comment]
Okay got it. thank anyway for this nice tweak!
