### ISSUE TITLE
Weather shows North Pacific Ocean as location 

### ISSUE THREAD

**Issue by tkanarek** [himynameisubik/Kalm-support#139]
General information:
===

**Kalm version:**
1.4.3

**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
13.5- English

**Device:**
XS Max
**Jailbreak:**
Uncover 13.5

Bug description:
===
Weather shows location of North Pacific Ocean. 
**Describe the bug:**
Weather on lock screen and in today center show the location as North Pacific Ocean. Have deleted weather app, as well as recommended .plist file. In addition have removed and redone loaded kale tweak and still issue persists. 
**How to reproduce:**

**Expected behavior:**

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Did you _reinstall_ the weather app?
Could you show me a screen of your weather app?

**Comment by tkanarek** [comment]
Yes I did reinstall.

**Comment by himynameisubik** [comment]
> Could you show me a screen of your weather app?

**Comment by himynameisubik** [comment]
Closing as of no reply.
