### ISSUE TITLE
Feature request: Letter spacing

### ISSUE THREAD

**Issue by mordechaih** [himynameisubik/Kalm-support#141]
**Request:** Adjust letter spacing.

I love the level of customization Kamp allows, but the designer in me wants small, capitalized text to have wider letter spacing for better readability. 

Could this be added at some point?
Thanks so much for your time and your hard work!

**Comment by himynameisubik** [comment]
Thanks! Interesting idea, feature requests are currently on hold though. Maybe at a later stage.

**Comment by himynameisubik** [comment]
This would unfortunately introduce other issues and provide a not great user experience. Sorry, this will not be added.
