### ISSUE TITLE
Delay during touch to wake on lock screen and Siri activating when power button is pressed.

### ISSUE THREAD

**Issue by parkstevens8** [himynameisubik/Kalm-support#144]
Kalm Version 1.4.3

https://pastebin.com/ryVXb4Pk

Device information:
===

iOS 13.5 English

iPhone X

unc0ver

Bug description:
Siri Activation and tap delay.

While Phone is off clicking power button activates siri without holding down. Also a delay when using tap to wake.

Leave phone off for around 5-10min and tap the screen or click the power button.

Siri will activate when power button is pressed and screen will take an extra second or two to turn on if tapped.

I disabled all tweaks but Kalm and it still persists.

**Comment by himynameisubik** [comment]
Tweak list? Sounds like another tweak interfering.

**Comment by parkstevens8** [comment]
https://pastebin.com/q5cN2iGU

**Comment by himynameisubik** [comment]
Did you disable all other tweaks and try?

**Comment by parkstevens8** [comment]
Yes and it still occurs

**Comment by himynameisubik** [comment]
Can't reproduce this issue at all. Does it happen with an older version of Kalm too?

**Comment by parkstevens8** [comment]
Yes also occurs in 1.4.2

**Comment by himynameisubik** [comment]
Can't reproduce this issue. Feel free to request a refund via email and send me the receipt you received from Chariz. Sorry! ;(
