### ISSUE TITLE
Kalm bug

### ISSUE THREAD

**Issue by QubismFan** [himynameisubik/Kalm-support#145]
General information:
===

**Kalm version:**
1.4.3

**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information: 
===

**iOS version and language:**
13.4.1

**Device:**
iPhone 11 Pro Max

**Jailbreak:**
unC0ver

Bug description:
===

**Describe the bug:**
I bought Kalm last night because it looks awesome but it completely crashes my Jailbreak. I've tried many ways to fix it and none of them see to work. It stops all my tweaks working. It starts with a blank screen, then eventually resets the phone completely and then I have to load uncover without tweaks. I then use iCleanerPro to disable Kalm, then ReJailbreak and remove the package. This is the only way to get my jailbreak back. It's such a shame because it looks like an awesome tweak. I'll have to go back to the other (less good) lock screen tweaks.

Do you know of a fix? If not, can I have a refund please.

**How to reproduce:**

**Expected behavior:**

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
The only thing you could try is disabling "Up Next" or follow these steps (mainly (re-)installing the stock apps) from here: https://github.com/himynameisubik/Kalm-support#general-steps-to-try-before-creating-an-issue

**Comment by QubismFan** [comment]
Hi,

I've tried all that but as soon as I install the tweak, everything goes wrong. I even disabled all my other tweaks and tried. It just doesn't seem to like my phone.

**Comment by himynameisubik** [comment]
Can you provide a crashlog? If not, feel free to request a refund by sending me the Chariz receipt.

**Comment by himynameisubik** [comment]
Feel free to either request a refund and include your Chariz Receipt (not a screenshot of it, but forward the email) or create a new issue and using the template provided with the needed information such as tweak list, crashlog and kalm preferences.
