### ISSUE TITLE
Time tinted when using third-party coloring despite disabling tinting

### ISSUE THREAD

**Issue by drippyer** [himynameisubik/Kalm-support#146]
General information:
===

**Kalm version:**
2.0.1

**Kalm preferences file:**
https://pastebin.com/yLYjV97L

Device information:
===

**iOS version and language:**
US English on iOS 13.5

**Device:**
iPhone X (iPhone10,6)

**Jailbreak:**
checkra1n 0.10.2

Bug description:
===

**Describe the bug:** 
Despite the tint for the Time element being disabled, the tint persists.
This appears to only be the case for the Time and no other elements.

**How to reproduce:**
1.  Enable Third-party Colors
2. Go into the Tinted Elements submenu
3. Disable tint for all individual elements
4. Respring
5. Unlock device
6. Play audio to update media controller
7. Skip to next audio track
8. See Time element adjust its tint

**Expected behavior:**
All elements should remain one color

**Screenshots:**
https://i.imgur.com/M2SiXgc.gifv

Additional information:
===

**Tweak list:**
https://pastebin.com/BhGTkBG9

**Crashlog:**
N/A

**Comment by drippyer** [comment]
Additionally, the gifv posted with the issue displays a bug in which Kalm fades away with changes in either the media or notification list. Not sure if that's an expected behavior so I didn't want to make a whole issue for it.

**Comment by CySxL** [comment]
Also got the fade away bug while tapping on the Grupi cell.  

So I downgrade lol

**Comment by himynameisubik** [comment]
Time element is tinted in the secondary color of ColorFlow or Artsy.

If you don't want them to be tinted disable Third party colors.

**Comment by drippyer** [comment]
Are all items not tinted to ColorFlow or Artsy?

When all other elements are disabled they are not tinted by ColorFlow, Time is the only one with this behavior.

**Comment by himynameisubik** [comment]
Sorry I'm not sure what you're going for. What do you exactly want?

Currently, time is tinted in Artsy/ColorFlow secondary color.

**Comment by drippyer** [comment]
Correct, I am personally looking for it to remain white while allowing the rest of the elements to be tinted. Often the ColorFlow color is not easily legible on my wallpaper and having it remain white ensures that is always legible.

Moreover, the rest of the elements perform the way I expect time to work. Even though ColorFlow/Artsy tinting is enabled, disabling an element within the individual element settings causes them to ignore all tinting.

**Comment by himynameisubik** [comment]
Ooh, so you say, even if time tinting is disabled, it still gets tinted if third party coloring is enabled?

**Comment by drippyer** [comment]
Correct!

**Comment by himynameisubik** [comment]
All right, now it makes sense. Will investigate this issue.

**Comment by drippyer** [comment]
Unfortunately I am still experiencing the same phenomenon. The time continues to be tinted according to ColorFlow/Artsy tint despite that element being disabled.

Sorry to be a hassle :/

**Comment by Riohh** [comment]
> Unfortunately I am still experiencing the same phenomenon after updating to 2.0.2. The time continues to be tinted according to ColorFlow/Artsy tint despite that element being disabled.
> 
> Sorry to be a hassle :/

I'm having the same issue on 2.0.2

**Comment by himynameisubik** [comment]
Will check it out

**Comment by himynameisubik** [comment]
Will be fixed with the next version. Sorry for the inconvenience.

**Comment by himynameisubik** [comment]
2.0.3 is out now.
