### ISSUE TITLE
2 lock screen bugs

### ISSUE THREAD

**Issue by rkycyku** [himynameisubik/Kalm-support#147]
General information:
===

**Kalm version:** 
2.0.1

**Kalm preferences file:**
https://pastebin.com/uT2yTqAg 

Device information:
===

**iOS version and language:**
12.4.6 - Albanian 

**Device:**
iPhone 6

**Jailbreak:**
Checkra1n (Bootra1n)

Bug description:
===

**Describe the bug:**
1. When the Notepad tweak is installed and the privacy option is enabled the up next doesn’t show correctly.
2. When device is unlocked and swiping up on the notifications center it’s kinda buggy it goes up and down.

**Screenshots:**

![4198DE64-A3CD-4ABF-AE99-60F3C1F3F917](https://user-images.githubusercontent.com/48863882/85897337-6b696e00-b7fa-11ea-9ef3-76455e0b0114.png)

**Comment by himynameisubik** [comment]
Did this happen with 1.4.3? Unfortunately can't test this as Notepad was discontinued. Maybe change the notification padding?

**Comment by rkycyku** [comment]
No, it worked perfectly with 1.4.3. I downgraded now so no problem i will use the 1.4.3 version.

**Comment by himynameisubik** [comment]
All right, thanks a lot for understanding. I'll try to look into it but I'll probably won't be able to. Will re-open if anything pops up that could have an impact.
