### ISSUE TITLE
Custom position not working

### ISSUE THREAD

**Issue by GoldenChaos** [himynameisubik/Kalm-support#148]
General information:
===

**Kalm version:** 2.0.1

Device information:
===

**iOS version and language:**

**Device:** iPhone 6s

**Jailbreak:** unc0ver

Bug description:
===

**Describe the bug:**
The Custom Position setting (Under “More”) does not actually change the positioning or do anything anymore for that matter. This seems to be a regression. 

**How to reproduce:** Attempt to change the positioning using the custom positioning attribute. Witness the lack of positioning change.

**Comment by himynameisubik** [comment]
Please provide the information asked in the template such as tweak list, settings file etc. Will be reopened as it's updated.
