### ISSUE TITLE
Crash on custom time

### ISSUE THREAD

**Issue by innuendofloyd** [himynameisubik/Kalm-support#149]
On latest 2.0.1.
Device go in safe mode if custom time is set to H:mm instead of default HH:mm
Automatically enters safe mode in specific time range between 1:00 and 9:59.
Ios 12.4

**Comment by himynameisubik** [comment]
Please create your issue report with the provided template and the needed information such as settings and crash report.

**Comment by himynameisubik** [comment]
I'll reopen this as soon as the missing information is added.

**Comment by innuendofloyd** [comment]
Sorry for not provide what needed. Checked out that bug is now solved. Thank you!
