### ISSUE TITLE
Auto Adjust Color keeps reverting to being turned on

### ISSUE THREAD

**Issue by ImpetuousRacer** [himynameisubik/Kalm-support#150]
Setting keeps reverting to being on...
General Settings >Colors > Additional Options > Auto Adjust Color

I turn off and respring, everything works. And later on it reverts to being on without touching that setting again.

Version 2.0.1 started since 2.0.0

**Comment by CySxL** [comment]
Same with mine. 

Noticed that happening while u change between light/Dark mode.
