### ISSUE TITLE
Several bugs report and tired ☹️

### ISSUE THREAD

**Issue by CySxL** [himynameisubik/Kalm-support#151]
General information:
===

**Kalm version:**
2.0.1
**Kalm preferences file:**
Put it on www.pastebin.com.

https://pastebin.com/eTym4TWm

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
iOS13.3. Traditional Chinese
**Device:**
iPhoneX
**Jailbreak:**
Checkra1n

Bug description:
===

**Describe the bug:**

1 . Tapping on Grupi cell would make the time/date area fade away a while, pretty annoying.

2. Auto Adjust Color automatically turn on itself while changing between light/ dark mode.

3. CUSTOM Position not working at all 

4. Gap calculation wrong: Because Kalm takes up so many spaces that I can't even get my NextUp2 display on bottom of screen.

**How to reproduce:**

**Expected behavior:**

**Screenshots:**
![F73F08B0-FF2B-4A91-967B-E243202384F1](https://user-images.githubusercontent.com/15531137/85964902-b4cddf00-b9ed-11ea-9776-934fe22231ac.png)
The only way that I can display NextUp2 on bottom of screen, and it makes my Grupi overlap on the date/time, which never occur in previous version of Kalm.
Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Please don't report multiple issues in one ticket.
