### ISSUE TITLE
Opening notification leads to respring iOS12

### ISSUE THREAD

**Issue by skapein** [himynameisubik/Kalm-support#152]
General information:

Kalm version: 2.0.1

Kalm Preferences file:

https://pastebin.com/7cKtG6Uw

iOS version and language:
12.4 EN

Device: iPhone 7 

Jailbreak: Uncover 4.3.1

Describe the bug:
When I enter the notification center, I scroll down and want to open a notification this causes me a respring.
I uninstalled the other tweaks but the problem was still there, it was only solved by uninstalling kalm.
Here's a respring at the moment when I presione "show less"
https://imgur.com/gallery/pkf8vkK

Tweak List:
7-zip (POSIX): 16.02-1
AppList: 1.5.16
AppStore++ (iOS 11 - 13): 0.9.11
AppSync Unified: 78.0
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
Base Structure: 1-5
Bazzi 2: 2.0.8
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
Bourne-Again SHell: 5.0.3-1
bzip2: 1.0.6-1
CA Certs: 0.0.2
CallSlicer: 1.4
CCModules Pro: 1.0.2
CCModules: 1.5-1
CCMusicArtwork: 2.2.0
CCSupport: 1.2.2
Cephei Tweak Support: 1.15.1
ColorBanners 2 (Packix): 1.2.4
Colorful Widgets: 0.0.5-9
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
CustomPlayer: 1.6.1-1
Cydia Installer: 1.1.36
Cydia Substrate: 0.9.7100~b4
Cydia Translations: 1.1.32~b1
DarkHangouts: 1.0.0
Darwin Tools: 1-6
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
file: 5.35-2
Filza File Manager : 3.7.4-12k
Find Utilities: 4.6.0-2
FingerTouch: 0.0.6b2
FingerTouchReachabilityFix12: 1.1
Flame: 1.3
FloatingDock: 1.5
ForceInPicture: 1.1
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
GoodWiFi: 0.0~beta5a
grep: 3.1-1
gzip: 1.9-1
HideDots: 1.5
iCleaner Pro: 7.8.3
Instagram ++: 1.8r-328
iOS Firmware: 12.4
iPhone Firmware (/sbin): 0-1
Jailbreak Resources: 1.0~b26
Kalm: 2.0.1
KSBA: 1.3.5-1
LeaveMeAlone: 2.3.1
libbulletin: 0.1-153
libcolorpicker: 1.6.8
libCSPreferences: 1.4.7
libidn2: 6.1.2-1
libMRYIPC: 1.0
libnotifications: 0.3
libplist: 2.0.0-2
libSparkAppList: 1.0.9
libsparkcolourpicker: 1.0.0
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.1+elucubratus2
LPMAutoLockTime: 1.0.1
LyreCC: 1.1
LyricsExplorer: 1.2.2
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Magma Evo: 2.0.3
MDausch Utils: 0.0.4
Modern Battery: 1.0.0
Navale: 2.2.2
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
Nimbus: 1.0
OpenSSL 1.0 Libraries: 1.0.2s-1
p11-kit: 0.23.12-1
plutil: 0.2.1
PowerSelector (iOS 11 & 12): 1.2.1
PreferenceLoader: 2.2.4
PrefixUI: 1.2.6
Profile Directory: 0-1
Prysm: 1.7.5
readline: 8.0-1
ReProvision (iOS 10 - 13): 0.5~release
RocketBootstrap: 1.0.9
Schmusic: 1.4.6
sed: 4.5-1
shell-cmds: 118-8
shuffle: 1.2.9
Signing Certificate: 0.0.1
Slices 3: 3.1.3
SmartBattery: 2.7-1
SnowBoard: 1.3.3~Beta3
Social Downloader: 1.1
Substrate Safe Mode: 0.9.6003
SwipeForMore: 1.1.7
SwipeSelectionX: 1.6.1-2
System Info: 2.7.2-1
System Memory Reset Fix: 2.0
system-cmds: 790.30.1-2
TagExplorer: 1.6.5
Tape Archive: 1.30-2
Trust Cache Injector: 0.4~b5
Twitter ++: 1.2r-82
uasharedtools (iOS 11): 2.2r-94
uasharedtools: 2.2r-94
UIKit Tools: 1.1.17-1
Ultrasound: 1.2.10
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
Viola: 1.9.5
XZ Utils: 5.2.4-4
YouTube Tools: 4.0
YT ++ for YouTube: 1.4r-106
zip: 2.32-1

Crashlog:
https://pastebin.com/0U5kQkfu

**Comment by himynameisubik** [comment]
Please provide the information that is required from the issue template. Will reopen when information is added.

**Comment by skapein** [comment]
> Please provide the information that is required from the issue template. Will reopen when information is added.

I'm sorry, I hope this information is enough, if you need more tell me

**Comment by himynameisubik** [comment]
Did you disable all tweaks and try?

**Comment by himynameisubik** [comment]
Works fine on my iOS12 device. Please check your tweaks.

**Comment by skapein** [comment]
> Works fine on my iOS12 device. Please check your tweaks.

I disable the rest of the tweaks but the problem persists, i came back to version 1.4.3 where everything works fine

**Comment by yuwei095** [comment]
Hello, 

Same here on iOS 13.5.
Seems to be temporarily fixed if interacting with iOS system notifications, like Do Not Disturb. Upon haptic touching and pressing disable, other notifications could be opened temporarily without issue.

**Comment by himynameisubik** [comment]
That's really odd but great info and help. @skapein could you try @yuwei095's workaround please?

Thanks @yuwei095 👍

**Comment by yuwei095** [comment]
Hi, the tweak is stable now, but I’ve discovered some new things after messing with the settings. Let me categorize into the 3 different modes.

**Default**
1. All settings at default work fine
2. Adjusting only the gap slider for weather works fine
3. Chronic resprings started when I adjusted the gap sliders {weather:-2.8,time:6.1, date:4.0} (setting I had on first post)
4. Everything in 3 worked fine when I changed the weather setting to vertical

**Compact**
1. Resprings even when everything left at default. 
2. Changed weather to vertical, disabled weather altogether, same result: chronic resprings

**Large**
1. Every variation I tested worked fine, even when messing with the gap sliders, and weather module

**Other Observations**
1. Resprings occur when interacting with notifications
2. It seems as if the notifications are affected by Kalm to be “backloaded” (visible, but interaction would cause respring) 
3. Do Not Disturb banner on the Notification Center would be “front loaded” (visible and can interact), and would bring existing notifications to the front after interacting with the Do Not Disturb notification
4. Environment in 3 can be destroyed as quickly one new notification coming in, the longest lasting being 2-3 new notifications
5. Situation reverts back to 2

Hope this information helps! Interested in the actual thing causing this problem, and hope you can figure it out. No rush though, still a great tweak!

**Comment by himynameisubik** [comment]
Hmm, did you observe these problems while _only_ having Kalm enabled? I can't seem to reproduce these issues. And I'm also using the compact mode 24/7 and never have any resprings.

**Comment by IvanKulagin** [comment]
Hi, I also have resprings on iPhone 11 Pro Max, iOS 13.5, unc0ver 5.0.1. I can confirm @yuwei095 words that compact style causes resprings even with default settings. I've tested it with everything except Kalm disabled in iCleaner

**Comment by skapein** [comment]
> That's really odd but great info and help. @skapein could you try @yuwei095's workaround please?
> 
> Thanks @yuwei095 👍

I followed @yuwei095  tip but the problem continuos

**Comment by himynameisubik** [comment]
I can't reproduce this issue that leads to a respring with notifications on any of my test device. 

Sorry for not being able to give you a better answer. Feel free to request a refund.

**Comment by IvanKulagin** [comment]
> I can't reproduce this issue that leads to a respring with notifications on any of my test device.
> 
> Sorry for not being able to give you a better answer. Feel free to request a refund.

I can give you a crash report if it will help somehow

**Comment by himynameisubik** [comment]
Crashlog was attached above already. If you disabled all other tweaks and it's still not working, feel free to request a refund.

**Comment by IvanKulagin** [comment]
> Crashlog was attached above already. If you disabled all other tweaks and it's still not working, feel free to request a refund.

Btw just checked 1.4.3 and it doesn’t have any problems with notifications. Guess I’ll stay on it, love your tweak!
