### ISSUE TITLE
Compatibility with Axon

### ISSUE THREAD

**Issue by oo3mL** [himynameisubik/Kalm-support#154]
General information: Not sure if you can fix or Axon needs to fix but starting with 2.0.1, anytime I have a notification or clear a notification with Axon on, it pushes the Kalm elements down to the center of the screen. 
===

**Kalm version:2.0.2

**Kalm preferences file: pastebin.com/YZAXv2gd
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
13.5.1
**Device:**
XS Max
**Jailbreak:**
unc0ver 

Bug description:
===

**Describe the bug:**
See gen info

**How to reproduce:**
When notification received and Axon is used, when you clear the notification when swiping, it moves the elements. Also sometimes when I turn on the screen as well. 

**Expected behavior:**

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Please provide the additional info that is missing. Will reopen it then.

**Comment by himynameisubik** [comment]
Also, it's probably because of using custom position.

**Comment by himynameisubik** [comment]
Duplicate of #156. See my response there.
