### ISSUE TITLE
Large Appearance will cause the text at the bottom of the lock screen to overlap with the player.

### ISSUE THREAD

**Issue by w6511** [himynameisubik/Kalm-support#155]
General information:
===

**Kalm version:**2.0.2

**Kalm preferences file:**
https://pastebin.com/xkKQrysQ

Device information:
===

**iOS version:**iOS 13.5.1

**Device:**iPhone 8

**Jailbreak:**checkra1n

Bug description:
===

**Describe the bug:**
Large Appearance will cause the text at the bottom of the lock screen to overlap with the player.
In addition to changing the Large, the other are the default settings.

**Expected behavior:**
Large Appearance will not overlap the text at the bottom of the lock screen with the player.

**Screenshots:**
![20200702_035842000_iOS](https://user-images.githubusercontent.com/65994118/86316218-cbc73800-bc5e-11ea-86d5-4557b21a93b6.jpg)

**Comment by himynameisubik** [comment]
What's the normal behavior? I'm pretty sure this is normal as the notifications lay over the unlock text view.
