### ISSUE TITLE
Automatic repositioning when using custom position

### ISSUE THREAD

**Issue by mercenary58** [himynameisubik/Kalm-support#156]
General information:
===

**Kalm version:**v2.0.2

**Kalm preferences file:**
https://pastebin.com/j4P9Miyq

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
IOS 13.5, English
**Device:**
iPhone 7(9,3)
**Jailbreak:**
unc0ver v5.2.0

Bug description:
===
alignment issue when receiving notification
**Describe the bug:**
im using kalm v2.0.2 as ubik said this solves alignment issue. i was getting the issue ever since i updated to v2 of kalm and this update gave me relief. upon updating, i wanted to test if its really fixed so i asked my brother to text me a message. sadly, the issue was not fixed for me, i tried re installing ,still no fix. this alignment issue occurs when i receive a notification and the only way to fix is to clear all notifications but when receiving another 1, the issue comes back.
**How to reproduce:**

**Expected behavior:**

**Screenshots:**
![kalm with notifs](https://user-images.githubusercontent.com/67646627/86377080-c75f4700-bc7f-11ea-99c3-a8f14935c19a.jpg)
![kalm no notifs](https://user-images.githubusercontent.com/67646627/86377086-c9290a80-bc7f-11ea-919f-4b10ceb0cd6a.PNG)

Additional information:
===

**Tweak list:**
https://pastebin.com/xTrWGCuDg

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Add your preferences file.

**Comment by himynameisubik** [comment]
Also, it's probably because of using custom position. Custom position will automatically move Kalm up if you get a notification to give the notification list more space.

**Comment by mercenary58** [comment]
> Add your preferences file. Will reopen after.

How do I add preference file?

**Comment by mercenary58** [comment]
> Add your preferences file. Will reopen after.

Found out how to add preference file and just added it. 👌

**Comment by himynameisubik** [comment]
All right, yeah this is linked to custom positioning as I said before. I will add a toggle to disable the automatic repositioning.

**Comment by mercenary58** [comment]
> All right, yeah this is linked to custom positioning as I said before. I will add a toggle to disable the automatic repositioning.

Great thanks a lot!

**Comment by himynameisubik** [comment]
2.0.3 is out now.
