### ISSUE TITLE
Kalm lockscreen/ notification center respring bug

### ISSUE THREAD

**Issue by adrsalvador1** [himynameisubik/Kalm-support#157]
General information:
===

**Kalm version:**
2.0.2

**Kalm preferences file:**
https://pastebin.com/kjcn4V0L

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
13.5, English

**Device:**
iPhone XS Max

**Jailbreak:**
Unc0ver 5.2.0

Bug description:
===

**Describe the bug:**
Just causes the device to respring. Does not go into safe mode; remain in jailbreak state. 

**How to reproduce:**

Bring down Notification Center/ lock screen; occurs randomly 

Additional information:
===

**Crashlog:**
https://pastebin.com/JbgSqj3h

**Comment by himynameisubik** [comment]
Provide tweak list and reopen please.
