### ISSUE TITLE
Lock Icon overlaps weather and condition 

### ISSUE THREAD

**Issue by tVance20** [himynameisubik/Kalm-support#16]
**Describe the bug**
When turn on Lock align instead of aligning it stay in the same spot as usual and causes the weather and conditions to appear underneath the lock icon.

**How to reproduce**
1. Go to 'Zebra or Cydia'
2. Click on 'Update Kalm'
3. Respring 

**Expected behavior**
I expected the lock to align with the text that way it does not overlap

**Screenshots**
![E4417900-420C-4E3A-B014-59F52DCEF053](https://user-images.githubusercontent.com/51184313/74177410-497e9e80-4bff-11ea-9312-d98c447d67bf.png)

**iOS Version:**
13.2.3
**Device:**
IPX
**Device language:**
English
**Tweak list:**
https://pastebin.com/KJjiv5B3

**Crashlog:**
N/A

**Additional context**
I’ve disabled all tweak through icleaner pro and got the same result. I don’t actually know how to make the error reoccur because I get the error as soon as I update!

**Comment by himynameisubik** [comment]
Could you attach a screenshot with all other tweaks disabled that show the same behaviour? I can't reproduce this. The lock icon should be aligned to the left, if you activated "Align Lock Icon"

**Comment by tVance20** [comment]
![3D7BD57B-EFEB-4CE7-9D89-6B5A49CD3E88](https://user-images.githubusercontent.com/51184313/74181910-b39b4180-4c07-11ea-8b20-f459efbb5754.png)

**Comment by himynameisubik** [comment]
Hmm, did you try to remove the preferences file already?

**Comment by tVance20** [comment]
Yes I actually done that before trying icleaner. The lock location seemed
to be fine on the initial release but as soon as I update and respring it
does that. This actually isn’t the only tweak i’ve had this problem with.

**Comment by himynameisubik** [comment]
So 1.0.0 works fine? Could you try installing LatchKey?

**Comment by tVance20** [comment]
Yes 1.0.0 works perfectly! LatchKey also works! Seem to be a good temporary fix.

**Comment by himynameisubik** [comment]
Can you check if LatchKey works if you don't change anything in LatchKey and just enable it? It's really weird, because the lock icon should also be slightly smaller than in your screens.

**Comment by tVance20** [comment]
I set all the setting in latchkey to default and it’s now normal. Is this how it should look?
![BE44B6A5-8CF9-42ED-856F-4357A3294EA2](https://user-images.githubusercontent.com/51184313/74184960-5a361100-4c0d-11ea-845c-038c21453307.png)

**Comment by himynameisubik** [comment]
Yep, this is exactly correct. This is really weird tho. I assume it has something to do how I check if the device has a lock icon or not. Thanks for testing and glad it's working with this workaround. I'll check if I can find a different way to check that. Really strange tho that this is only 1 report about this so far.

**Comment by tVance20** [comment]
Thank you as well for all the help. Hope you can narrow it down and figure it out some how. Will I need to open a new case that happens to be going on with the big because I believe it also fall under this?When ever I update whenever I turn on calendars and reminders it choses one or the other and never both.

**Comment by himynameisubik** [comment]
Sorry I don't understand what you mean. But if you have another issue, please create a new one so it's easier for the future if anyone has a similar issue.

**Comment by himynameisubik** [comment]
Oh, I think I got it. Did you ever have LatchKey installed? If so, please try to uninstall LatchKey (if you don't need it) and then *remove* the preferences file of LatchKey with Filza. I think that might be the issue, because I'm checking a value of the LatchKey preferences file, to see if it's enabled or not but I forgot to check if LatchKey is still installed.

**Comment by tVance20** [comment]
Yes I recall having LatchKey installed once upon a time. I removed
LatchKey now it’s seems to be working fine. I actually did not find any
preferences to remove.

Get Outlook for iOS <https://aka.ms/o0ukef>
------------------------------
*From:* ubik <notifications@github.com>
*Sent:* Monday, February 10, 2020 3:21:35 PM
*To:* himynameisubik/Kalm-support <Kalm-support@noreply.github.com>
*Cc:* tVance20 <tristenvance20@gmail.com>; Author <author@noreply.github.com
>
*Subject:* Re: [himynameisubik/Kalm-support] Lock Icon overlaps weather and
condition (#16)


Oh, I think I got it. Did you ever have LatchKey installed? If so, please
try to uninstall LatchKey (if you don't need it) and then *remove* the
preferences file of LatchKey with Filza. I think that might be the issue,
because I'm checking a value of the LatchKey preferences file, to see if
it's enabled or not but I forgot to check if LatchKey is still installed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/himynameisubik/Kalm-support/issues/16?email_source=notifications&email_token=AMGQFOIAD7K6C3SDMA77DF3RCHAN7A5CNFSM4KSTG5P2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELKKVIQ#issuecomment-584362658>,
or unsubscribe

**Comment by himynameisubik** [comment]
I have just tested it, it's definitely this. I will push a quick fix to Packix later. 1.0.3. Thanks for the time you took out of your day to help fixing this issue! :)
