### ISSUE TITLE
Feature request: Tapping things to open respective apps

### ISSUE THREAD

**Issue by iamtheCHiLDiSH** [himynameisubik/Kalm-support#160]
I love this tweak and was defo worth the money, but I would love to see an implementation of tapping the LS text to open their respective apps, like the weather widget would open the weather app, or the Up Next widget opening either calendar or reminders, depending on where the subheading is coming from. Keep up the amazing support tho, you've done a v good job

**Comment by himynameisubik** [comment]
Touch/tap interactions are not planned to be added to Kalm.
