### ISSUE TITLE
Kalm 2.0.0+ doesn’t work well with Hyperion

### ISSUE THREAD

**Issue by CoolOrbit** [himynameisubik/Kalm-support#162]
General information:
===

**Kalm version:**
Kalm 2.0.3

**Kalm preferences file:**
https://pastebin.com/6eyAfPcF

Device information:
===

**iOS version and language:**
iOS 13.5, English

**Device:**
iPhone XS

**Jailbreak:**
Unc0ver

Bug description:
===

**Describe the bug:**
When locking the device from the home screen or within an app (anywhere but from the lockscreen) Kalm will cause the clock to disappear after a second on the AOD. This is usually permanent until I unlock/lock again from the lockscreen but occasionally it will show up again on its own after some amount of seconds.

I believe what is happening is the clock is just moving up off the screen because if you use the large preset the clock won’t fully disappear it will just be 3/4th of the way off the screen.

**How to reproduce:**
1. Unlock device
2. Go to home screen or anywhere but the lockscreen
3. Lock device and wait a second on Hyperion’s AOD

NOTE: if using the Kalm default appearance it will sometimes just flash and not actually disappear so you may have to do this several times to see the main issue. With the compact and large appearance it seems to happen nearly every time however.

**Expected behavior:**
I’m not sure I really need to fill this out, but the expected behavior would be for the clock not to disappear on Hyperion’s AOD

**Screenshots:**

Additional information:
===

**Tweak list:**
This happens with only Kalm and Hyperion, there are no other tweaks interfering.

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Could you try using Hyperion 0.4.21-1? Seems like that issue was introduced with one of the later Hyperion updates.

**Comment by himynameisubik** [comment]
Should be fixed with the upcoming version of Kalm and Hyperion update.

**Comment by CoolOrbit** [comment]
> Should be fixed with the upcoming version of Kalm and Hyperion update.

Awesome. And you're right 0.4.21-1 doesn't have that issue

**Comment by himynameisubik** [comment]
Sorry for the premature celebration. Seems like there is still an issue if the view is smaller than the original lockscreen date view. Might need some more work. Will keep this open.

**Comment by himynameisubik** [comment]
Tritium is the one AOD tweak that as of now has no issues at all. Photon and Hyperion both seem to move Kalm around in a weird way. However I'm in contact with Spark to fix Hyperion atm.

**Comment by himynameisubik** [comment]
I think this issue was fixed with the latest update 2.0.5. Feel free to reopen if the problem still occurs.

**Comment by CoolOrbit** [comment]
Well it's different but not fixed lol, for me at least.

![image](https://user-images.githubusercontent.com/26469060/92308760-c7bcdc80-ef65-11ea-8ec7-81c1c0bd24b3.png)

**Comment by CoolOrbit** [comment]
That picture actually doesn't show the issue too well, it's stuffed in the top left corner and some is cut off by the notch

**Comment by himynameisubik** [comment]
0.4.21-1 of Hyperion still works for you too, right?

**Comment by CoolOrbit** [comment]
It does not actually

**Comment by CoolOrbit** [comment]
And to be clear, this is no longer really the same issue. Now it's just as if the default position of the clock is where it is in the picture I showed. There's no buggy-ness aside from that.

**Comment by himynameisubik** [comment]
As from my testing just now Hyperion 0.4.32 and Kalm 2.1.1 should work without an issue. No matter if invoked from Homescreen, App or LS.

**Comment by CoolOrbit** [comment]
Unfortunately it's still not for me, here's a video of it with all the presets. This is with all other tweaks disabled. https://imgur.com/a/qyg9Efn

**Comment by CoolOrbit** [comment]
I should probably note I am on Odyssey now, not Unc0ver. But I'd imagine that wouldn't affect this

**Comment by himynameisubik** [comment]
Which Kalm and Hyperion version did work for you?
I'm pretty much at a standstill atm and waiting on info from Spark as I don't think/see an option how to fix it myself. Sorry for the inconvenience.

**Comment by CoolOrbit** [comment]
iirc Kalm v1.3.4 was the last version to work without issue with Hyperion for me

**Comment by himynameisubik** [comment]
Sorry for the inconvenience but I'm not able to fix this issue at the moment. I suggest trying out Tritium instead of Hyperion which works fine.

**Comment by CoolOrbit** [comment]
I'm not sure when it was fixed, or by which tweak, but the latest Kalm and Hyperion seem to be working fine together so you can close this

**Comment by himynameisubik** [comment]
Thanks!
