### ISSUE TITLE
Springboard crash on lockscreen. 

### ISSUE THREAD

**Issue by diggitydogg** [himynameisubik/Kalm-support#164]
Crash report: https://pastebin.com/j28VLWpB
Tweak list: https://pastebin.com/A5NL1mM7

iPhone 11 Pro Max 13.5
unc0ver 5.2.1
Kalm 2.0.3

Crash occurred when swiping notification and tapping clear.

**Comment by himynameisubik** [comment]
Please create your issue with the provided template
