### ISSUE TITLE
kalm does not show me reminder calendar events

### ISSUE THREAD

**Issue by chiquito1961** [himynameisubik/Kalm-support#165]
General information:
===

**Kalm version:**

**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**

**Device:**

**Jailbreak:**

Bug description:
===

**Describe the bug:**

**How to reproduce:**

**Expected behavior:**

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by chiquito1961** [comment]
I have seen that if I install version 1.4.3 everything works for me but when I update to 2.0.3, calendar events and reminders no longer appear, why?

**Comment by himynameisubik** [comment]
Create an issue with the provided template.
