### ISSUE TITLE
Feature request: Move clock with lockscreen/add space for clock on today page

### ISSUE THREAD

**Issue by sephkane** [himynameisubik/Kalm-support#166]
General information:
===

**Kalm version:**
2.0.3

**Kalm preferences file:**
https://pastebin.com/NR9aiYEE

Device information:
===

**iOS version and language:**
iOS 13.5, English

**Device:**
iPhone 8 Plus

**Jailbreak:**
unc0ver 5.2.0

Bug description:
===

**Describe the bug:**
Enabling custom position from the 'more' section will make the widgets view move up the screen and cover the lockscreen clock. It removes all padding and brings the widgets up to the spotlight search bar leaving no room for the clock. The clock is still visible behind the widgets.

**How to reproduce:**

1. Enable custom position from the 'more' section.

**Expected behavior:**
...To see the lockscreen clock on the widgets page?

**Screenshots:**
https://imgur.com/a/iIS9hAT

Additional information:
===

**Tweak list:**
https://pastebin.com/4ARPTgCw

**Crashlog:**
No crashes

**Comment by imfaridhasan** [comment]
i know this bug on lastest kalm with smart positioning toggle turned off, currently like this right ?
https://imgur.com/gallery/o4qqwR8
but, we want this behavior :
https://imgur.com/gallery/TSQzvdX
i know this can be solved by installing tweak called [[nomorenctimex]] but i want this to be integrated on kalm. Hopefully fixed on next update.

**Comment by himynameisubik** [comment]
Will look into this. No Eta.

**Comment by sephkane** [comment]
> 
> 
> i know this can be solved by installing tweak called [[nomorenctimex]] but i want this to be integrated on kalm. Hopefully fixed on next update.

This is a nice workaround but I want the clock to still be on the widget view, and the widgets lower down on the page so I can see my clock.

**Comment by himynameisubik** [comment]
Use an older version for now or wait.

**Comment by himynameisubik** [comment]
It's not feasible to re-add this feature with using custom positioning since it would bring in more issues than goods. Sorry. Will not be added.
