### ISSUE TITLE
Misalignment with RTL language

### ISSUE THREAD

**Issue by MetallicAchu** [himynameisubik/Kalm-support#167]
General information:
===

**Kalm version:**
2.0.3
**Kalm preferences file:**
https://pastebin.com/ipN5Y0ac

Device information:
===

**iOS version and language:**
13.5 Hebrew
**Device:**
iPhone 11 Pro
**Jailbreak:**
unc0ver 5.2.1

Bug description:
===

**Describe the bug:**
Whenever the clock updates (a minute has passed), the clock jumps right. Video here: https://imgur.com/gallery/tYrlsOo

**How to reproduce:**
No idea :) Has been happening from the start

**Expected behavior:**
Expected the clock to stay where I told him!

**Screenshots:**
https://imgur.com/gallery/tYrlsOo

Additional information:
===

**Tweak list:**
https://pastebin.com/arEmMGC4

**Crashlog:**
No crash

**Comment by himynameisubik** [comment]
Hmm, do you have RTL language?

**Comment by MetallicAchu** [comment]
> Hmm, do you have RTL language?

Yes, Hebrew as I mentioned

**Comment by himynameisubik** [comment]
Well I don't know Hebrew so I don't know if it's RTL. Was just a question. Will look into it.

**Comment by MetallicAchu** [comment]
> Well I don't know Hebrew so I don't know if it's RTL. Was just a question. Will look into it.

Haha sorry if it came out wrong!! 
I Appreciate your response and thank you for the tweak

**Comment by himynameisubik** [comment]
Please send me your receipt of Kalm to cydia@ubikstyles.com. You have piracy repos and pirated tweaks installed.

**Comment by MetallicAchu** [comment]
Hey, I sent you my receipt. 
Which of the repos are pirated? I know for a fact that I don't have any pirated tweaks installed...

**Comment by himynameisubik** [comment]
Thanks for the receipt. Appreciate it.

Well I can see this here:
`CCModules (com.hackyouriphone.ccmodules) v1.6-3 by jailbreak365  via HackYouriPhone
HYI Repo Icons (com.hackyouriphone.iconrepo) v8.0.4 by HackYouriPhone  via HackYouriPhone
`

HackYouriPhone is a Piracy Repo.

**Comment by himynameisubik** [comment]
After looking into it and breaking my brain by using RTL language, I think I found the issue 😅 
Should be fixed with the next update.

**Comment by MetallicAchu** [comment]
> Thanks for the receipt. Appreciate it.
> 
> Well I can see this here:
> `CCModules (com.hackyouriphone.ccmodules) v1.6-3 by jailbreak365 via HackYouriPhone`
> `HYI Repo Icons (com.hackyouriphone.iconrepo) v8.0.4 by HackYouriPhone via HackYouriPhone`
> 
> HackYouriPhone is a Piracy Repo.

I had now idea! Good to know, thank you for that information!!

**Comment by himynameisubik** [comment]
Kalm 2.0.5 was released: https://www.reddit.com/r/jailbreak/comments/ilty52/update_kalm_205_more_options_and_various_fixes/g3uh3q0?utm_source=share&utm_medium=web2x&context=3
