### ISSUE TITLE
Forced respring in Kalm...

### ISSUE THREAD

**Issue by Zeus-lgtng** [himynameisubik/Kalm-support#168]
So I have noticed, and it hasn’t bothered me much to report it, but since it has been happening since the beginning, I thought that I should report it. I have noticed that when I have a notification on the lock screen or even in the Notification Center, when I use 3D force touch to open the notification and instantly close it, it doesn’t happen all the time, but it forces my phone to do a respring for whatever reason. It’s not another tweak because I have disabled all other tweaks but Kalm and it still happens, not as often, but still happens. I’m not in any rush to see a fix, I just thought that I’d pass the problem to you or the developer to get it resolved whenever possible. Thank you for your time and love the tweak!

**Comment by himynameisubik** [comment]
Please use the provided template to report an issue which also requires the Crashlog if you get a crash. Thanks
