### ISSUE TITLE
Multi Calendars Not working

### ISSUE THREAD

**Issue by tVance20** [himynameisubik/Kalm-support#17]
**Describe the bug**
Whenever enabling more than one calendar it doesn’t seem to display all of them only one and that is the native calendar. Also when enabling reminders and calendars the calendar goes away and only shows the reminder.

**How to reproduce**
1. Go to 'Setting'
2. Click on 'Kalm'
3. Scroll down to 'Up Next'
4. Enable more than one calendar or enable calendars and a reminder.

**Expected behavior**
It is expected that when I enable these things that the all display on the lock screen .

**Screenshots**
![D89DAF3C-2A03-423E-A047-5D91A2E65C24](https://user-images.githubusercontent.com/51184313/74187212-b864f300-4c11-11ea-8577-4a2dad863cbd.png)
![2A959C3C-F948-4302-82BC-D9FBF2C571DA](https://user-images.githubusercontent.com/51184313/74187221-bac74d00-4c11-11ea-9f63-3f197e0d5ec9.png)
.

**iOS Version:**
13.2.3
**Device:**
IPX
**Device language:**
English
**Tweak list:**
https://pastebin.com/KJjiv5B3

**Crashlog:**
NA

**Additional context**
No additional Text.

**Comment by himynameisubik** [comment]
Up until now - version 1.0.2 - there is only *1* event shown - the next upcoming one. In the next update 1.1.0 you can select how many events you want to display. See here: https://github.com/himynameisubik/Kalm-support/issues/3

Also duplicate.
