### ISSUE TITLE
Custom Font Crash to Safe Mode

### ISSUE THREAD

**Issue by ShippoFoxDemon** [himynameisubik/Kalm-support#170]
General information:
===

**Kalm version:** 2.0.3

**Kalm preferences file:**

https://pastebin.com/h63BJi5h

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:** 13.5 - English

**Device:** iPhone 11 Pro Max

**Jailbreak:** unc0ver

Bug description:
===

**Describe the bug:**
The bug crashes me to safe mode every time I try to select custom font (a-font, snowboard, etc.)

**How to reproduce:**

1. Go to fonts
2. Click on Custom font (a-font, snowboard, etc) and respring
3. Scroll down to there’s nothing to scroll down to it crashes to safe mode

**Expected behavior:**
I expected it to change the font

**Screenshots:**

Additional information:
===

**Tweak list:**

https://pastebin.com/X7LmcaRd

**Crashlog:**

https://pastebin.com/qu81rG7r

**Comment by himynameisubik** [comment]
What font do you use and what do you use to enable said font?

**Comment by himynameisubik** [comment]
Found the issue. Just don't select "Custom" for now and leave it on System.

**Comment by himynameisubik** [comment]
Kalm 2.0.4 was submitted to Chariz and will be available soon.
