### ISSUE TITLE
Notifications crash SpringBoard when tapping a notification stack

### ISSUE THREAD

**Issue by mattp12** [himynameisubik/Kalm-support#171]
General information:
===

Kalm version: 2.0.3

Kalm preferences file: https://pastebin.com/Ce5AHFUz
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

iOS version and language: iOS 13.5.1, English

Device: iPhone 8 Plus

Jailbreak: checkra1n

Bug description:
===

Describe the bug: When there are a lot of notifications on the lock screen, simply tapping one can crash SpringBoard.

How to reproduce: Have a lot of notifications (from different apps so you have to scroll), and tap one of the notification stacks. It seems kind of finicky, however, and doesn't always reproduce effectively.

1. Get a lot of notifications from various apps.
2. Tap one of the notification stacks

Expected behavior: For the notification to act as you would think.

Screenshots: N/A

Additional information:
===

Tweak list: https://pastebin.com/PPzygvg4
Put it on www.pastebin.com

Crashlog: https://pastebin.com/26zZPqEV
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Working on it. Sorry for the inconvenience.

**Comment by premzei** [comment]
I thought I was the only one having the issue lol. It kept showing up in cr4shed as complications for the culprit, so I removed complications and it still continued to happen which confused me. Thanks for working on a fix :)

**Comment by commendedfish** [comment]
This only started happening to me recently (I think after I updated Kalm). I too have complications tweak so kalm might be conflicting with complications. The bug is quite hit or miss, as in sometimes it will crash and sometimes it won’t.

**Comment by kfronz782** [comment]
> This only started happening to me recently (I think after I updated Kalm). I too have complications tweak so kalm might be conflicting with complications. The bug is quite hit or miss, as in sometimes it will crash and sometimes it won’t.

Its not a conflicting tweak. I have turned off all my tweaks and this still happens.

**Comment by himynameisubik** [comment]
It's not a tweak conflict. Will be fixed soon.

**Comment by himynameisubik** [comment]
Kalm 2.0.4 was submitted to Chariz and will be available soon.
