### ISSUE TITLE
Conflict: Axon

### ISSUE THREAD

**Issue by CySxL** [himynameisubik/Kalm-support#172]
General information:
===

**Kalm version:**
1.4.3
**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

https://pastebin.com/MmwHCAbQ

Device information:
===

**iOS version and language:**
13.3,  Traditional Chinese
**Device:**
iPhoneX
**Jailbreak:**
Checkra1n

Bug description:
===
Music randomly downs a little bit lower that NextUp2 can't display the whole area.

Can't reproduce and fix, only respring can temporarily fix it.

Only happens after playing media for a while randomly.

Have tried iCleanerPro to investigate which tweak caused it and found out that it is Axon from https://repo.co.kr/

Can you try something to make Kalm compatible with Axon for not letting it move music widget a little bit?

**Describe the bug:**

**How to reproduce:**

**Expected behavior:**

**Screenshots:**

Seems like it can't upload videos here, I upload them on my twitter, below are the links :

https://twitter.com/cysxl/status/1283572702498807812?s=21

https://twitter.com/cysxl/status/1283572481731620864?s=21

Hope it can fix 🥳🥳

P.s. Due to the position problem of version 2.0.0 and above still exists so I'm still staying on version 1.4.3, sorry for the inconvenience.

Hope U have a great day! :)

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
1.4.3 will not be worked on
