### ISSUE TITLE
Multiple Calendars - No Events

### ISSUE THREAD

**Issue by stubbz00** [himynameisubik/Kalm-support#173]
General information:
===

**Kalm version:**
2.0.3

**Kalm preferences file:**
https://pastebin.com/rzcNDTN0

Device information:
===
**iOS version and language:**
13.5 English
**Device:**
iPhone XS Max
**Jailbreak:**
unc0ver 5.2.1

Bug Information:
===

**Describe the bug:**
I have two outlook calendars for two separate accounts.  If I have both enabled and choose 'Same Day Only' no events show up for either calendar.  If I disable one of the calendars then the events show up for that 1 calendar that is still enabled.  Also, if I leave both calendars enabled and I turn off 'Same Day Only' then both of the calendars show upcoming events, but this includes all day events even though that option is disabled.

**How to reproduce:**

1. Go to 'Settings' under 'UP NEXT', then click on 'Calendars' and enable both calendars
2. Go back and turn on 'Same Day Only'
3. No events show up for either calendar
4. Turning off 'Same Day Only' will show events for both calendars, even 'All Day Events' even though the 'All Day Events' option is disabled.

**Expected behavior:**
Having both calendars enabled and 'Same Day Events' enabled will show both calendars same day events only.

**Screenshots:**

**Tweak list:**
Kalm
Complications

**Comment by stubbz00** [comment]
I believe I resolved this issue by taking a closer look at some events on one of my calendars.  Some of the events were showing up under all-day but were actually events that spanned multiple days and are technically not all-day events.

**Comment by himynameisubik** [comment]
Thanks for the info. Hope all works now.
