### ISSUE TITLE
Configuración 

### ISSUE THREAD

**Issue by alamdiaz-ctrl** [himynameisubik/Kalm-support#174]
General information:
No puedo ver en mi pantalla de bloqueo mis calendarios y ya reinstalé la aplicación 

**Kalm version:**

**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:** Español 

**Device:** iPhone 7 Plus 

**Jailbreak:** 13.5

Bug description:
===

**Describe the bug:**

**How to reproduce:**

**Expected behavior:**

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Please
