### ISSUE TITLE
Keeps freezing notification center

### ISSUE THREAD

**Issue by kfronz782** [himynameisubik/Kalm-support#175]
General information:
===

**Kalm version:** 2.0.3

**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:** iOS 13.5

**Device:** iPhone 11 Pro Max

**Jailbreak:** Yes

Bug description:
===

**Describe the bug:**
When pulling down notification center it freezes phone for a good minute 

**How to reproduce:**

1. Go to '...' top and pull down notification center

**Expected behavior:**
pull down immediately

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Linked with #171
