### ISSUE TITLE
Device respring after using faceID (randomly)

### ISSUE THREAD

**Issue by langkhack18** [himynameisubik/Kalm-support#176]
General information:
===

**Kalm version:** 
2.0.3
**Kalm preferences file:**

https://pastebin.com/MGb2g2fH

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:** 13.5 English

**Device:**
iPhone 11 128GB
**Jailbreak:**
uncover 5.2.1

Bug description:
===
Device respring after using face ID 
**Describe the bug:**
It happens when I use my face id (face id was recognized) then I swipe up cause the device to respring. Cr4shed identified it was caused by Kalm with ẽc_bad_excess( sigsegv) memory leaked??
**How to reproduce:**
1. Wake up device
2. Recognized face id
3. Swipe up
4. Springboard respring

**Expected behavior:**
Springboard respring

**Screenshots:**

Additional information:
===
I can’t really tell when this would occur exactly, I guess you can see the crash log to know what happened
**Tweak list:**

https://pastebin.com/QH4RCx5g

**Crashlog:**
https://pastebin.com/Rrd9kfk7

**Comment by himynameisubik** [comment]
Linked with #171
