### ISSUE TITLE
Kalm and Avrora conflict and crash SpringBoard to safe mode when viewing battery section in Settings

### ISSUE THREAD

**Issue by mattp12** [himynameisubik/Kalm-support#177]
General information:
===

Kalm version: 2.0.3

Kalm preferences file: https://pastebin.com/DX84SQ32
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

iOS version and language: iOS 13.5.1, English

Device: iPhone 8 Plus

Jailbreak: checkra1n

Bug description:
===

Describe the bug: When having Kalm and Avrora (by @Litteeen) both enabled, and in Avrora setting any app to change their name to the weather, SpringBoard crashes to safe mode upon opening Settings, navigating to the battery section, and letting it load. No crash occurs if either only Kalm or Avrora are enabled. I am thinking it has to do with the way weather is fetched for both of them, but I have no idea why the battery page of all things would cause a crash.

How to reproduce: Install Avrora from https://repo.litten.love, select an app for weather, and install Kalm. Go into the battery section of Settings, and let the page load. SpringBoard proceeds to crash.

I was unsure of who to report this bug to, but seeing as the Avrora page doesn't appear to have issue creating enabled, I figured that here is good.

Steps to reproduce the behavior: Above

Expected behavior: For the page to load correctly.

Screenshots: N/A

Additional information:
===

Tweak list: https://pastebin.com/6vCLDtPa
Put it on www.pastebin.com

Crashlog: https://pastebin.com/YfgcSH0N
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Springboard does not crash for me with both installed, but if Avrora is installed Batteries Section does not load (Kalm installed or not). Please contact the dev of Avrora.
