### ISSUE TITLE
Kalm interface shows behind notifications after scrolling down

### ISSUE THREAD

**Issue by riverdogg** [himynameisubik/Kalm-support#178]
General information:
===

**Kalm version:**
2.0.3

**Kalm preferences file:**
https://pastebin.com/nwvynJXD

Device information:
===

**iOS version and language:** 13.6 English

**Device:**
iPhone X

**Jailbreak:**
Checkra1n

Bug description:
===

**Describe the bug:**
The Kalm interface appears after scrolling down to view music controls/notifications. It appears behind the music controls/notifications. It only appears after scrolling down all the way. 

I turned off all other tweaks using iCleaner Pro and it still *sort of* happened. The Kalm interface flashed momentarily after scrolling all the way down, but went away. 

EDIT: here’s the issue in action — 

![](https://media2.giphy.com/media/XZNkCUxEdD0Vbk31t5/giphy.gif?cid=4d1e4f29a7a9778f964e18518570d668aef4c6de3b578637&rid=giphy.gif)

**How to reproduce:**

1. On lock screen
2. Scroll down to see music player/notifications
3. Scroll down as far as possible

**Expected behavior:**
The Kalm interface should scroll up and allow the music controls/notifications to be seen clearly.

**Screenshots:**
![E96AD35D-E3D8-4D58-8416-EC0496767704](https://user-images.githubusercontent.com/68792580/88467083-e9677600-ce87-11ea-8022-7bdc1657d035.png)

**Comment by riverdogg** [comment]
Forgot to mention that after I turned off all the tweaks, I turned on XenHTML_loader.dylib and the issue occurred again.

**Comment by himynameisubik** [comment]
I can't reproduce this issue. Might be a conflict with some setting in Xen?

**Comment by riverdogg** [comment]
I updated to version 2.0.4 yesterday. I don’t know if you specifically addressed this issue, but it’s solved. Thanks.

**Comment by himynameisubik** [comment]
Sweet, thanks. Probably a two in one with the general notification issue for some users.

**Comment by riverdogg** [comment]
Also, thanks for this great tweak. It’s the reason I jailbroke my phone in the first place.

________________________________
