### ISSUE TITLE
Sliding too far up on the lock screen when the media player is shown or when there are notifications makes the player/notifications jump to the top

### ISSUE THREAD

**Issue by mattp12** [himynameisubik/Kalm-support#179]
General information:
===

Kalm version: 2.0.3

Kalm preferences file: https://pastebin.com/r2yHkg09
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

iOS version and language: iOS 13.5.1, English

Device: iPhone 8 Plus

Jailbreak: checkra1n

Bug description:
===

Describe the bug: When the media player is showing on the lock screen or when you get a notification, swiping too far up causes the player/notification to jump to the top.

How to reproduce:

1. Start playing music and/or receive a notification.
2. Open the coversheet or lock your screen.
3. Slide up on the screen until bug occurs.

Expected behavior: For the media player/notifications to instead go back to the original position.

Screenshots: No screenshots, but video: https://m.imgur.com/a/KCvOtPu

Only Kalm and TouchFlow (to show touches) are enabled in the video.

Additional information:
===

Tweak list: https://pastebin.com/kgztze5u
Put it on www.pastebin.com

Crashlog: N/A
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
This is happening automatically since there is "notification content" visible. While in some cases it is not perfect, it is needed to allow the user to scroll further down if the Kalm view is larger and there are more notifications (or widgets) visible.

Sorry for the inconvenience.
