### ISSUE TITLE
Lockscreen Music Player Lowered

### ISSUE THREAD

**Issue by bl00dweak** [himynameisubik/Kalm-support#180]
General information:
===

**Kalm version: 2.0.4

Device information:
===

**iOS version and language: 13.4 English

**Device: iPhone 11 pro

**Jailbreak: unc0ver

Bug description:
===

**Describe the bug:**
When updating Kalm to the newer version 2.0.4 the music player on the lock screen is lowered and not centered. I verifies with other tweaks by removing any lock screen ones and found the culprit to be Kalm. I removed the tweak and the preference files through iCleaner pro and the full screen music player was back to working like normal, upon reinstalling the tweak it went right back to the similar view. Also, another fix was to downgrade the tweak to 2.0.3 and it worked as earlier stated.

**How to reproduce:**

1. Go to 'Install newest version of Kalm'
2. Click on 'Any music Spotify or Apple music and play a song'
3. Lock the screen by pressing power button
4. See error that music player is lowered and not taking up the whole screen. 

**Expected behavior:**
To work normally and have the music player full screen, and when receiving notifications they display below the music player.

**Screenshots:**
![Lockscreen](https://user-images.githubusercontent.com/68878015/88602727-52461e00-d041-11ea-8c94-348fc4a3db56.png)

**Comment by CySxL** [comment]
Wow ur settings are so similar with mine :)
![70D77DC5-D651-4873-9E23-71C2011CA8F5](https://user-images.githubusercontent.com/15531137/88616440-bced6d00-d0c6-11ea-8cdc-cdfba9c9ed5f.png)

**Comment by himynameisubik** [comment]
Will be fixed in 2.0.5.
