### ISSUE TITLE
2.0.4 sends my phone into a respring loop. 13.5 iPhone 11 Pro max 

### ISSUE THREAD

**Issue by lakers9339** [himynameisubik/Kalm-support#181]
General information:
===

**Kalm version:**

**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**

**Device:**

**Jailbreak:**

Bug description:
===

**Describe the bug:**

**How to reproduce:**

**Expected behavior:**

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Please create the issue with the needed information
