### ISSUE TITLE
12 hour am pm glitch

### ISSUE THREAD

**Issue by albertoh83** [himynameisubik/Kalm-support#183]
General information: 12 hour am pm keeps showing and disappearIng all the time 
===

**Kalm version: latest

**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information: iphone 11 pro max 
===

**iOS version and language: 13.3 english 

**Device:**

**Jailbreak: latest uncover 

Bug description: 12 hour am pm keeps showing and disappearIng all the time 
===

**Describe the bug:**

**How to reproduce:**

**Expected behavior:**

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Add the needed information to the issue.
(Tweak list, Kalm version/preferences, etc.)

**Comment by albertoh83** [comment]
ubik i know that u need all this info but is too much. the only issue is that am pm appear and disappear that all

**Comment by himynameisubik** [comment]
Kalm has a ton of settings and if you can't tell me yours and your tweaks etc, I won't be able to fix it or look into it.
