### ISSUE TITLE
"Nandi" weather (when "Always" is set)

### ISSUE THREAD

**Issue by EyalRotem** [himynameisubik/Kalm-support#184]
General information:
===

**Kalm version:**
2.0.4

**Kalm preferences file:**
https://pastebin.com/DfeSsm2T

Device information:
===

**iOS version and language:**
13.5 English (and Hebrew keyboard)

**Device:**
iPhone X 

**Jailbreak:**
Unc0ver 5.3.1

Bug description:
===

**Describe the bug:**
When setting the the weather to be updated "always", the location of a place called Nandi (in kenya) Is shown instead of the real location (israel in my case.
Even when entering the weather app, that location is shown and than updated.

Tried all the things listed for troubleshooting, none helped.
Now I’ve set it to update every "5 minutes" and the issue is not recurring.
My location is Israel, by the way.

Something similar happened to another user in when having both Kalm and velox reloaded , he saw it in the velox tweak, but I suspect that kalm was the cause as he had that installed as well - it was posted on reddit.
https://www.reddit.com/r/jailbreak/comments/hllgt1/help_velox_reloaded_weather_widget_keeps_showing/

**How to reproduce:**

1. Set weather update to "always"
2. Respring 
3. Wait for X minutes
4. See weather for Nandi on lockscreen

**Expected behavior:**
The weather will be shown for Nandi, instead of current real location. After entering the weather app- the location will update

**Screenshots:**
None

Additional information:
===

**Tweak list:**
https://pastebin.com/uh6d6164

**Crashlog:**
None

**Comment by himynameisubik** [comment]
Is the Kenya one shown in the Weather app aswell?

**Comment by EyalRotem** [comment]
Once I open the weather app, the location based page is showing the Nandi,Kenya info for a second or so and than updates to the actual location.

**Comment by himynameisubik** [comment]
Kalm is not adding any locations to your weather app. Did you reinstall the weather app?

**Comment by EyalRotem** [comment]
Yes, I did everything in the troubleshoot section to the tee.
Only thing that made this issue go away is that interval time (or removing kalm)

**Comment by himynameisubik** [comment]
Unfortunately if that didn't help you're out of luck, it seems like it's a strange behavior with (jailbroken?) iOS and iCloud(?). I also had my Weather app constantly resetting to Cities I had either used some time ago, or never added – without Kalm installed, on one of my devices. Removing the Cities, and restoring my device helped there. I know it's not an ideal solution but unfortunately I can't do much about it. It's an issue that seems to be recurring for other users on stock iOS as well if you google the issue of wrong Cities in the weather app.

Sorry for the inconvenience ;(
