### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ShaanyBro** [himynameisubik/Kalm-support#185]
General information:
===

**Kalm version:**
2.0.4
**Kalm preferences file:**
Put it on www.pastebin.com.
(Not needed)
- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===
**iOS version and language:**
13.5. English
**Device:**
iPhone 11
**Jailbreak:**

Unc0ver 

Bug description:
===
**Describe the bug:**

After respringing, kalm is misaligned way too low. This fixes after unlocking.

**How to reproduce:**
(Above)

Literally just respring
**Expected behavior:**
It will be misaligned right after respring.

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

Happened without any other tweaks enabled.

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Please report issues with the provided template
