### ISSUE TITLE
Events are not displayed on time

### ISSUE THREAD

**Issue by alxndrdaemon** [himynameisubik/Kalm-support#186]
General information:
===

**Kalm version:**
2.0.4

**Kalm preferences file:**
https://pastebin.com/uwHxbXed

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
iOS 13.5 - Spanish

**Device:**
iPhone Xs Max

**Jailbreak:**
uncover 5.3.1

Bug description:
===

**Describe the bug:**
If I have several events, they are not shown in the schedule correctly. For example, it is 1:00 am if I have an event close to 9:00 am (without duration) another at 10:00 am (duration 2 hours) another at 12:00 pm (1 hour duration), another at 9:00 pm (no duration) another at 9:00 (duration 1 hour) the events that I have marked in the next 12H appear instead of the event next to the hour

**How to reproduce:**

**Expected behavior:**
That the next event will be shown until its duration ends and the next event according to the time while the day passes instead of the event that I will have marked as the maximum time that they will appear

**Screenshots:**

https://i.imgur.com/EqvEqfU.jpg
https://i.imgur.com/zmEcUHU.png

Additional information:
===

**Tweak list:**
https://pastebin.com/q4RM6xxA

**Crashlog:**
NA

**Comment by himynameisubik** [comment]
Not sure what the issue is, might be a configuration on your side. Works fine here: 
![Bildschirmfoto 2020-08-07 um 09 42 40](https://user-images.githubusercontent.com/322449/89621916-73eda380-d892-11ea-96bf-7913f2b4d8c0.png)

**Comment by alxndrdaemon** [comment]
Thanks for reply. If you select just 1 event. And look at the time, if you can see, it’s 3:36 am and the event that is showed is the last.

![A8D13D28-1025-4710-8AA1-3294296BAAD6](https://user-images.githubusercontent.com/66810492/89637738-87334b80-d85f-11ea-8847-d020544d968d.png)

![60D48841-846D-4898-B414-D5C5E32BF689](https://user-images.githubusercontent.com/66810492/89637731-83072e00-d85f-11ea-84c0-a559e03938ba.png)

**Comment by himynameisubik** [comment]
Weird, I'll check it out.

**Comment by alxndrdaemon** [comment]
I don't know why, but for example tomorrow 12h before shows the event correctly, but during the night i don't know what happen that always that i get up and check my lockscreen shows the last. (if this is helpful for you)

**Comment by himynameisubik** [comment]
Seems like it's linked with 12h vs 24h mode, could you try changing your time mode to 24 hours and see if that works?

**Comment by alxndrdaemon** [comment]
Yeeeeeah!! It works, is there would be to keep 12H!?

**Comment by himynameisubik** [comment]
Yeah, I'm working on that, just wanted to make sure it's that. :)

**Comment by alxndrdaemon** [comment]
Really appreciate your answer, time and effort to your work! I'll be waiting for the update!! Once again thanks

**Comment by himynameisubik** [comment]
Kalm 2.0.5 was released: https://www.reddit.com/r/jailbreak/comments/ilty52/update_kalm_205_more_options_and_various_fixes/g3uh3q0?utm_source=share&utm_medium=web2x&context=3

**Comment by alxndrdaemon** [comment]
> Kalm 2.0.5 was released: https://www.reddit.com/r/jailbreak/comments/ilty52/update_kalm_205_more_options_and_various_fixes/g3uh3q0?utm_source=share&utm_medium=web2x&context=3

Thanks!
