### ISSUE TITLE
Bugged out Kalm lockscreen iPad only

### ISSUE THREAD

**Issue by Macley-Kun** [himynameisubik/Kalm-support#188]
General information:
===

**Kalm version:**

**Kalm preferences file:**
https://pastebin.com/DT5uLzG1

Device information:
===

13.5 Dutch/Netherlands

Ipad 6 wifi

Unc0ver

Bug description:
===

**Describe the bug:**
Alligment of Kalm goes all over the place in the lockscreen, with and withoud tweaks enabeld.
Can be made worse when enabling the dnd icon.

**How to reproduce:**

1. Have latest version installed
2. Go to your lockscreen, and see how things bug and go all over the lockscreen

**Expected behavior:**
See last screenshot, this is how it's surely is meant to be displayed

**Screenshots:**
![IMG_0205](https://user-images.githubusercontent.com/26381427/89582381-d5812400-d838-11ea-9a19-0c0a71e64387.PNG)
![IMG_0206](https://user-images.githubusercontent.com/26381427/89582391-d914ab00-d838-11ea-9c0c-cb9e78d9cd55.jpg)
![IMG_0208](https://user-images.githubusercontent.com/26381427/89582395-dade6e80-d838-11ea-8446-8947fc29da6c.jpg)

Additional information:
===

**Tweak list:**
Only have kalm installed, made sure that everything else is disabeld and even deleted

**Crashlog:**
No crashlog, just strange behavior since last update

**Comment by Macley-Kun** [comment]
My smart ass brain forgot to also show how bugged it was on landscape, my bad i added additional pics here:

![IMG_0209](https://user-images.githubusercontent.com/26381427/89582883-a4edba00-d839-11ea-800a-66a901c0d149.PNG)
![IMG_0211](https://user-images.githubusercontent.com/26381427/89582885-a7501400-d839-11ea-9d6e-98f44cf4faa8.jpg)

It only happend with the recent update afaik

**Comment by himynameisubik** [comment]
Kalm Version?

**Comment by Macley-Kun** [comment]
2.0.4, most recent

Met vriendelijke groet,

Wesley de Vree
________________________________
Van: ubik <notifications@github.com>
Verzonden: Friday, August 7, 2020 9:33:16 AM
Aan: himynameisubik/Kalm-support <Kalm-support@noreply.github.com>
CC: Macley <wesley.de.vree@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [himynameisubik/Kalm-support] Bugged out Kalm lockscreen iPad only (#188)


Kalm Version?

**Comment by himynameisubik** [comment]
Can you try downgrading to an earlier version? 2.0.2/3?

**Comment by Macley-Kun** [comment]
Yup, older versions work perfect with no weird bugs!

Met vriendelijke groet,

Wesley de Vree
________________________________
Van: ubik <notifications@github.com>
Verzonden: Friday, August 7, 2020 9:44:49 AM
Aan: himynameisubik/Kalm-support <Kalm-support@noreply.github.com>
CC: Macley <wesley.de.vree@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [himynameisubik/Kalm-support] Bugged out Kalm lockscreen iPad only (#188)


Can you try downgrading to an earlier version? 2.0.2/3?

**Comment by himynameisubik** [comment]
All right, should be fixed in the next update (2.0.5)

**Comment by Macley-Kun** [comment]
Thanks dude! Your extremely fast!

There's however, another bug that i have to report.

For some reason, when kalm is loaded, and only on an iPad.

When navigating to the background section in settings, when you chooce a picture to change your background (clicking on one of the two pictures, or when clicking on new background, and then selecting one) it will freeze and then respring the device.

The point where it all goes wrong is when the user get's presented with the new window to move their wallpaper around.

After some testing, i found it was kalm, and because i used vartaman in the past, i rootfs to be sure. Sadly even with a clean start, i still got the same result only having kalm installed.

This behavior, only shows on iPad, and not on iPhone for some reason.

Would you want me to make a new issue for this new bug?

**Comment by himynameisubik** [comment]
What's the crashlog for that?

**Comment by Macley-Kun** [comment]
[JetsamEvent-2020-08-07-155530.txt](https://github.com/himynameisubik/Kalm-support/files/5041804/JetsamEvent-2020-08-07-155530.txt)
Is this what you need?

**Comment by himynameisubik** [comment]
Install Cr4shed and try reproducing the crash. It will create a crashlog.

**Comment by Macley-Kun** [comment]
Trying to do this, but it seems that the tweaks aren’t correctly hooked in right?
Cr4shed crashes instantly and dra1n doesn’t show any data of battery or other stuff.

I did do a rootfs today, not sure what to do next. Will have to try again and hopefully I can get ya those logs

Will take a bit longer, sorry for the inconvenience

Met vriendelijke groet,

Wesley de Vree
________________________________
Van: ubik <notifications@github.com>
Verzonden: Friday, August 7, 2020 4:53:18 PM
Aan: himynameisubik/Kalm-support <Kalm-support@noreply.github.com>
CC: Macley <wesley.de.vree@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [himynameisubik/Kalm-support] Bugged out Kalm lockscreen iPad only (#188)


Install Cr4shed and try reproducing the crash. It will create a crashlog.

**Comment by Macley-Kun** [comment]
I just managed to get cr4shed and also crashreporter back up, but they sadly don’t register the crash sadly.

Is there anything else I can do? Ya prefer a recording of what exactly happens?

Met vriendelijke groet,

Wesley de Vree
________________________________
Van: Wesley de Vree <wesley.de.vree@gmail.com>
Verzonden: Friday, August 7, 2020 5:29:45 PM
Aan: himynameisubik/Kalm-support <reply@reply.github.com>; himynameisubik/Kalm-support <Kalm-support@noreply.github.com>
CC: Author <author@noreply.github.com>
Onderwerp: Re: [himynameisubik/Kalm-support] Bugged out Kalm lockscreen iPad only (#188)

Trying to do this, but it seems that the tweaks aren’t correctly hooked in right?
Cr4shed crashes instantly and dra1n doesn’t show any data of battery or other stuff.

I did do a rootfs today, not sure what to do next. Will have to try again and hopefully I can get ya those logs

Will take a bit longer, sorry for the inconvenience

Met vriendelijke groet,

Wesley de Vree
________________________________
Van: ubik <notifications@github.com>
Verzonden: Friday, August 7, 2020 4:53:18 PM
Aan: himynameisubik/Kalm-support <Kalm-support@noreply.github.com>
CC: Macley <wesley.de.vree@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [himynameisubik/Kalm-support] Bugged out Kalm lockscreen iPad only (#188)


Install Cr4shed and try reproducing the crash. It will create a crashlog.

**Comment by himynameisubik** [comment]
That's weird, that sounds like a bigger issue tbh if other tweaks are also crashing?

**Comment by Macley-Kun** [comment]
None are crashing, it’s only the background stuff in combination with kalm weirdly enough.

Normally I only report to a dev when I’m certain it’s related to their tweak, and makes a little sense ik my eyes

It might be related to this bug aswell, maybe it’s beter to wait for the update and then re-check

Mvgr

Wesley de Vree
________________________________
Van: ubik <notifications@github.com>
Verzonden: Friday, August 7, 2020 8:52:41 PM
Aan: himynameisubik/Kalm-support <Kalm-support@noreply.github.com>
CC: Macley <wesley.de.vree@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [himynameisubik/Kalm-support] Bugged out Kalm lockscreen iPad only (#188)


That's weird, that sounds like a bigger issue tbh if other tweaks are also crashing?

**Comment by himynameisubik** [comment]
You said it crashes when setting a wallpaper only with Kalm (and Cr4shed) installed? And Cr4shed does not provide a crashlog?

**Comment by Macley-Kun** [comment]
Yup, it somehow only crashes when kalm is getting loaded (assumingly) when an image is loaded into the window that makes the user able to move the image around, and line it out.

And yes I know, but I rather wanted to submit bugs and help improve your work, then just not bothering looking further into it.

**Comment by himynameisubik** [comment]
Kalm 2.0.5 was released: https://www.reddit.com/r/jailbreak/comments/ilty52/update_kalm_205_more_options_and_various_fixes/g3uh3q0?utm_source=share&utm_medium=web2x&context=3

**Comment by Macley-Kun** [comment]
Both issues solved, kalm looks to be working perfect again, and can also change wallpaper when kalm is active on the first screen!
Thank you for your help <3
