### ISSUE TITLE
Little option

### ISSUE THREAD

**Issue by Se7Touch** [himynameisubik/Kalm-support#189]
Hello,

Please add Disable push down other items (Complications) option to Privacy Mode...

Thank you.

**Comment by himynameisubik** [comment]
What do you mean?

**Comment by Se7Touch** [comment]
I want to fix the location of the complications but when I turn on the up next privacy feature it pushes the complications down.

Is there any way to push Axon and not push complications?
![ezgif-7-a0c90f719732](https://user-images.githubusercontent.com/16725944/89758535-b90f1100-daf0-11ea-9e1c-ea7e98fd66fd.gif)

**Comment by himynameisubik** [comment]
I can't change this. Kalm needs to push down the "notification content" to make space for the up next events. Unfortunately complications is a part of that content, that's why it get's pushed down. Maybe the dev of Complications can add something to make the position "fixed".
