### ISSUE TITLE
Not compatible with ProudLock

### ISSUE THREAD

**Issue by crewming22595** [himynameisubik/Kalm-support#19]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Screenshots**

**iOS Version:** 12.1.2

**Device:** iPhone 7

**Device language:** vietnammese

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Additional context**

**Comment by himynameisubik** [comment]
Please provide me with a link to ProudLock. I can't get it to work on my iPhone 6 with 12.4.4.

**Comment by himynameisubik** [comment]
ProudLock Xr does not work on my phone unfortunately. I can't fix this issue. Maybe try LatchKey, I assume the problem is that ProudLock adds the lock glyph in a different way that I'm checking if there is a lock glyph.

**Comment by himynameisubik** [comment]
Closing this issue as no more information was provided.

**Comment by himynameisubik** [comment]
Issue was fixed by downgrading ProudLock Xr to version 1.0. Thanks!
