### ISSUE TITLE
Kalm disappears after bedtime alarm

### ISSUE THREAD

**Issue by jspence77** [himynameisubik/Kalm-support#190]
General information:
===

**Kalm version:** 2.0.4

**Kalm preferences file:**

https://pastebin.com/mmRR1V7P

Device information:
===

**iOS version and language:** 13.5 English 

**Device:** iPhone 11 Pro Max

**Jailbreak:** unc0ver 5.3.1

Bug description:
===

**Describe the bug:**
Each morning after my bedtime alarm goes off and the Good Morning screen takes over the lock screen, Kalm then disappears. 

**How to reproduce:**

1. Set a bedtime alarm
2. Wait for the alarm to go off so that the Good _____ screen shows up
3. Dismiss the screen and Kalm will have disappeared until you respring. 

**Tweaklist:**

https://pastebin.com/7Vm3Fy5B

**Comment by himynameisubik** [comment]
Tweaklist?

**Comment by jspence77** [comment]
> Tweaklist?

Just added at the bottom of the post.

**Comment by himynameisubik** [comment]
Ok that's a lot, could you try disabling other tweaks and see if the problem still persists tomorrow morning? Because I'm using bed time aswell, and if the Good morning screen shows up, Kalm hides, and if you then close the good morning screen, it fades back in.

**Comment by yaboijay2029** [comment]
I have the same issue. The only lockscreen tweak i have other than Kalm is Axon. Mines disappears about an hour after my alarm has went off and i've dismissed it. I'm just using standard alarms not the bedtime option.

**Comment by himynameisubik** [comment]
If you don't use the bed time option this issue is not linked. 
Try disabling "Auto position" if you're using a custom position @yaboijay2029

**Comment by yaboijay2029** [comment]
@himynameisubik sorry. i'm not using that option in Kalm. Any other suggestions?

**Comment by himynameisubik** [comment]
Nope, try disabling _all_ other tweaks and check if it happens again. If it does, please create a seperate issue.

**Comment by jspence77** [comment]
For some reason I can’t get the issue to happen again. I’m going to keep messing with it and see if there’s something I’m doing to dismiss the alarm that interrupts Kalm’s normal behavior.

**Comment by yaboijay2029** [comment]
@himynameisubik okay will do. I will turn off all tweaks before going to bed and will report back in the morning.

**Comment by himynameisubik** [comment]
Will close this issue until further notice from @jspence77
