### ISSUE TITLE
Kalm disappears about an hour after alarm goes off

### ISSUE THREAD

**Issue by yaboijay2029** [himynameisubik/Kalm-support#192]
General information:
===

**Kalm version:**
2.0.4

**Kalm preferences file:**
https://pastebin.com/ZgR10EEe

Device information:
===

**iOS version and language:**
iOS 13.6 English

**Device:**
iPhone 7

**Jailbreak:**
checkra1n beta 0.10.2 

Bug description:
===

**Describe the bug:**
I was told to disable my tweaks to see if this issue reproduces. I only kept Kalm enabled. The lockscreen disappeared again.

**How to reproduce:**

1. Go to 'iCleaner'
2. Turn off all tweaks except for substrate mode and preference loader
3. Set alarm to go turn or snooze
4. After about an hour the kalm lockscreen time and date disappears except for received notifications from apps

**Comment by himynameisubik** [comment]
Could you try downgrading to 2.0.3?

**Comment by yaboijay2029** [comment]
@himynameisubik sorry i somehow didn't finish my sentence haha 
edit: After about an hour the kalm lockscreen time and date disappears except for received notifications from apps
i also downgraded 2.0.3 so i will give an update in the morning

**Comment by yaboijay2029** [comment]
@himynameisubik same thing happened. i had an alarm set to 6:45 and 7...and at 8 on the dot it disappeared. What i will do is set 2 15 minute interval alarms now and see if it replicates after an hour

**Comment by yaboijay2029** [comment]
@himynameisubik so the time hasn't disappeared yet. so i believe it may pertain to whenever it hits 8am it disappears

**Comment by yaboijay2029** [comment]
@himynameisubik so I believe this may have something to do with the dnd and the good morning Splash screen. I will keep testing

**Comment by yaboijay2029** [comment]
you can close this @himynameisubik 
something with DND was causing it so I changed the time it's still working

**Comment by himynameisubik** [comment]
Oh weird, but thanks for letting me know!
