### ISSUE TITLE
Feature request: custom local of weather depiction

### ISSUE THREAD

**Issue by CySxL** [himynameisubik/Kalm-support#193]
As title, just like we now can customize time/date locale, can we choose which locale status to use for the depiction of weather like "en_US_POSIX" in time/date ?  

That'll help much to create a consistently custom english weather font :)

screenshot below:
![IMG_CCD3C5C53B19-1](https://user-images.githubusercontent.com/15531137/90103326-e3710080-dd74-11ea-8069-a1eed0b0d322.jpeg)

I'm ok with traditional chinese text can't be customized and wanna use english text instead.

Kalm 2.0.4
iPhone X, iOS13.3, Checkra1n

**Comment by himynameisubik** [comment]
Unfortunately this is not possible. Kalm uses the text & data from the stock iOS Weather Widget to provide best possible results and I can't change the language for that Widget.
