### ISSUE TITLE
When clearing a notification, Kalm disappears for a second then reappears

### ISSUE THREAD

**Issue by mattp12** [himynameisubik/Kalm-support#194]
General information:
===

Kalm version: 2.0.4

Kalm preferences file: https://pastebin.com/zu1jj6im
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

iOS version and language: iOS 13.6.1, English

Device: iPhone 8 Plus

Jailbreak: checkra1n

Bug description:
===

Describe the bug: When swiping to clear a notification, everything from Kalm disappears for a second and then reappears. This happens even if Kalm is the only tweak enabled.

How to reproduce:

1. Receive a notification
2. Slide to the left to clear it

Expected behavior: For Kalm to stay and not disappear.

Screenshots: No screenshot, but a video: https://imgur.com/a/T2OP4nE

Additional information:
===

Tweak list (this happens even with every other tweak disabled but here it is anyway): https://pastebin.com/zNbjNTmL
Put it on www.pastebin.com

Crashlog: N/A
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Disable auto positioning.

**Comment by mattp12** [comment]
Thanks, that solves it
