### ISSUE TITLE
up next glitch

### ISSUE THREAD

**Issue by codster2** [himynameisubik/Kalm-support#196]
General information:
===

**Kalm version:** 2.0.4

**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:** 13.4.1 English

**Device:** iPhone XR

**Jailbreak:** unc0ver 

Bug description:
===

**Describe the bug:** anytime i try and use the up next option it slows down my phone when i try to turn it off, turn it on, or view my lock screen.

**How to reproduce:** activate up next

1. Go to 'Kalm'
2. Click on 'Kalm Tweak'
3. Scroll down to 'Up Next '
4. Activate 'Up Next'
5. See error

**Expected behavior:**
Within 5 minutes it takes 5 seconds to turn my phone and off and or view the lock screen

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Please provide the missing information.
