### ISSUE TITLE
Weird cut off of Time

### ISSUE THREAD

**Issue by CySxL** [himynameisubik/Kalm-support#198]
General information:
===

**Kalm version:**
2.0.4

**Kalm preferences file:**

https://pastebin.com/snpxcxTX

Device information:
===

**iOS version and language:**
iOS13.3, Traditional Chinese
**Device:**
iPhoneX
**Jailbreak:**
Checkra1n

Bug description:
==

The font of time is randomly cut off.  (the leftest or rightest number)

**How to reproduce:**
Randomly.

Or change fonts to italics style. Might happen sometimes.

**Screenshots:**

HelveticaNeue-BoldItalic (the 8)
![11C14484-38BC-44CA-ACE7-DC63FFCB720E](https://user-images.githubusercontent.com/15531137/90704149-52dd7780-e2c2-11ea-91ed-af023cec5ecb.png)

Avenir-BlackOblique (the minute 8)
![AB3D2438-933E-42A0-9582-0A96AAFDE255](https://user-images.githubusercontent.com/15531137/90704207-730d3680-e2c2-11ea-9219-d4dabec349d0.png)

Arial-BoldItalicMT (the minute 8)
![6EAC7A7C-5F9E-45F2-8856-7173271FC474](https://user-images.githubusercontent.com/15531137/90704253-933cf580-e2c2-11ea-87df-7c027e842f5f.png)

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by CySxL** [comment]
Forget to circle the part of cutting off but I guess you can tell them tho.

**Comment by himynameisubik** [comment]
Related to custom fonts and center alignment. Will not be investigated actively. Might be fixed with the 2.0.5 update.
