### ISSUE TITLE
Feature Request : Change statusbar items color

### ISSUE THREAD

**Issue by CySxL** [himynameisubik/Kalm-support#199]
Hi 👋

Is there any chance to color those lockscreen statusbar items to sync with Kalm's color ? Just like Fabric 2 or ColorFlow 5 does. 

Because those white icons/indicators are really not harmony with beautiful Kalm 🥺🥺

[](url)

**Comment by CySxL** [comment]
![2F13B976-12C5-4E75-9CD5-CC18090E288D](https://user-images.githubusercontent.com/15531137/90711166-904a0100-e2d2-11ea-896e-312b8f93bd41.png)


and below is what Fabric 2 does :
![9C172096-A50F-4CF2-8FFD-81700CFC057C](https://user-images.githubusercontent.com/15531137/90711213-b7083780-e2d2-11ea-8c01-654e8e17fd19.jpeg)

**Comment by himynameisubik** [comment]
Feature requests are on hold atm.

**Comment by CySxL** [comment]
Wow! Glad to know that :)

**Comment by himynameisubik** [comment]
Closing this as duplicate of #52

**Comment by CySxL** [comment]
Hope it come true ! :)
