### ISSUE TITLE
Font Weight not applying to Weather condition label 

### ISSUE THREAD

**Issue by p2kdev** [himynameisubik/Kalm-support#2]
**Describe the bug**
The temperature shows the correct font weight, but the weather condition label stays thin

**How to reproduce**

Pre-Requisite : 
Enable Weather condition from Settings -> Kalm -> Weather -> Show Condition

1. Go to Settings -> Kalm -> Appearance -> Font Weights
2. Enable Weather & set the desired font Weight

**Expected behavior**
The selected font weight should apply to the weather condition/City Label

**Screenshots**
![File Feb 03, 10 12 02 AM](https://user-images.githubusercontent.com/51972743/73670407-c98c8d80-466e-11ea-97bb-7309e5e860af.jpeg)

![File Feb 03, 10 12 31 AM](https://user-images.githubusercontent.com/51972743/73670418-ce514180-466e-11ea-87b1-ae10910a87de.jpeg)

**iOS Version:** 13.3.1

**Device:** iPhone X

**Comment by himynameisubik** [comment]
Thanks for submitting that issue so clearly, will be fixed with the next update!

**Comment by himynameisubik** [comment]
Version 1.0.2 was submitted to Packix fixing this issue. Thanks for your report!
