### ISSUE TITLE
Feature request: Privacy Option

### ISSUE THREAD

**Issue by tommoctrl** [himynameisubik/Kalm-support#20]
Feature Request: an option to hide the Up Next content if the device is not unlocked

**Comment by himynameisubik** [comment]
Really good idea! Will look into this. No ETA yet.

**Comment by himynameisubik** [comment]
Hey pssst @tommoctrl 
https://twitter.com/himynameisubik/status/1247637181763551234?s=21

**Comment by himynameisubik** [comment]
Added as of 1.4.0 :)

**Comment by tommoctrl** [comment]
Yay :D


Da: ubik
Inviato: giovedì 4 giugno 2020 09:22
A: himynameisubik/Kalm-support
Cc: tommoctrl; Mention
Oggetto: Re: [himynameisubik/Kalm-support] Feature request: Privacy Option(#20)

Added as of 1.4.0 :)
