### ISSUE TITLE
Hi there.

### ISSUE THREAD

**Issue by Jenkomac** [himynameisubik/Kalm-support#201]
I Love your tweak. But the last update 2.0.4 has a problem when I'm changing my wallpaper. I got other tweak called Quart. Using both my iPhone stays "Black Screen" when I'm try to change my Wallpaper. Now get back to 2.0.3 it is working properly with the tweak "Quart"

**Comment by Jenkomac** [comment]
I Love your tweak. But the last update 2.0.4 has a problem when I'm changing my wallpaper. I got other tweak called Quart. Using both my iPhone stays "Black Screen" when I'm try to change my Wallpaper. Now get back to 2.0.3 it is working properly with the tweak "Quart"

**Comment by himynameisubik** [comment]
Report issues with the template please.
