### ISSUE TITLE
Kalm doesn’t work anymore

### ISSUE THREAD

**Issue by real-mizuya** [himynameisubik/Kalm-support#203]
General information:
===

**Kalm version:** 2.05

**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:** 13.5 German 

**Device:** iPhones SE2

**Jailbreak:** Unc0ver 

Bug description:
===

**Describe the bug:**
I updated Kalm and now it doesn't work. It says either Apple calendar or reminders app are not installed but enabled in upcoming section. Reminders is not installed and also not enabled in settings of upcoming. ![image](https://user-images.githubusercontent.com/47298686/92238691-0432fe80-eeba-11ea-9492-2b9470c97a78.jpeg)

**How to reproduce:**

**Expected behavior:**

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
This is a fail-safe that has to be in place unfortunately – I'm still looking how to make it better, but for now you _need_ to have Calendars and Reminders installed (as the popup says).
