### ISSUE TITLE
Springboard crash

### ISSUE THREAD

**Issue by asd7360162** [himynameisubik/Kalm-support#204]
General information:
===

**Kalm version:**2.0.5

**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
13.5 Chinese
**Device:**
XS
**Jailbreak:**
unc0ver

Bug description:
===

**Describe the bug:**

**How to reproduce:**

**Expected behavior:**

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
https://pastebin.com/YDcFSFNu

**Comment by himynameisubik** [comment]
Please fill out the required information and reopen the issue
