### ISSUE TITLE
Springboard crash when clicking on notification banners

### ISSUE THREAD

**Issue by luv-letter117** [himynameisubik/Kalm-support#205]
General information:
===

**Kalm version:**
2.0.5
**Kalm preferences file:**
https://pastebin.com/gKwnG8jp

Device information:
===

**iOS version and language:**
13.5 Chinese
**Device:**
XS
**Jailbreak:**
unc0ver

Bug description:
===

**Describe the bug:**
When I press banners on the lock screen to open app, my springboard crashed

**How to reproduce:**

1. press power button to wake up my device
2. press bannners on lock screen to open app

**Expected behavior:**
stop crash

**Screenshots:**
no screenshot

Additional information:
===

**Tweak list:**

https://pastebin.com/35n4uV07

**Crashlog:**
https://pastebin.com/YDcFSFNu

**Comment by himynameisubik** [comment]
Tweak list?

**Comment by himynameisubik** [comment]
2.0.4 does not have this issue for you?

**Comment by luv-letter117** [comment]
> 2.0.4 does not have this issue for you?

yes sir

**Comment by himynameisubik** [comment]
Could you provide proof of purchase to cydia@ubikstyl.es including your Chariz Email Adress?
You're using CyDown which is mostly used for Piracy.

Closing until provided proof of purchase.

**Comment by luv-letter117** [comment]
> Could you provide proof of purchase to [cydia@ubikstyl.es](mailto:cydia@ubikstyl.es) including your Chariz Email Adress?
> You're using CyDown which is mostly used for Piracy.
> 
> Closing until provided proof of purchase.

OK, sent.

**Comment by himynameisubik** [comment]
Thanks! Will check it out.

**Comment by himynameisubik** [comment]
Will be fixed with the next upcoming version.

**Comment by luv-letter117** [comment]
> Will be fixed with the next upcoming version.

Thanks a lot.

**Comment by himynameisubik** [comment]
2.1.1 is released
