### ISSUE TITLE
Time and date misalignment after *really* fast swipe up 

### ISSUE THREAD

**Issue by alanyzr** [himynameisubik/Kalm-support#207]
![tweak list](https://user-images.githubusercontent.com/71020313/92726773-b843f600-f3a0-11ea-840c-1812f6901ec6.PNG)
[archive.zip](https://github.com/himynameisubik/Kalm-support/files/5201432/archive.zip)

![FE8A8C36-A407-47A6-AEF0-E77FB9C94B21](https://user-images.githubusercontent.com/71020313/92605935-eebc3b00-f2e4-11ea-970e-ed8a3678ea0c.jpeg)
General information:
===
The time and date will freeze after a quick swipe up to see the hided notification banners
**Kalm version:**
2.1.1
**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
13.5 English
**Device:**
iPhone 11 Pro Max
**Jailbreak:**
unc0ver 5.3.1

Bug description:
===

**Describe the bug:**

The time and date will freeze after a quick swipe up to see the hided notification banners

**How to reproduce:**

1. First of all and the most crucial part:
leave 1-2 banners hided in the lock screen 
(which normally the banner came minuets before. the point is the banner must be hide in NC)
2. Then you swipe up from the middle of the screen to let those 1-2 hided banners appear
in a very quick speed(This is very important: you must do it very quickly)

**Expected behavior:**
The time and date will freeze and a large gap between those elements appear which you have to swipe up the screen once again to let them reposition.

**Screenshots:**
![CE22B51D-D833-4603-8831-FF0987BB247C](https://user-images.githubusercontent.com/71020313/92606197-43f84c80-f2e5-11ea-8420-5ab5507e202f.png)

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Please add your Kalm prefs and Tweaklist

**Comment by alanyzr** [comment]
I uploaded those files named archive.zip

**Comment by alanyzr** [comment]
> Please add your Kalm prefs and Tweaklist. Will be reopened after providing that info.

I uploaded those files named archive.zip

**Comment by himynameisubik** [comment]
All right, I'll check it out. Could you please upload the tweak list like this: Tweak list: With Zebra -> Packages -> Top left (Box with arrow) export it, or use Flame with Cydia. I don't know about Sileo. And copy paste the contents on pastebin.com

Also, did you try if this problem is also happening with _all_ other tweaks disabled? I can't seem to replicate that behavior, but maybe I'm to slow.

**Comment by himynameisubik** [comment]
Should be fixed as of 2.2.0.
https://twitter.com/HiMyNameIsUbik/status/1309136304047882241
