### ISSUE TITLE
Axon + Kalm (Up Next) slowing down unlock when notifications are present

### ISSUE THREAD

**Issue by codster2** [himynameisubik/Kalm-support#208]
General information:
===

**Kalm version:**
2.1.1
**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===
**iOS version and language:**
iOS 13.4.1 English
**Device:**
iPhone XR

**Jailbreak:**
unc0ver 5.0.1

Bug description:
===

**Describe the bug:**
Anytime I go to use calm's up next feature with axon's notification grouping kalm will 80% of the time slow down my phone when it's waking up out of sleep mode.
**How to reproduce:**
just turn on up next with reminders and calendars and turn on axon and within 20-30 minutes it will slow down your phone. (yes i've tried iCleaner)

**Expected behavior:**
i expect it to work seamlessly and not slow down my phone when i go to look at my notifications
**Screenshots:**

(The Last 3 Tweaks are Tweak Restrictor, UnSub, and Weather Ground)
<img width="428" alt="Screen Shot 2020-09-10 at 7 39 50 AM" src="https://user-images.githubusercontent.com/66573324/92724557-d4ac4800-f338-11ea-90e5-5408ba922fb4.png">

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Please add missing information such as Kalm prefs, tweak list etc. Will reopen after that info was added.

**Comment by codster2** [comment]
> Please add missing information such as Kalm prefs, tweak list etc. Will reopen after that info was added.

should i just add screenshots/ screen recordings of my tweaks here or do i need to put them in the pastebin?

**Comment by himynameisubik** [comment]
Tweak list: With Zebra -> Packages -> Top left (Box with arrow) export it, or use Flame with Cydia. I don't know about Sileo. And copy paste the contents on pastebin.com
Kalm Preferences: Use Filza to locate the file `hi.my.name.is.ubik.kalm.plist` in `/var/mobile/Library/Preferences` and copy paste the contents to pastebin.com

**Comment by himynameisubik** [comment]
Also, does this issue also happen if you disable all other tweaks besides Axon and Kalm?

**Comment by himynameisubik** [comment]
Also also, did you have this issue before updating to 2.1.1?

**Comment by himynameisubik** [comment]
Sorry misclicked closing this time..

**Comment by himynameisubik** [comment]
Some more stuff, did you try using Axon Reborn? I'm using it now since you reported this issue and can't seem to replicate your _slowing down_ issue.

**Comment by codster2** [comment]
> Some more stuff, did you try using Axon Reborn? I'm using it now since you reported this issue and can't seem to replicate your _slowing down_ issue.

I have tried using axon reborn, im not sure as to why its happening but its been happening for a while, i just havent really used up next with axon but i need it to take my medicine, so i turned it on, it doesn't happen every single time but like 70% of the time my phone feels like it lags and ends up activating siri if i use the power button

**Comment by himynameisubik** [comment]
Why are you not using Axon Reborn as it is the much more modern approach? Please also provide me with the Kalm settings. Might be some misconfiguration such as to many refreshes or something. I've let many notifications now idle on my phone and can't see any lag (on an iPhone 8).

**Comment by codster2** [comment]
> Why are you not using Axon Reborn as it is the much more modern approach? Don't know but that might help?
> Please also provide me with the Kalm settings. Might be some misconfiguration such as to many refreshes or something. I've let many notifications now idle on my phone and can't see any lag (on an iPhone 8).

I stopped using axon reborn because it actually lagged it more for me, but i use compact appearance, left allignment with colors enabled/custom color, times new roman font for everything, custom date format ( EE d) weather disabled, upnext enabled with the header being hid, alarms off, all day events and overdue reminders on, 1 max event, 1 max line, 1D ahead with 30 min update interval (i made it 30 because it seems like it reduced the issue slightly.

**Comment by himynameisubik** [comment]
Can you please provide the prefs file? So I can test your exact settings myself. Because as I said. I can't replicate that issue at all. 
> Kalm Preferences: Use Filza to locate the file `hi.my.name.is.ubik.kalm.plist` in `/var/mobile/Library/Preferences` and copy paste the contents to pastebin.com

Also, does it lag without Axon installed? And how many notifications are we talking about?

**Comment by codster2** [comment]
> Can you please provide the prefs file? So I can test your exact settings myself. Because as I said. I can't replicate that issue at all.
> 
> > Kalm Preferences: Use Filza to locate the file `hi.my.name.is.ubik.kalm.plist` in `/var/mobile/Library/Preferences` and copy paste the contents to pastebin.com
> 
> Also, does it lag without Axon installed? And how many notifications are we talking about?

not to many notifications, and it doesn't seem like it is lagging with axon uninstalled but same issue with grupi, and calendars just recently activated but only for holidays and birthdays. and ill get the pref file for you now.

**Comment by himynameisubik** [comment]
And without Kalm you have no lag at all?
All right, thx!

**Comment by codster2** [comment]
https://pastebin.com/6dKh1AyS

and yes without kalm theres no lag

**Comment by codster2** [comment]
so what i sent in pastebin is the list, i dont believe its the plist, im trying to get the plist open but i dont know how, its my first time doing this im sorry if im annoying

**Comment by codster2** [comment]
https://pastebin.com/66JbMk4w
100% the plist

**Comment by himynameisubik** [comment]
Long tap on the .plist -> More -> Send email and send it to cydia@ubikstyl.es that also works :)

**Comment by codster2** [comment]
just sent it over, let me know if you received it

**Comment by codster2** [comment]
and again thank you so much for your help and cooperation

**Comment by himynameisubik** [comment]
That worked. I now use your settings and have 4 notifications on Axon Reborn pending and let the phone rest for some time. Right now it does not lag at all. 

Sure thing, sorry for the inconvenience. Kinda looking for a needle in a haystack atm, no idea what could cause it for you.

**Comment by himynameisubik** [comment]
I doubt it, we'll see. Only time will tell. All you could also try is using an older version of Kalm to test if that maybe helps. Do you get a crash or does it just lag? And about "how much" lag in seconds are we talking when you unlock it? Until it turns the screen on or until it's unlocked?

**Comment by codster2** [comment]
this issue has been persistent for a few kalm versions now, and no crashing except one time yesterday but nothing since, and its about 2-5 seconds and its just when screen turns on, if i tap it takes the same amount of time but if i press the home button it takes that same amount of time but will activate siri and i have to tap or click the button to turn siri off again

**Comment by himynameisubik** [comment]
Did you try these two steps from the main support page?
1. Try (re-)installing the stock Weather, Calendar and Reminders app from Apple.
2. Try removing the Kalm preferences file hi.my.name.is.ubik.kalm.plist in /var/mobile/Library/Preferences and respring.

Only calendar & reminders app is relevant for you on 1.

**Comment by codster2** [comment]
> Did you try these two steps from the main support page?
> 
> 1. Try (re-)installing the stock Weather, Calendar and Reminders app from Apple.
> 2. Try removing the Kalm preferences file hi.my.name.is.ubik.kalm.plist in /var/mobile/Library/Preferences and respring.
> 
> Only calendar & reminders app is relevant for you on 1.

ill be honest i have not, and by remove the plist do i just delete it and respring it?

**Comment by himynameisubik** [comment]
Yes, you can just remove the file you sent me (you'll lose your settings unfortunately) and do a respring.

**Comment by codster2** [comment]
> Yes, you can just remove the file you sent me (you'll lose your settings unfortunately) and do a respring.
> 
> * But as you said in the OP you did disable all other tweaks besides Axon and Kalm?

OP?

**Comment by himynameisubik** [comment]
Original post. You said:
> just turn on up next with reminders and calendars and turn on axon and within 20-30 minutes it will slow down your phone. (yes i've tried iCleaner)

If you didn't mean, you disabled _all_ other tweaks except Kalm & Axon, please try that.

**Comment by codster2** [comment]
> Original post. You said:
> 
> > just turn on up next with reminders and calendars and turn on axon and within 20-30 minutes it will slow down your phone. (yes i've tried iCleaner)
> 
> If you didn't mean, you disabled _all_ other tweaks except Kalm & Axon, please try that.

i am trying it now, i completely forgot to attempt that, by icleaner i meant like cleaning the phone, as of right now nothing has happened

**Comment by himynameisubik** [comment]
Ah, okay. Yeah please try that. Since there could be many other tweaks that are interfering or just not work well together with certain combinations.

**Comment by codster2** [comment]
it's still happening, the delay has been reduced significantly but it's still happening, could it be the custom color option?

**Comment by himynameisubik** [comment]
What did you try now?

**Comment by codster2** [comment]
you were correct, its not custom color. I know its a lot to ask but do you think you can install the tweaks im running (if free) and see if any of them conflict with the issue im having?

**Comment by codster2** [comment]
now my kalm is starting to crash more frequently

**Comment by codster2** [comment]
also also, i believe it has to do with the time update interval, when i put it to 30 the issue still arises after a while but it's reduced significantly

**Comment by himynameisubik** [comment]
You could also try setting a higher interval or disabling calendars for example. I won't be able to install all your tweaks and test it like that. No idea why this happens to you, all I can really do is offer you a refund.

**Comment by himynameisubik** [comment]
I'm also really unsure about what kind of lag we're talking. So it's really hard to see what you're referring to. Many users use Axon & Kalm and don't have any "lag", and I installed Axon on my 2 other devices as well and can't see any lag eithery

**Comment by himynameisubik** [comment]
> now my kalm is starting to crash more frequently

Do you have a crash report? If not, install Cr4shed.

**Comment by codster2** [comment]
i might be able to get the crashed report, but also it's like a delay type effect, i even reinstalled rootfs and it's still happening, all i know for a fact is that it has to do with the update time interval to have the reminders brought up, if it's at always every single time i try to wake my phone up it'll delay and it'll take about 2 seconds to bring up my lock screen, if i push the power button once then siri will pop up because the delay is so long

**Comment by codster2** [comment]
i cant get the crashed report because it was lost when i restored rootfs

**Comment by himynameisubik** [comment]
Just keep Cr4shed installed so if it crashes again, you will get a crash report to submit. About the delay I can't help you unfortunately as I can't replicate this issue on my ```slowest```device the (old) iPhone SE.

All I can guess is that you might have very many calendar/reminder events so Kalm would need to loop through a lot which _could_ technically lead to a small amount of lag. Sorry for any inconvenience. Feel free to request a refund.

**Comment by codster2** [comment]
no need for a refund, the only thing that i can think of is attempting to screen record to show you exactly what i mean but idk how that'd work

**Comment by himynameisubik** [comment]
Closing this for now
