### ISSUE TITLE
Random Springboard crashes

### ISSUE THREAD

**Issue by NICHOLAS85** [himynameisubik/Kalm-support#209]
General information:
===

**Kalm version:**
2.1.1
**Kalm preferences file:**
https://pastebin.com/tKMgqXp4

Device information:
===

**iOS version and language:**
iOS 13.5.1, English
**Device:**
iPhone X
**Jailbreak:**
Odysseyra1n

Bug description:
===

**Describe the bug:**
At random times Springboard will crash, sometimes with a crash report and sometimes without, and Kalm seems to always be chosen as the culprit. These crashes started recently however I am unable to indicate what the last working version was.

**How to reproduce:**
Simply use the phone, visiting lock screen etc. Springboard crashes at least once a day.

**Expected behavior:**
No crashes.

**Screenshots:**

Additional information:
===

**Tweak list:**
https://pastebin.com/n0ri6zkg

**Crashlog:**
https://pastebin.com/0YCWAMY1

**Comment by himynameisubik** [comment]
When does that happen? Anything specific/particular?

**Comment by NICHOLAS85** [comment]
I don't believe there is any specific behavior that is causing this issue. My device simply resprings. I've seen it occur while on my home screen and on the lock screen just swiping around. I'll do some more testing to see if I can find a consistently reproducible crash.

**Comment by CanerKaraca23** [comment]
I'm having this issue too, it's crashed while device close. It's just random.

**Comment by CanerKaraca23** [comment]
I'm having this issue too, it's crashed while device in close. It's just random.

**Comment by himynameisubik** [comment]
> I'm having this issue too, it's crashed while device in close. It's just random.

Please provide a crash log to make sure this is the same issue.

**Comment by CanerKaraca23** [comment]
> > I'm having this issue too, it's crashed while device in close. It's just random.
> 
> Please provide a crash log to make sure this is the same issue.

https://hastebin.com/xanawatufe.sql

**Comment by himynameisubik** [comment]
This is related to something different. Please create a seperate issue after making sure you followed these steps here: https://github.com/himynameisubik/Kalm-support#general-steps-to-try-before-creating-an-issue

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23: This is related to something different. Please create a seperate issue after making sure you followed these steps here: https://github.com/himynameisubik/Kalm-support#general-steps-to-try-before-creating-an-issue

Also I don't have stock callendar and reminder but I disabled up next on kalm preferences. But kalm working now. I will create new issue.

**Comment by NICHOLAS85** [comment]
Update since last message:
Crashes occurs ~2 times a day. Have seen it occur when opening Notification Center, while device is locked/sleeping, when scrolling on the lockscreen, and sporadically. I haven't been able to reliably reproduce the issue but can provide more crash logs. In the future I am going to systematically disable tweaks to determine if it's a tweak conflict but haven't had the time to do so yet.

**Comment by himynameisubik** [comment]
Should be fixed as of 2.2.0.
https://twitter.com/HiMyNameIsUbik/status/1309136304047882241

**Comment by NICHOLAS85** [comment]
Thanks for the update! Will reopen if I run into this issue again, otherwise thanks for the fix!
