### ISSUE TITLE
Random Safe Mode

### ISSUE THREAD

**Issue by CanerKaraca23** [himynameisubik/Kalm-support#210]
General information:
===

**Kalm version:** 2.1.1

**Kalm preferences file:**

https://pastebin.com/y00JT7Mw
https://pastebin.com/ULJDux46

Device information:
===

**iOS version and language:** 12.4.8, Turkish

**Device:** iPhone 5s

**Jailbreak:** unc0ver

Bug description:
===

**Describe the bug:**
Device enters randomly to Safe Mode, springboard crashes.

**How to reproduce:**

**Steps to reproduce the behavior:** Just randomly, it's crashed while device locked in my pocket.

**Expected behavior:** Fix

**Screenshots:** -

Additional information:
===

**Tweak list:** https://pastebin.com/y5ULaQqc

**Crashlog:** https://pastebin.com/FvhMMmTJ

**Comment by himynameisubik** [comment]
Please upload your crashlogs and tweaklist to pastebin.com

**Comment by CanerKaraca23** [comment]
> Please upload your crashlogs, tweaklist and preferences file to pastebin.com

Updated.

**Comment by himynameisubik** [comment]
Should be fixed as of 2.2.0.
https://twitter.com/HiMyNameIsUbik/status/1309136304047882241
