### ISSUE TITLE
Conflict between compactor and kalm

### ISSUE THREAD

**Issue by Oliverkiller** [himynameisubik/Kalm-support#211]
General information:
===

**Kalm version: 2.2.0**

**Kalm preferences file:**
Put it on www.pastebin.com.

https://pastebin.com/fCdvq6iK

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:iOS 14 language:English**

**Device:iPhone 6s**

**Jailbreak:odessyra1n**

Bug description:
===

**Describe the bug:if compactor tweak is installed the default and compact appearance will bug in a way that make the time go inside the screen to the left **

**How to reproduce:**

**Expected behavior:**

**Screenshots:**

Additional information:
===

**Tweak list: https://pastebin.com/cmdekSV7**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Can you provide a screenshot?

**Comment by himynameisubik** [comment]
Nevermind. It's an issue with Compactor. Not Kalm.

(Disable Kalm and use Compactor, the Clock will be shifted to the left. Disable Compactor and the time will be correctly aligned again.)

**Comment by Oliverkiller** [comment]
Yeah I did it

**Comment by Oliverkiller** [comment]
Compactor is the issue
