### ISSUE TITLE
All Kalm modules take multiple seconds to appear after waking device

### ISSUE THREAD

**Issue by goob47** [himynameisubik/Kalm-support#212]
General information:
This doesn’t happen every time I wake the device, only after it has been asleep for more than 5 mins or so. None of the Kalm modules (time, weather, next up, date) appear until after I unlock the device with Face ID (no, I didn’t turn on privacy mode). The Face ID prompt itself is delayed because it seems like the Kalm modules need to load first. I messed with the calendar update timing and set it to 5 min intervals, 10 mins, but nothing changed. This has been super annoying and I’ve just resorted to disabling the tweak entirely. I don’t have any other lock screen tweaks other than the newest version of Complications.

**Kalm version:**
2.2.0
**Kalm preferences file:**
https://pastebin.com/pxKKBJXD

Device information:
===

**iOS version and language:**
13.7, English
**Device:**
iPhone X
**Jailbreak:**
Checkra1n 

Bug description:
===

**Describe the bug:**

This doesn’t happen every time I wake the device, only after it has been asleep for more than 5 mins or so. None of the Kalm modules (time, weather, next up, date) appear until after I unlock the device with Face ID (no, I didn’t turn on privacy mode). The Face ID prompt itself is delayed because it seems like the Kalm modules need to load first. I messed with the calendar update timing and set it to 5 min intervals, 10 mins, but nothing changed. This has been super annoying and I’ve just resorted to disabling the tweak entirely.

**How to reproduce:**

1. Unlock screen
2. Wait more than 2 seconds before time, date, and next up appear on the lockscreen.

**Expected behavior:**
I expected the time, date, and next up to appear almost instantly after waking the device from sleep.

Additional information:
===

I don’t have any other lock screen tweaks other than the newest version of Complications. I’ve tested with it disabled and removed entirely and this problem still occurs with Kalm.

**Comment by himynameisubik** [comment]
Can't reproduce this issue on my devices.
What's your tweak list?
