### ISSUE TITLE
Seconds support or compatibility with FastForwardTime?

### ISSUE THREAD

**Issue by ZydePunk77** [himynameisubik/Kalm-support#214]
Seems to work fine with Jellyfish, but Kalm has more options. The addition of seconds would be extremely useful for me job. So I have to use Jellyfish. Just wondering if this will ever be supported. 

Perhaps a look at HS13 beta Xen HTML json file widget for reference. I love the concept of “small seconds”. Just throwing that out there so I know to check for an update. 

Thanks for reading 
-ZydePunk77.

**Comment by himynameisubik** [comment]
FastForwardTime (or any _show seconds_ tweak) will not be directly supported. Updating the time every second puts a small load on the whole thing which would lead to an increased power consumption. You can however change the time format to show seconds, but these will only update every minute or any time you show open your lockscreen/coversheet (lock/unlock or drag down coversheet). Sorry for the inconvenience but I hope you can understand.
