### ISSUE TITLE
Crash iPhone X iOS 14.1

### ISSUE THREAD

**Issue by Mistake08** [himynameisubik/Kalm-support#215]
General information:
I got my iPhone X with jailbreak on iOS 14.1, and when my device respring after I installed Kalm it get stuck with the screen off.
===

**Kalm version:** 2.2.0

**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**

**Device:**

**Jailbreak:**

Bug description:
===

**Describe the bug:**

**How to reproduce:**

**Expected behavior:**

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Sorry for the inconvenience!

Please make sure to try these steps first: https://github.com/himynameisubik/Kalm-support#general-steps-to-try-before-creating-an-issue

And if it doesn't help create an issue with the information needed.
