### ISSUE TITLE
Charging/Battery view pop up font

### ISSUE THREAD

**Issue by blacktornadog7** [himynameisubik/Kalm-support#216]
General information:
===

Kalm version: 2.2.0

Kalm preferences file: https://pastebin.com/4egNxs12

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

iOS version and language: IOS 12.4.8, English

Device: iPhone 6

Jailbreak: Unc0ver

Bug description:
===

Describe the bug:
When plugging the device to charge the battery pop up view font is too large.
(I think it's because the "DATE AND ACCESSORY" font in Kalm is set to 75 and they both seem to share the same value).

How to reproduce:

1. Go to 'Kalm'
2. Set the 'DATE AND ACCESSORY' font to '75'
3. Plug the device to charge while locked or on lock screen

Expected behavior:
Charged percentage text is too large it's out of the screen borders.

Screenshots:
**how it looks stock (Kalm is turned off):** ![IMG_5207](https://user-images.githubusercontent.com/74029985/98320349-69ef5400-1feb-11eb-8c99-7fddcc49287b.PNG)

**how it looks when Kalm is enabled:** 
![IMG_5206](https://user-images.githubusercontent.com/74029985/98320444-a4f18780-1feb-11eb-8065-9e0a22a1be8c.PNG)

**how the lock screen looks:** 
![IMG_5209](https://user-images.githubusercontent.com/74029985/98320487-c18dbf80-1feb-11eb-880e-36a04794a1dc.PNG)

Additional information:
===

Tweak list:
https://pastebin.com/4AA9xQL5

Crashlog:
There is no crash.

P.S: I used to have jellyfish and it didn't have this problem but I really like Kalm more especially cause it's more customisable and versatile❤

**Comment by himynameisubik** [comment]
The size of it is unfortunately linked to the same font size as the date, so it requires some workarounds. I'll look into it but I can't guarantee a fix soon.

**Comment by himynameisubik** [comment]
Should be fixed with the upcoming update 2.3.0. No ETA yet.
