### ISSUE TITLE
Custom horizontal margin

### ISSUE THREAD

**Issue by aCluelessDanny** [himynameisubik/Kalm-support#217]
General information:
===

**Kalm version:** 2.2.0

**Kalm preferences file:** https://pastebin.com/TZ89uT34 

Device information:
===

**iOS version and language:** iOS 14.1 - English (US)

**Device:** iPhone 7+

**Jailbreak:** Checkra1n 0.12.0

Bug description:
===

**Describe the bug:**
Prior to updating iOS yesterday, I remembered that the layout always had a slight horizontal padding, but that seems to be missing here, or at least a lot smaller, after I've installed Kalm back in. It might just be a minor nitpick of mine, but I assume this is a bug for this device (given that Checkra1n just updated yesterday to support my device) & there's no setting for adjusting the horizontal position/padding.

**How to reproduce:**

1. Install Kalm and respring
2. Use the Default or Compact appearance option in the settings
3. Look at the lock screen

**Expected behavior:**
The container should have a slight horizontal padding

**Screenshots:**

Sample image of how the layout should be positioned horizontally (I grabbed this from one of your demo screenshots since I don't have one of my own)

<img width="294" alt="image" src="https://user-images.githubusercontent.com/21282515/98597528-c928bf00-229e-11eb-91ac-27a1b2847078.png">

Example image of the diminsihed/missing horizontal padding:

![image](https://user-images.githubusercontent.com/21282515/98595788-0e97bd00-229c-11eb-8899-1e341a9ffdb4.png)

Example image after removing Kalm preferences file:

![image](https://user-images.githubusercontent.com/21282515/98596385-faa08b00-229c-11eb-8e72-c3258d4e1064.png)

Additional information:
===

**Tweak list:** https://pastebin.com/NMVAMYEL 

**Crashlog:** (no crashlog)

**Comment by himynameisubik** [comment]
The horizontal margin depends on your device. The margins are smaller on non-notched devices since the frame aligns with the status bar. I'll see if I can add a custom horizontal margin.
