### ISSUE TITLE
Kalm keeps crashing on Iphone X 14.0.1

### ISSUE THREAD

**Issue by blackrider71** [himynameisubik/Kalm-support#219]
General information:
===

**Kalm version:** 2.2.0

**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:** 14.0.1

**Device:** Iphone X

**Jailbreak:** checkra1n

Bug description: 
Everytime I install Kalm it keeps crashing and loose my JB. I´ve tried every step you said but the tweak list dissapears from settings. I´ve diabled all of the tweaks in icleaner and after respring the Kalm tweak simply isn´t there. When I remove Kalm from cydia or disable it from icleaner my JB and the tweaks all come back.
===

**Describe the bug:**

**How to reproduce:**

**Expected behavior:**

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Please create an issue with the provided template.

**Comment by Drupe14** [comment]
I'm having the same issue as OP - what can I do to remedy?

**Comment by himynameisubik** [comment]
> I'm having the same issue as OP - what can I do to remedy?

Please report a bug with the provided template and fill out the needed information. Without that, I can't do much unfortunately. And also, don't use 2.2.0.

**Comment by Drupe14** [comment]
Nevermind! I deleted the .plist file from preferences and it worked. But,
my follow up question would be: how come when I switched the position from
Left to Right, it caused perpetual crashes?

That does seem buggy!

iphone8 13.5 odesseyra1n
