### ISSUE TITLE
Feature Request : Only tint texts for Third-Party main color

### ISSUE THREAD

**Issue by CySxL** [himynameisubik/Kalm-support#220]
General information:
===

**Kalm version:**
2.2.0
**Kalm preferences file:**
Put it on www.pastebin.com.

https://pastebin.com/EuJSpp8V

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
iOS13.3, Traditional Chinese
**Device:**
iPhoneX
**Jailbreak:**
Checkra1n

Bug description:
===

**Describe the bug:**

No bugs. 

Just want the old feature of Kalm that only tints Time's texts according to Third-Party "main" colors back.

Right now Kalm would tint the Time texts with second color of third-party tweak like ColorFlow 5, I don't want that.

**How to reproduce:**
Just play some media with cover artwork and install ColorFlow 5 as well.

**Expected behavior:**

Tint Time section like other section with same main color.

**Screenshots:**

![E097CEE3-760B-4AC9-9C22-4861242EAD23](https://user-images.githubusercontent.com/15531137/99877305-19593700-2c38-11eb-85c5-a3acdf7b46a1.jpeg)

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
This feature will not be worked on, sorry.

**Comment by CySxL** [comment]
It'a ok !

But may I ask why 🤔 ?
