### ISSUE TITLE
Kalm sends me straight to safe mode

### ISSUE THREAD

**Issue by Oliverkiller** [himynameisubik/Kalm-support#221]
General information:
===

**Kalm version:2.2.0**

**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:iOS 14.1 /English **

**Device:iPhone 6s**

**Jailbreak:odysseyra1n**

Bug description:
=== 
since the latest apt update from procursus repo made Kalm keeps sending me to safe mode every single time

**Describe the bug: **

**How to reproduce:**

**Expected behavior:**

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog: https://pastebin.com/swHtxDhx **
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Seems like a 14.1 issue. Should be fixed with the next update. Please make sure to create an issue with the provided template next time. Else it will be closed.

**Comment by Oliverkiller** [comment]
Actually I restored and I jailbreak with checkra1n and it works as well as Kalam worked fine with any apt version before 2.1.11 using odysseyra1n

**Comment by himynameisubik** [comment]
Huh, that's weird. Because I found something about the reason in the Crashlog. But that only impacts notch-devices.

**Comment by Oliverkiller** [comment]
I use iPhone 6s this is why it didn't impact me then
