### ISSUE TITLE
Weather doesn't update correctly and "Up Next" text sometimes doesn't show

### ISSUE THREAD

**Issue by libertig** [himynameisubik/Kalm-support#222]
General information:
===

**Kalm version:** 2.2.0

Device information:
===

**iOS version and language:** 14.1, English

**Device:** iPhone 7

**Jailbreak:** Odysseyra1n

Bug description:
===

**Describe the bug:** weather doesn't update correctly, if you enter the weather app then it shows the correct value. Also the "Up Next" text sometimes doesn't show, leaving a blank space where it should appear.

**Comment by himynameisubik** [comment]
Please use the provided template and provide the needed information. I can't do much with this report. Will re-open after information is added.
