### ISSUE TITLE
Kalm, ColorFlow 5, and Dress don’t work properly together

### ISSUE THREAD

**Issue by CoolOrbit** [himynameisubik/Kalm-support#223]
General information:
===

**Kalm version:**
2.2.1

**Kalm preferences file:**
https://pastebin.com/EPQ9z7DG

Device information:
===

**iOS version and language:**
13.5, English

**Device:**
iPhone XS

**Jailbreak:**
Odyssey

Bug description:
===

**Describe the bug:**
The "third party colors" option doesn't work properly with ColorFlow, the compact layout in Kalm (though I haven't tried the other layouts), and Dress.

The only things that color properly are the lock and weather. The time only changes color if you leave the lockscreen (turning off display or going to homescreen) and the date doesn't change color at all.

**How to reproduce:**
1.) use compact Kalm layout with third party colors option enabled and ColorFlow + Dress installed

2.) witness the fuckery

**Expected behavior:**
No fuckery

**Screenshots:**
https://imgur.com/a/UrFSFwQ

Additional information:
===

**Tweak list:**
https://pastebin.com/M1WSJq3n

EDIT: Honestly if you just added an option to have a different custom color when music is playing that'd be fixed enough for me. The only reason I'm even using ColorFlow is because I can't make Kalm white when the media player is showing.

**Comment by himynameisubik** [comment]
If you enabled the time to be tinted in Settings, it will use the secondary color of ColorFlow and if not it will use the normal color it would use. The date view and weather (if enabled to be tinted) will use the primary color of ColorFlow. This is the intended behavior.

Kalm is not tested with Dress. Might want to test if it still occurs if you disable it.

**Comment by CoolOrbit** [comment]
> If you enabled the time to be tinted in Settings, it will use the secondary color of ColorFlow and if not it will use the normal color it would use. The date view and weather (if enabled to be tinted) will use the primary color of ColorFlow. This is the intended behavior.

I know that's the intended behavior but that's not what is happening.

> Kalm is not tested with Dress. Might want to test if it still occurs if you disable it.

Yes sorry I thought I had mentioned it but it Dress is the main culprit, it works fine without it.

**Comment by himynameisubik** [comment]
No worries, yeah Dress is/seeems not compatible.

**Comment by CoolOrbit** [comment]
So should I report it to Litten then?
