### ISSUE TITLE
Bug: Drop-shadow on labels appears

### ISSUE THREAD

**Issue by CySxL** [himynameisubik/Kalm-support#224]
General information:
===

**Kalm version:**
2.2.1
**Kalm preferences file:**

https://pastebin.com/e88ThTtZ

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
iOS13.3, Traditional Chinese
**Device:**
iPhoneX
**Jailbreak:**
Checkra1n 0.12.2

Bug description:
===

**Describe the bug:**

When slide down Notification center, there will be a grey blur background behind the Date and Accessory section. 

But when you stay on Notification center and switch songs manually, the blur background will disappear itself until you leave NC and
slide down NC again.

**How to reproduce:**

1. Launch a media player app and play
2. Slide down NC
3. The grey blur background appears
4. Stay on NC and switch songs manually
5. The grey background disappears 
6. leave NC (swipe up)
7. Swipe down NC again
8. the grey blur background appears again

**Expected behavior:**

Remove the grey blur background totally.

**Screenshots:**
![26C2BE1D-5073-4DAB-9734-AE9B047FB2FA](https://user-images.githubusercontent.com/15531137/103610562-721c2f00-4f5b-11eb-8055-72f754cbadba.png)
![A30993BC-42EF-431D-95B5-888A0855EA37](https://user-images.githubusercontent.com/15531137/103610599-83fdd200-4f5b-11eb-8007-9f6a2e68be3b.png)
![0F72F5E9-FD8F-458E-8E52-61FF0C7F161F](https://user-images.githubusercontent.com/15531137/103610619-8e1fd080-4f5b-11eb-99b9-0798341156fc.png)
![95A9EB8A-340F-4712-8D3C-D841B56A976A](https://user-images.githubusercontent.com/15531137/103610652-9bd55600-4f5b-11eb-9931-909ae4d1ff18.png)
![7B82D1AD-4B8E-4D25-9045-0D600ED256D2](https://user-images.githubusercontent.com/15531137/103610673-a7288180-4f5b-11eb-953f-1da8e77df7b6.png)
![380D3646-E99D-4ED0-8DAA-A86751E2284B](https://user-images.githubusercontent.com/15531137/103610682-abed3580-4f5b-11eb-9d3a-655c6dea6806.png)

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

https://pastebin.com/28PguTHx

**Crashlog:**
Put it on www.pastebin.com
no crash log

**Comment by himynameisubik** [comment]
Yeah that's a bug. Will be fixed with 2.3.0

**Comment by CySxL** [comment]
![58125410-E62C-4F5B-B730-4B14D54A6197](https://user-images.githubusercontent.com/15531137/103647800-d1e3fb80-4f96-11eb-826e-b6d482222786.png)
![Uploading 0423BD14-45FF-4389-89B8-A78CA1D0402C.png…]()


happens on Alternate Date too

**Comment by CySxL** [comment]
![56F83736-DE39-44ED-ADDD-3A4ACFE6C1C6](https://user-images.githubusercontent.com/15531137/103648089-41f28180-4f97-11eb-855b-fb42c780f35f.png)
no blur background one here
