### ISSUE TITLE
Bug : landscape layout messes up

### ISSUE THREAD

**Issue by CySxL** [himynameisubik/Kalm-support#225]
General information:
===

**Kalm version:**
2.2.1
**Kalm preferences file:**

https://pastebin.com/e88ThTtZ

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
iOS13.3, Traditional Chinese
**Device:**
iPhoneX
**Jailbreak:**
Checkra1n 0.12.2

Bug description:
===

**Describe the bug:**

Kalm at landscape mode is way too far from top of screen, can't adjust it back to normal 'cause my current setup of portrait mode is perfect.

**How to reproduce:**

Swipe down NC in landscape mode.

**Expected behavior:**

Kalm not floats up too much like my current setup.

Or Kalm has ability to set separate setup for landscape mode.

**Screenshots:**
![621A94C4-AC69-45DB-91C2-5E5A456E35D3](https://user-images.githubusercontent.com/15531137/103613742-0db09e00-4f62-11eb-9a65-92aee720d50f.png)

![521507B4-F97B-4C46-A452-3751520F01C5](https://user-images.githubusercontent.com/15531137/103613800-3173e400-4f62-11eb-9fa1-01f58485c7db.png)

Additional information:
===

**Tweak list:**

https://pastebin.com/28PguTHx

**Crashlog:**

 no crash log

**Comment by himynameisubik** [comment]
Unfortunately this is due to using to many negative values in spacing. Adding seperate landscape options would introduce to much clutter and possibly more issues. Sorry for that, hope you can achieve your desired setup in another way.

**Comment by CySxL** [comment]
It'a okay. 

Any clue/option u can give me to reduce the negative value ? 

because now no matter how I adjust it, the landscape position doesn't move at all.

**Comment by CySxL** [comment]
after some investigation,
here is the weird situation I found 
https://streamable.com/9dl8w6
