### ISSUE TITLE
Bug : Time/Date at Today view is blocked

### ISSUE THREAD

**Issue by CySxL** [himynameisubik/Kalm-support#226]
General information:
===

**Kalm version:**
2.2.1
**Kalm preferences file:**

https://pastebin.com/TRCzjAZ0

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
iOS13.3, Traditional Chinese
**Device:**
iPhone X
**Jailbreak:**
Checkra1n 0.12.2 with Substitute 2.0.1

Bug description:
===

**Describe the bug:**

When Custom Position is adjusted to any negative value, the Time/Date will be blocked in Today View page (the swipe-left widgets page)

**How to reproduce:**

1. Go to GENERAL SETTINGS
2. Click on More
3. Enable CUSTOM POSITION
4. Swipe left from Lockscreen
5. See the whole widgets being moved up to block the Time/Date

**Expected behavior:**

Do not block the Time/Date, remain the default height/Y-position of Today View. 

**Screenshots:**

--> Set the CUSTOM POSITION with negative value : 
![D65BDD9B-BB4E-4964-B00F-DA6F53FB506E](https://user-images.githubusercontent.com/15531137/104095757-a84b0d00-52d3-11eb-8acb-72936e55ecf4.jpeg)

--> normal or with positive value of CUSTOM POSITION : 
![5B54FA03-0866-4722-9840-AB62E711B6DE](https://user-images.githubusercontent.com/15531137/104095764-ae40ee00-52d3-11eb-8b7e-ef502d11f7ca.jpeg)

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**

No crash log here

**Comment by himynameisubik** [comment]
This is intentional. When using custom position the time will be hidden on the today view. Will not be changed.
