### ISSUE TITLE
Issues on landscape mode

### ISSUE THREAD

**Issue by B777-9X** [himynameisubik/Kalm-support#227]
![68F039D6-D680-4B92-9E8C-90978BCF583B](https://user-images.githubusercontent.com/77750791/105610016-6be4da00-5dc6-11eb-87eb-d853b22796be.png)

Wanted to move kalm on the left side. This only happens in landscape mode. Apart from that, this tweak is awesome!

**Comment by himynameisubik** [comment]
Sorry for the inconvenience. Can't reproduce this issue, try disabling other tweaks or change the appearance of Kalm to see if it persists. If yes, please create an issue with the provided template.
