### ISSUE TITLE
Clock isn't automatically changing color upon wallpaper changes.

### ISSUE THREAD

**Issue by MrMrMr** [himynameisubik/Kalm-support#228]
General information:
===

**Kalm version:** 2.2.1

**Kalm preferences file:** https://pastebin.com/qDrznhBs

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:** iOS 13.5, English

**Device:** iPhone XS

**Jailbreak:** Unc0ver 5.0.1

Bug description:
===

**Describe the bug:**
The clock color doesn't automatically adjust when changing the wallpaper from something dark to something light and visa versa. This makes it hard to see the time when going to the lock screen after changing the wallpaper. A temporary fix to this is to respring the device causing the colors to adjust.

Note: In the screenshots I posted, the accent color for the date and weather have issues changing as well. This is usually not an issue on real images. I tried using extreme examples to illustrate the issue with the clock better but everything else started having issues as well.

**How to reproduce:**

1. Set wallpaper to a dark image and respring so the clock changes to a lighter color
2. Change the wallpaper to something that has a lot of white. 
3. Lock the device, then unlock and the clock color should blend in with the background. (Note: Sometimes, it will decide to add a drop shadow to the clock and is still readable. Using images that are majorly white will prevent the shadow from appearing.)
4. Respring the device and the clock will turn to a darker color making it readable again.

**Expected behavior:**
When changing the wallpaper from a dark image to a light image, Kalm should change the colors without respringing. The version that this works on is version 2.1.1. I've included screenshots of how 2.1.1 handles the colors.

**Screenshots:**
![2 2 0 and Higher White](https://user-images.githubusercontent.com/1860937/105617964-ccacec00-5d9f-11eb-93c9-d5d34433b1d3.png)
![2 2 0 and Higher Black](https://user-images.githubusercontent.com/1860937/105617966-d0407300-5d9f-11eb-9611-77d45da7f733.png)
![2 1 1 Working Example](https://user-images.githubusercontent.com/1860937/105617968-d2a2cd00-5d9f-11eb-9e0a-6f3f8a39f0d1.png)

Additional information:
===

**Tweak list:**
https://pastebin.com/dHCP6beW

**Crashlog:**
No crashing occurs.

**Comment by himynameisubik** [comment]
Will look into this.
