### ISSUE TITLE
Feature request: add an standard clock view for settings app

### ISSUE THREAD

**Issue by libertig** [himynameisubik/Kalm-support#229]
I noticed that Kalm screws the clock inside settings app when you first install it. The clock get misaligned and the only way to revert it is not only deleting the tweak but updating the system or restoring it.

I would suggest to add an standard view for this (like a clean clock) or at least fix the permanent misalignment.

Here's an example: https://imgur.com/a/SsuAd7V

**Comment by himynameisubik** [comment]
I know this is sub-optimal, but this will not be actively worked on. Sorry for the inconvenience.
