### ISSUE TITLE
Feature request: Show stock alarm on lock screen

### ISSUE THREAD

**Issue by rahulsinghal97s** [himynameisubik/Kalm-support#23]
I would like to request feature that can show alarm that is Set in stock alarm app. Thank you.

**Comment by himynameisubik** [comment]
Will look into it, but can't promise any ETA.

**Comment by rahulsinghal97s** [comment]
Thank you so much.  Yes take your time bro

**Comment by p2kdev** [comment]
Btw. This is how you get the next alarm on iOS13. I used this in my tweak Sakal

	MTAlarmManager *alarmManager = MSHookIvar<MTAlarmManager *>([%c(SBScheduledAlarmObserver) sharedInstance], "_alarmManager");
	MTAlarm *nextAlarm = [alarmManager nextAlarmSync];

	NSString *nextAlarmString = nil;

	if (nextAlarm)
	{
		@try
		{
			NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
			[formatter setDateFormat:alarmFormat];
			NSString *nextAlarmAt = [formatter stringFromDate:nextAlarm.nextFireDate];

			int difference = [nextAlarm.nextFireDate timeIntervalSinceNow];

			if (difference > 0)
			{
				difference += 60; // Round to next minute
			}

			int hours = difference / 3600;
			int minutes = (difference / 60) % 60;

			if (hours < nextAlarmThreshold)
			{
				NSString *timeUntilAlarm = (hours > 0) ? [NSString stringWithFormat:@"%02d hr %02d min",hours,minutes] : [NSString stringWithFormat:@"%02d min",minutes];

				if (alarmType == 1)
					nextAlarmString = nextAlarmAt;
				else if (alarmType == 2)
					nextAlarmString = timeUntilAlarm;
				else
					nextAlarmString = [NSString stringWithFormat:@"%@ (%@)",nextAlarmAt,timeUntilAlarm];
			}
		}
		@catch (NSException *exception)
		{
			nextAlarmString = @"Invalid DateTime Format!";
		}
	}

Let me know if you have any questions!

**Comment by himynameisubik** [comment]
Thanks @p2kdev! Not sure yet, if this will be added any time soon.

**Comment by rahulsinghal97s** [comment]
Have you find the way out ?

**Comment by himynameisubik** [comment]
Yes, but as said before, this will not be added any time soon as at the moment there are other tweaks who offer this and I'm working on other enhancements. Need some time.

**Comment by rahulsinghal97s** [comment]
Any update on this feature bro ??

**Comment by himynameisubik** [comment]
If there is an update
on any issue, I will update said issue.

**Comment by himynameisubik** [comment]
Will be added in 1.3.3

**Comment by himynameisubik** [comment]
Kalm 1.3.3 was submitted to Packix

**Comment by rahulsinghal97s** [comment]
Thank you so much bro for the update
