### ISSUE TITLE
Padding is messed up on iOS 14

### ISSUE THREAD

**Issue by ZenIsBestWolf** [himynameisubik/Kalm-support#231]
General information:
===

**Kalm version:**
3.0.0
**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

https://pastebin.com/YdJ5biga

Device information:
===

**iOS version and language:**
iOS 14.3 Main: English US. Added: Spanish US, Japanese
**Device:**
iPhone 8 Plus (iPhone10,5)
**Jailbreak:**
unc0ver 6.0.0

Bug description:
===

**Describe the bug:**

The padding on the lock screen is incorrect.

**How to reproduce:**

1. Install Kalm
2. Go to lock screen
3. See error

**Expected behavior:**

The padding should be there

**Screenshots:**

Image of issue: ![image](https://user-images.githubusercontent.com/28688587/109409522-80863600-7961-11eb-83f5-5d86e461a58a.png)

Image of expected result: ![image](https://user-images.githubusercontent.com/28688587/109409529-8da32500-7961-11eb-8dcb-22a8c323cd3f.png)

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com
This occurs with no other tweaks enabled.
**Crashlog:**
Put it on www.pastebin.com
No crash occurs.

**Comment by himynameisubik** [comment]
Use the option "Custom horizontal margin" in "More" to adjust the distance between Kalm and the edge of your display on iOS 14..

**Comment by ZenIsBestWolf** [comment]
> Use the option "Custom horizontal margin" in "More" to adjust the distance between Kalm and the edge of your display on iOS 14.

Thanks, although this fixes it visually, this might still be considered a bug since the default values have now changed and anyone who used this offset option will now find it different on 14 as well.

**Comment by himynameisubik** [comment]
It will be fixed with the next update and a standard offset on iOS14.

**Comment by ZenIsBestWolf** [comment]
Awesome, thanks so much!

**Comment by ewillyc** [comment]
How did you dissapear the lock icon?

**Comment by ZenIsBestWolf** [comment]
> 
> 
> How did you dissapear the lock icon?

i pulled down the notification shade

**Comment by himynameisubik** [comment]
Kalm 3.0.1 was released.
https://twitter.com/HiMyNameIsUbik/status/1372534026502873093
