### ISSUE TITLE
Old alarm showing

### ISSUE THREAD

**Issue by juliocormor** [himynameisubik/Kalm-support#234]
General information:
===

**Kalm version:**
3.0.0
**Kalm preferences file:**
https://pastebin.com/g6fdaet8

Device information:
===

**iOS version and language:**
iOS 14.3 - Spanish
**Device:**
iPhone 11, 128 Gb
**Jailbreak:**
Unc0ver 6.0.0

Bug description:
===

**Describe the bug:**
I have an alarm from 1 month ago stuck in my up next reminders, the day 6 of February at 10:15 am.

**How to reproduce:**
Not really sure. No alarms enabled apart from the sleep mode one.

**Expected behavior:**
Only seeing upcoming events and alarms.

**Screenshots:**
https://i.imgur.com/DndpqHv.jpg
[day-month, hour (6 of Februar)]

https://i.imgur.com/ptuJYmx.jpg
[hour (6 of February)]

https://i.imgur.com/N9A1tDI.jpg
[, day, month(NOW)]

https://i.imgur.com/uPFX45Q.jpg
my normal lockscreen [writtenDay, numberDay(NOW)]

Additional information:
===
I'm not sure where this alarm is coming from, really.

**Tweak list:**
https://pastebin.com/KMqzJRhC

**Crashlog:**
I don't have (I think).

**Comment by himynameisubik** [comment]
Can you try disabling alarms, reminders and calendars in Up Next and then respring. After that enable only alarms and respring. Sorry for the inconvenience.

**Comment by juliocormor** [comment]
If I disable alarms, reminders and calendars, it does not appear. If I enable alarms back it appears again. (Done with resprings)

**Comment by juliocormor** [comment]
Do you know if I can delete the file containing all my alarms? I don’t really know where it is or if I should try.

**Comment by himynameisubik** [comment]
Hmm, that's really weird. So it is definitely an alarm. It might have something to do with the sleep schedule or an alarm for a reminder or calendar entry. Could you try resetting the sleep schedule and check the dates you mention for any calendar entries or reminders that may have an alarm set?

Also *did* you have an alaram set on that date (if you remember)?

**Comment by juliocormor** [comment]
Ok, deleting my sleep schedule but keeping it on shows the old alarm, but if I turn it off it disappears. So we know it comes from the sleep shedule.

https://user-images.githubusercontent.com/63738513/109663990-fdd1c680-7b6c-11eb-8f60-6e239d8f8f43.mp4

https://user-images.githubusercontent.com/63738513/109663999-00ccb700-7b6d-11eb-86e1-4e19b39c4e03.mp4

About calendar entries, I have zero, checking the reminders apps showed me the tutorial (so I have never used it before), also no reminders.

**Comment by himynameisubik** [comment]
Huh, that's really really weird. (Yeah I already said that).

But I'm glad you reported this and even resolved it with some easy steps. Thanks a lot for even updating the answer! :)
Will close this for now.

**Comment by JaredTheWolf** [comment]
@himynameisubik I actually just came to report this. I have tried the same steps as above with no luck. I also have sleep scheduling enabled

**Comment by himynameisubik** [comment]
> @himynameisubik I actually just came to report this. I have tried the same steps as above with no luck. I also have sleep scheduling enabled. I tried deleting the Kalm preferences file thinking it was a preference issue, but no dice.

You did the steps @juliocormor has done too? Disabling sleep schedule, etc? Does disabling the schedule also remove the alarm?

**Comment by JaredTheWolf** [comment]
> You did the steps @juliocormor has done too? Disabling sleep schedule, etc? Does disabling the schedule also remove the alarm? 

Yes. https://streamable.com/0z4u9o

> Can you please also post screenshots with the alarms and dates and settings?

[lockscreen](https://user-images.githubusercontent.com/21344934/109671616-3a3bfd00-7b42-11eb-9063-3bc927b2fd97.png), [settings 1](https://user-images.githubusercontent.com/21344934/109671689-4de76380-7b42-11eb-88e1-50b6139a2b1b.png), [settings 2](https://user-images.githubusercontent.com/21344934/109671743-59d32580-7b42-11eb-9c6f-7d933af9f6ac.png), [settings 3](https://user-images.githubusercontent.com/21344934/109671794-65265100-7b42-11eb-95b7-0bc6a76037a5.png), [alarm schedule 1](https://user-images.githubusercontent.com/21344934/109671837-6eafb900-7b42-11eb-94df-4d6a66b56d3a.png), [alarm schedule 2](https://user-images.githubusercontent.com/21344934/109671886-78392100-7b42-11eb-9bbc-0a2707ace818.png)

Let me know if you need anything else.

**Comment by himynameisubik** [comment]
Can you *delete* the schedule and the alarms, respring and setup a new schedule? I feel like this is some kind of a "ghost" alarm that doesn't really exist anymore, but it's weird that it's enabled.
