### ISSUE TITLE
Add toggle to enable charging view

### ISSUE THREAD

**Issue by MTACS** [himynameisubik/Kalm-support#239]
With the latest update of Kalm (3.0.0), the native MagSafe views used in Lynx 2 and similar tweaks is hidden. Disabling or downgrading to previous versions gets rid of the issue.

**Comment by himynameisubik** [comment]
That's intended since I change the charging label which results in weird charging views. But I'll add a toggle in a later version, so it's just an option that is on by default. If a user has some third-party charging view he can use that.

**Comment by MTACS** [comment]
Activating the built in MagSafe view adds the view to the CSCoversheetViewBase. I'd figure it wouldn't have to hide this view as it doesn't contain the charging label but I may be wrong. Other tweaks like "MagSafe" which create the view could add a check.

**Comment by himynameisubik** [comment]
I don't hide the CSCoversheetViewBase, I only changed CSCoverSheetViewController's _transitionChargingViewToVisible to:
```- (void)_transitionChargingViewToVisible:(BOOL)arg1 showBattery:(BOOL)arg2 animated:(BOOL)arg3 {
	arg2 = NO;
	arg3 = NO;
	%orig;
}
```

**Comment by himynameisubik** [comment]
Kalm 3.0.1 was released.
https://twitter.com/HiMyNameIsUbik/status/1372534026502873093
