### ISSUE TITLE
Safemode crash after enabling the Up Next style Compact

### ISSUE THREAD

**Issue by epsyIon** [himynameisubik/Kalm-support#24]
**Describe the bug**
After enabling the Up Next style Compact in the Settings app the device immediately crashes into safemode and to go back you need to change the setting back in Filza.

BUT: This doesn't happen all the time. It looks like it has to do with the length of the text which needs to be displayed. As you can see in the screenshot, the text would be too long for the screen width of my device. The Compact Up Next style works on shorter calendar events.

**How to reproduce**

0. Have a calendar event with many symbols and set it to a specific time for even more symbols
1. Open Settings app
2. Go to 'Kalm' settings
3. Click on 'Up Next'
4. Choose the style 'Compact'
5. See error

**Expected behavior**
No crash

**Screenshots**
https://imgur.com/WUu5rKI

**iOS Version:**
13.3

**Device:**
iPhone SE

**Device language:**
English

**Tweak list:**
Happens even with all tweaks besides Kalm disabled in iCleaner.

**Crashlog:**
Cr4shed doesn't recognize it as a crash, no crashlog.

**Comment by himynameisubik** [comment]
Thanks for the report!
Will look into this and sorry for the inconvenience.

**Comment by himynameisubik** [comment]
Is the event in your screenshot causing this crash? If so I can check it with the identical data on my SE.

**Comment by EPSYLON2K** [comment]
Yes, that's the event causing the issue. Thanks for the fast reply!

**Comment by himynameisubik** [comment]
Was able to reproduce this issue and will be fixed soon. Thanks for raising this issue!

**Comment by himynameisubik** [comment]
Closing this as 1.2.1 was submitted to Packix.

**Comment by himynameisubik** [comment]
1.2.1 is released.

**Comment by epsyIon** [comment]
1.2.1 fixed the issue, thank you!
