### ISSUE TITLE
Safe mode crash when having a specific configuration and switching to "mini" appearance in Up Next 

### ISSUE THREAD

**Issue by zuiaiqie** [himynameisubik/Kalm-support#241]
General information:
===

**Kalm version:**
3.0.0

**Kalm preferences file:**
https://pastebin.com/C99iHDVA

Device information:

**iOS version and language:**
ios 14.3, english

**Device:**
iPhone 12 Pro

**Jailbreak:**
unc0ver 6.1.1

Bug description:
===

**Describe the bug:**

note: Sorry for my grammer, not a native English speaker. I Disabled all tweaks but kalm in icleaner and usersoace rebooted, so this should be just about kalm tweak.

Event icon bug: Under [UP NEXT-settings], goes to safemode when: 1.setting the up next apperance to mini and 2. enabling both event icon and color indicator in calendar section. No safemode when setting the up next apperance to default or compact, only mini.

Fonts color issue: the color I picked from the suggested colors under [general settings-colors-accent color-wallpaper color]  got reset everytime when dark mode is turned on and off. This probably becuase the wallpaper changed under dark mode (i use the default apple wallpaper which looks different in dark mode), but I didn't change the wallpaper itself. Anyway to keep the color preference in both light/dark mode, so switching back from dark mode still keeps the old, already selected font color？

Also, a little suggestion: can you kindly add an option to config the spacing between each events in up next? Pretty much every other spacing can be changed in the [fonts] setting, but not the spacing between each events. Please consider add it for better customization.

Many thanks!

**Comment by himynameisubik** [comment]
Bug reports should be seperate as this creates a mess. 

But besides that; 

1. I can't reproduce the issue using mini, event icon & color indicator, I'm using the same setup. See here: 
![110292288-4239e800-7fed-11eb-951f-62949084b7e3](https://user-images.githubusercontent.com/322449/110292720-f176bf00-7fed-11eb-9cd1-da8250675428.png)

2. If you would like to keep one color, you're better of using the custom color option. 

3. Not sure if this will be added, as currently feature requests are closed.

Sorry for any inconvenience.

**Comment by zuiaiqie** [comment]
You seems be using the large appearance for the clock in the screenshot, can you try the default appearance for both the clock view and the up next?

**Comment by himynameisubik** [comment]
No I don't but here are other styles:
![IMG_0129](https://user-images.githubusercontent.com/322449/110293697-2e8f8100-7fef-11eb-9a48-c4f168d58fcf.PNG)
![IMG_0128](https://user-images.githubusercontent.com/322449/110293724-351df880-7fef-11eb-859a-0fc673e87583.PNG)
![IMG_0127](https://user-images.githubusercontent.com/322449/110293728-36e7bc00-7fef-11eb-9486-b73132724752.PNG)
![IMG_0126](https://user-images.githubusercontent.com/322449/110293730-37805280-7fef-11eb-9843-3b334ddae631.PNG)


And here with your preferences:
![IMG_0131](https://user-images.githubusercontent.com/322449/110294326-005e7100-7ff0-11eb-9db9-8b31b472e6f0.PNG)

**Comment by zuiaiqie** [comment]
Can you try this one?
![1](https://user-images.githubusercontent.com/54428901/110294620-0a519580-802b-11eb-877b-c2370dc1e9b1.png)
![2](https://user-images.githubusercontent.com/54428901/110294607-04f44b00-802b-11eb-9595-4a256acc2a7e.png)

**Comment by himynameisubik** [comment]
Confirmed, will look into it. Thanks for the repot

**Comment by zuiaiqie** [comment]
Thank you for your quick response!

**Comment by himynameisubik** [comment]
Kalm 3.0.1 was released.
https://twitter.com/HiMyNameIsUbik/status/1372534026502873093
