### ISSUE TITLE
Weather always not showing in the lockscreen

### ISSUE THREAD

**Issue by luv-letter117** [himynameisubik/Kalm-support#242]
General information:
always showing 'N/A'

**Kalm version:3.0.0

**Kalm preferences file:**
https://pastebin.com/shvXP0vp

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language: ios 14.2 Chinese

**Device:xs

**Jailbreak:unc0ver 6.1.1

Bug description:
===

**Describe the bug:**
weather always  showing 'N/A' in the lockscreen

**How to reproduce:**

1. Go to Cydia
2. Click on install kalm
3. See error

**Expected behavior:

**Screenshots:
![9A261BB7-0CC4-432F-9E4F-901EFBEA8832](https://user-images.githubusercontent.com/22892413/110290256-8812a280-8025-11eb-9e04-61098516c050.jpeg)

Additional information:
===

**Tweak list:
This occurs with no other tweaks enabled.

**Crashlog:
no crsah

**Comment by himynameisubik** [comment]
Do you have a location set in the Weather app? And if not, do you have Location Services enabled for Widgets & App? Settings > Privacy > Location Services > Weather > While using the App or Widgets

**Comment by luv-letter117** [comment]
yes, I did

**Comment by himynameisubik** [comment]
Unfortunately I can't help you out with this information as I can't reproduce your issue. Feel free to send me a refund request. Sorry for the inconvenience.

**Comment by luv-letter117** [comment]
> Hi, I wanted to jump in on this as I have two phones and this definitely seems to be an issue, not necessarily with Kalm I suppose but at least with iOS 14+. On my iPhone 8 Plus running iOS 13.5 and Unc0ver 5.0.1 and the 3.0.0 version of Kalm, I have location services enabled with weather configured to “While using the app” as no “while using the app or widgets” option is available on iOS 13.5. I also have NOT added any locations to the weather app and the weather on the lock screen updates correctly as expected, driving from city to city and continues to work even after respring/reboot/rejailbreak. On my iPhone 11 running iOS 14.2 and Unc0ver 6.0.1 and the same 3.0.0 version of Kalm, location services are enabled and weather is set to “while using the app or widgets” and on this phone too, I did NOT manually add any locations to the weather app and Kalm only shows N/A on the lock screen at all times. If I manually open the weather app and lock the phone, the lock screen does update but after the screen turns off again, it goes back to N/A and never updates automatically again until I open the weather app. For this phone, if I follow your instruction to manually add a location to the weather app, then Kalm only shows the weather for that location only and I noticed two things: 1.) it does not update when I’m in a new city and 2.) while it remains on the manually added location, it doesn’t even update the temp accordingly for that city. I tried all of your troubleshooting steps (yes, disabled all tweaks with iCleaner Pro) but nothing is getting it to work. I went as far as using the hi.my.name.is.ubik.kalm.plist file from my 13.5 phone to the 14.2 phone and respringing but that didn’t work. Background app refresh for the weather app is enabled as well on both phones.
> 
> I’m aware you can’t reproduce this issue but I wanted to share my experience.

**Comment by luv-letter117** [comment]
My issue is caused by a tweak called Relocate Reborn, When I disable it with iCleaner Pro, wheather refresh normally. I wish my experience  will help you.

**Comment by MikeyRod1981** [comment]
> My issue is caused by a tweak called Relocate Reborn, When I disable it with iCleaner Pro, wheather refresh normally. I wish my experience will help you.

Thanks for the sharing!  I don't have that particular tweak installed, so that isn't the case for me though it could help others that find this thread.  I don't have that many tweaks, honestly, so I don't know what could be conflicting as I disabled all Cydia Substrate add-ons with iCleaner Pro except for "Substrate Safe Mode" and it still doesn't work.

Thanks again and take care.

**Comment by luv-letter117** [comment]
Glad to help.

**Comment by himynameisubik** [comment]
Hey @MikeyRod1981 could you create a new issue for your problem? It is not linked to this problem since you don't have Relocate Reborn tweak and as you can see @luv-letter117's issue in the end _was_ another tweak despite the mention of the issue occuring without any other tweaks enabled.

**Comment by MikeyRod1981** [comment]
> Hey @MikeyRod1981 could you create a new issue for your problem? It is not linked to this problem since you don't have Relocate Reborn tweak and as you can see @luv-letter117's issue in the end _was_ another tweak despite the mention of the issue occuring without any other tweaks enabled.

Hi ubik, understood and will do, thanks!
