### ISSUE TITLE
Kalm overlaps with expanded notifications

### ISSUE THREAD

**Issue by Jarboer** [himynameisubik/Kalm-support#248]
General information:
===

**Kalm version:**
3.0.1

**Kalm preferences file:**
[Preferences](https://pastebin.com/aMHiz65a)

Device information:
===

**iOS version and language:**
iOS 14.2 and English (Canada)

**Device:**
iPhone 12

**Jailbreak:**
Unc0ver 6.1.1

Bug description:
===

**Describe the bug:**
When haptic touching on a notification including a snoozed alarm or message, kalm overlaps with the notification making it very hard to see what's underneath.

**How to reproduce:**

1. Open the notification centre
2. Haptic or 3D Touch a notification such as a snoozed alarm or message
3. Observe as kalm overlaps with the expanded notification

**Expected behavior:**
I'd expect kalm would appear blurred behind the expanded notification so it doesn't overlap with the notification.

**Screenshots:**
![image](https://user-images.githubusercontent.com/16063018/111722510-5cb76100-8838-11eb-9eef-1099a74a7074.jpeg)

![image](https://user-images.githubusercontent.com/16063018/111722515-5f19bb00-8838-11eb-9b4f-024ca17f9ddd.jpeg)

Additional information:
===

**Tweak list:**
[Tweaks](https://pastebin.com/6V876Qe2)

**Comment by himynameisubik** [comment]
Update to 3.0.2 hotfix
