### ISSUE TITLE
"Up next" causes ~0.5s delay in turning on screen from locked

### ISSUE THREAD

**Issue by maxlesser** [himynameisubik/Kalm-support#25]
**Describe the bug**
When "up next" is enabled, there is an additional ~0.5s delay in the screen coming on when clicking a button to turn on the screen while the phone is locked. This happens on every unlock/screen turn on.

When the "up next" option is disabled, the screen turns on as quickly as expected, with no delay. "Weather" option seems to have little/no impact.

**How to reproduce**
1. Enable "Up next" option
2. Disable "Weather" option
3. enable "Calendar" events - disable "Reminder"
4. Select gmail calendar
5. Lock phone
6. click home button or lock button to turn on screen and see lockscreen
**Expected behavior**
Screen turns on immediately.
**Actual behavior**
There is a ~0.5s delay before screen turns on

**iOS Version:**
13.2.2

**Device:**
iphone 7

**Device language:**
English

**Tweak list:**
All other tweaks disabled

**Comment by himynameisubik** [comment]
Might be a conflict with the Gmail Calendar, does this also happen with a normal calendar? 

I'll try to check if I can find anything, and see if I can get a Gmail calendar set up. I assume it's because it's pulling Gmails Calendar data. 

Thanks for the report and sorry for the inconvenience!

**Comment by maxlesser** [comment]
No worries at all! Thank you for the speedy reply - it's an awesome tweak :) 

This appears to happen even with normal (non-gmail) calendars selected in the "up next" settings - I switched to "siri suggestions" only (and some other non-gmail calendars) and am seeing the same behavior.

**Comment by himynameisubik** [comment]
That's really weird then, because on my iPhone 6 it does not happen so it can't be something like "Your device is too slow to fetch the events". 

I'll check if I can find something, but I'm really not to sure what to look for.

**Comment by himynameisubik** [comment]
Possibly fixed in 1.2.1 which was submitted to Packix as of now.

**Comment by himynameisubik** [comment]
1.2.1 is released.

**Comment by maxlesser** [comment]
Awesome! Definitely looks improved, thanks for the quick help, you're a hero.
