### ISSUE TITLE
IPad support

### ISSUE THREAD

**Issue by starraiderx** [himynameisubik/Kalm-support#29]
**Describe the bug**
IPad OS is missing the weather app so weather data cant be fetched.

**How to reproduce**

**Expected behavior**

**Screenshots**

**iOS Version:**
13.3
**Device:**
ipad 8.3
**Device language:**
english 
**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Additional context**

**Comment by himynameisubik** [comment]
On iPad OS you have to use the Weather Widget. I have other users with iPad OS where it works fine.

Care to elaborate?

**Comment by starraiderx** [comment]
I didn’t know that you had to use the weather widget. Pls add this as a pop up in settings when you first open Kalm settings on iPad.

**Comment by himynameisubik** [comment]
I have added an information text on the Kalm description page.

**Comment by himynameisubik** [comment]
Sorry for the confusion.
