### ISSUE TITLE
Choose the number of events to display

### ISSUE THREAD

**Issue by LileAuTresor** [himynameisubik/Kalm-support#3]
Thank you for this excellent tweak!
It would be great if we could choose the number of events to display in the settings. Have you planned to add this feature?

**Comment by himynameisubik** [comment]
Thanks for the kind words!

It is not yet planned, but I'll look into it. No ETA yet.

**Comment by himynameisubik** [comment]
![EP8aGpaXsAEqN6X](https://user-images.githubusercontent.com/322449/73763208-68011780-4771-11ea-8033-9534d2b72bc4.png)

**Comment by LileAuTresor** [comment]
Wow, it was fast ! Thank you very much !!!

**Comment by himynameisubik** [comment]
Will still take some time until it's ready, but it's a first draft :-)

**Comment by himynameisubik** [comment]
Will be added in 1.1.0.
