### ISSUE TITLE
No date. 

### ISSUE THREAD

**Issue by Nicklasfox** [himynameisubik/Kalm-support#30]
Hello dev. 

I purchase your lovely kalm app. And I’m loving it. But where is the date?

**Comment by himynameisubik** [comment]
Did you disable all other tweaks with iCleaner? This sounds like a conflicting tweak or misconfiguration.

Did you specify a custom date format?

**Comment by Nicklasfox** [comment]
It was xenHTML. who was the bad one. So I solved it.

Thanks. 😌

Med vänlig hälsning
Nicklas Östling
Ordförande Ao
Ninjafoxen@gmail.com

Sent via Superhuman iOS ( https://sprh.mn/?vip=ninjafoxen@gmail.com )
