### ISSUE TITLE
The " ° ” next to the temperature won't show up

### ISSUE THREAD

**Issue by NAVECCIER** [himynameisubik/Kalm-support#32]
**Packix Username:***
ccyamamamwuhe

**Describe the bug**
Temperature unit doesn't show up for my system language (Chinese) and I tried to switch my language to English and it displayed properly.

**How to reproduce**

**Expected behavior**

**Screenshots**
under my system language:
![IMG_7407](https://user-images.githubusercontent.com/54629426/75135324-30581080-571c-11ea-9b2f-a049ef753f07.jpg)
when switching to English:
![IMG_7404](https://user-images.githubusercontent.com/54629426/75135382-541b5680-571c-11ea-90f3-5e757eff32c2.jpg)
Everything seems to work perfectly.

**iOS Version:**
13.3

**Device:**
iPhone XS Max

**Device language:**
Chinese

**Tweak list:**
diables all tweaks except Kalm but the problem still exists
also tried to reset settings

**Crashlog:**
Put it on www.pastebin.com

**Additional context:**
Add any other context about the problem

**Comment by himynameisubik** [comment]
Hi there, sorry for the inconvenience. Is it normal in chinese language to display the ° symbol next to the temperature? Could you show me a screenshot of your Weather Widget on the Today view (lockscreen swipe left and add Weather to it).

**Comment by NAVECCIER** [comment]
Oh, it doesn't display on Weather Widget either so it's not the problem of Kalm itself. I'm just thinking it will be a little weird to have only   one number next to the weather icon.
![IMG_7415](https://user-images.githubusercontent.com/54629426/75138921-584c7180-5726-11ea-89ec-15203c51516c.jpg)
![IMG_7416](https://user-images.githubusercontent.com/54629426/75138956-6e5a3200-5726-11ea-9965-7da1a2f65d6c.jpg)

**Comment by himynameisubik** [comment]
Yeah, this is a native iOS thing. I'll see if I can get some checks in there if a ° character is present at the end, if not add one by myself, allthough this might lead to other issues, so I don't know if I can fix this for you. You could also enable the Location or Condition for weather so it's not just a number. Sorry for the bad news.

**Comment by NAVECCIER** [comment]
Anyway thank you for your help.
