### ISSUE TITLE
Notification section in landscape mode starts lower than the usual position

### ISSUE THREAD

**Issue by p2kdev** [himynameisubik/Kalm-support#33]
**Packix Username:***
patilkiran08

**Describe the bug**
The notification section in landscape mode has empty space & hence it starts a bit lower than usual.

**How to reproduce**
1. Make sure you have few notifications in the notification center
2. Turn off rotation lock
3. Open messages app & rotate device to landscape mode
4. Pull down from the top to invoke the notification center

**Expected behavior**
The Notification list should start from the usual position

**Screenshots**
https://imgur.com/1AmJBDP?r

**iOS Version:** 13.3.1

**Device:** iPhone X

**Device language:** English

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Additional context:**
Add any other context about the problem

**Comment by himynameisubik** [comment]
Thanks for the report, will be fixed next update. Either 1.2.3 or 1.3.0.

**Comment by himynameisubik** [comment]
Fixed in 1.3.0. Submitted to Packix.
