### ISSUE TITLE
Respring Loop when reminders is active.

### ISSUE THREAD

**Issue by XGARX** [himynameisubik/Kalm-support#34]
**facebook.10157308135109072:***
Your Packix username

**Describe the bug**
Respring Loop when reminders is active, when I deactivate reminders it works again.

**How to reproduce**

**Expected behavior**

**Screenshots**

**iOS Version:**

**Device:**

**Device language:**

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Additional context:**
Add any other context about the problem

**Comment by himynameisubik** [comment]
Please provide more information

**Comment by mclgoerg** [comment]
I am having a resprikg loop aswell after I deinstalled Grupi.

**Comment by himynameisubik** [comment]
No more information provided.
