### ISSUE TITLE
Safemode after installed 1.3.0

### ISSUE THREAD

**Issue by canary-yellow** [himynameisubik/Kalm-support#36]
**Packix Username:***
harudsgn

**Describe the bug**
I just bought the kalm tweak (1.30) and went straight to safemode after I respring my springboard.

**How to reproduce**

**Expected behavior**

**Screenshots**

**iOS Version:**
12.4

**Device:**
iPhone X

**Device language:**
French

**Comment by himynameisubik** [comment]
Duplicate of #37
