### ISSUE TITLE
1.3.0 crashes SpringBoard on iOS 12.X

### ISSUE THREAD

**Issue by gkeep** [himynameisubik/Kalm-support#37]
**Packix Username:***
gkeep77 (discord.184996189677158401)

**Describe the bug**
Latest Kalm update crashes SpringBoard on iDevices running 12.X (from the looks of it).
Other reports of this in the update thread:
* [1](https://www.reddit.com/r/jailbreak/comments/fffnid/update_kalm_130_out_on_packix_now_scheduling/fjy5kao/)
* [2](https://www.reddit.com/r/jailbreak/comments/fffnid/update_kalm_130_out_on_packix_now_scheduling/fjy44im/)

**How to reproduce**
* Update to 1.3.0

**Device:**
iPhone 5S

**Device language:**
English

**Tweak list:**
[here](https://pastebin.com/kTFwxXLb)

**Comment by himynameisubik** [comment]
Sorry for the inconvenience. Will look into this. For the meantime please downgrade to 1.2.X.

**Comment by himynameisubik** [comment]
Issue is present because of the new do not disturb icon, please try these steps:
- Install 1.3.0
- Disable Kalm in iCleaner after Safe Mode
- Respring
- Go to Kalm Settings -> More
- Disable "DO NOT DISTURB ICON"
- Enable Kalm in iCleaner
- Respring

**Comment by gkeep** [comment]
Yeah, I've seen your tweet. It works! I assume you're working on a permanent fix right now?

**Comment by himynameisubik** [comment]
Yes of course

**Comment by gkeep** [comment]
Thanks for the tweak and great support ❤️

**Comment by himynameisubik** [comment]
1.3.2 was released

**Comment by gkeep** [comment]
Just updated. Works great! Thanks again.

**Comment by himynameisubik** [comment]
Sweet! Thanks for the update. Enjoy!
