### ISSUE TITLE
Flashing screen during respring

### ISSUE THREAD

**Issue by Rodknock** [himynameisubik/Kalm-support#39]
**Packix Username:***
Your Packix username

**Describe the bug**

**How to reproduce**

**Expected behavior**

**Screenshots**

**iOS Version:**

**Device:**

**Device language:**

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Additional context:**
Add any other context about the problem

**Comment by himynameisubik** [comment]
No information provided. Please open an issue with the information needed.
