### ISSUE TITLE
Sonus13 Bug

### ISSUE THREAD

**Issue by holothegreat** [himynameisubik/Kalm-support#4]
Sorry if this is wrong place, I couldn't find where else to report bugs.

When I am in landscape mode and if I switch or kill the app into portrait mode, then Sonus still thinks it is still in landscape mode so the volume hud is all rotated when I am in portrait mode. Also, the dynamic colors sometimes don't work that well when I am in a white app and it doesn't match the status bar black color.

**Comment by himynameisubik** [comment]
Via Cydia/Zebra and email. Also please provide a way to reproduce the issue along side with tweaklist and device.
