### ISSUE TITLE
1.3.0 Chinese Date Spacing Issue

### ISSUE THREAD

**Issue by terry3041** [himynameisubik/Kalm-support#40]
**Packix Username:**
leosoqq

**Describe the bug:**
The spacing between Chinese date and normal date is too small and I have no way to adjust it.
Also the Chinese date is comparatively small.

**How to reproduce:**
Update to 1.3.0

**Expected behavior:**
[Larger spacing in 1.2.2](https://i.imgur.com/bJ0VsTq.jpg)

**Screenshots:**
[Small spacing in 1.3.0](https://i.imgur.com/n5DZC4z.jpg)

**iOS Version:**
13.3

**Device:**
iPhone XS

**Device language:**
Chinese (Tradtitional)

**Tweak list:**
[Pastebin](https://pastebin.com/ViQZRBfd)

**Comment by himynameisubik** [comment]
Space was adjusted, will be adjusted again in 1.3.1.

**Comment by terry3041** [comment]
Thanks!

**Comment by himynameisubik** [comment]
1.3.2 was released
