### ISSUE TITLE
1.3.2 Chinese Date Spacing and Size Issue

### ISSUE THREAD

**Issue by terry3041** [himynameisubik/Kalm-support#41]
**Packix Username:**
leosoqq

**Describe the bug:**
The previous issue reported is still not fixed in 1.3.2. 
The gap between the Chinese date and the normal date is too small.
The font size of the Chinese date is too small.

**How to reproduce:**
Update to 1.3.2

**Expected behavior:**
The font size should be bigger and the spacing should be larger like what you have done in Kalm 1.2.2.
![39B9ECB8-7695-4516-9B1A-E558B9D67D42](https://user-images.githubusercontent.com/19218518/76267312-4bdb2380-62a5-11ea-97e7-a0331e69124e.jpeg)

**Screenshots:**
Small font size and small gap.
![8745E105-0B4E-4C7B-A4F4-0237B31526D6](https://user-images.githubusercontent.com/19218518/76267268-23532980-62a5-11ea-8cb2-6ef4de627ec3.jpeg)

**iOS Version:**
13.3

**Device:**
iPhone XS

**Device language:**
Chinese (Traditional)

**Tweak list:**
[Pastebin](https://pastebin.com/ViQZRBfd)

**Comment by himynameisubik** [comment]
Will be adjusted, but not in the same way as first version.
