### ISSUE TITLE
Is it compatible with WeatherLock13?

### ISSUE THREAD

**Issue by FVI812** [himynameisubik/Kalm-support#42]
**FVI:***

FVI

**Request:** Hey guys, is there a chance Kalm could be or is it already compatible with WeatherLock13? If it is I'll purchase it in no time!

Thanks for this awesome tweak!

**Comment by himynameisubik** [comment]
Kalm-support is not meant for Questions, it's meant for support, feature requests and issue tracking. Please ask in r/jailbreak to see if somebody knows. Thank you!
