### ISSUE TITLE
1.3.2 & 1.3.1 conflicts with lockwidgets

### ISSUE THREAD

**Issue by vpww** [himynameisubik/Kalm-support#43]
**Packix Username:***
vpww

**Describe the bug**
Install both lockwidgets and kalm and you device goes to safemode after install.if one of those tweaks is disabled- everything is fine. 
1.3 works good with lockwidgets

**iOS Version:**
13.3
**Device:**
11 pro ma x
**Device language:**
Russian

**Comment by himynameisubik** [comment]
LockWidgets works fine with 1.3.2. If you have issues provide *all* information needed.
