### ISSUE TITLE
SafeMode Issue with LockWidgets on 1.3.2

### ISSUE THREAD

**Issue by vpww** [himynameisubik/Kalm-support#44]
**Packix Username:***
vpww

**Describe the bug**
After update and respring kalm to 1.3.1 and 1.3.2 i get safemode

**How to reproduce**
1. open cydia
2. update kalm to 1.3.2
3. respring
4. get safemode
5. disable kalm with icleaner - no safemode

**Expected behavior**
no safemode :)

**Screenshots**
https://drive.google.com/file/d/1MafROnB-NiIv7mN_3cJ7zYcdljpX3e3R/view?usp=sharing

**iOS Version:**
13.3

**Device:**
11 pro max

**Device language:**
Russian

**Tweak list:**
https://pastebin.com/z60gv4JR

**Crashlog:**
https://pastebin.com/Dwd5G2AL

**Additional context:**
i disabled all tweaks one by one to see which one conflicts, found the curlpit - lockwidgets, safemode happens when both are enabled and other tweaks are disabled:
https://pastebin.com/RSc25zLS
https://drive.google.com/file/d/1aXBm_4wiaYFOS8b7-2XyS7ficyd0jmgH/view?usp=sharing

**Comment by himynameisubik** [comment]
What widget are you using in LockWidgets?

**Comment by vpww** [comment]
com.apple.weather.WeatherAppTodayWidget
com.apple.BatteryCenter.BatteryWidget
com.apple.Music.RecentlyPlayedTodayExtension
ru.yandex.rasp.today - by this app https://apps.apple.com/ru/app/id387272416

**Comment by himynameisubik** [comment]
Can you test if it happens if you disable some? It works fine for me with WeatherApp and Battery

**Comment by himynameisubik** [comment]
Also, did you try these steps:
https://github.com/himynameisubik/Kalm-support#this-is-the-only-official-place-for-kalm-bug-reports-and-feature-requests

**Comment by vpww** [comment]
> Also, did you try these steps:
> https://github.com/himynameisubik/Kalm-support#this-is-the-only-official-place-for-kalm-bug-reports-and-feature-requests

yes, i tried all steps with no luck

with lockwidgets i restored default preferencies and reinstalled it - same no luck(

**Comment by himynameisubik** [comment]
Just enable 1 widget and not more. It works fine on both my iOS13 devices and many others. Might be something else that is conflicting. Disable everything but Kalm and LockWidgets

**Comment by vpww** [comment]
> Just enable 1 widget and not more. It works fine on both my iOS13 devices and many others. Might be something else that is conflicting. Disable everything but Kalm and LockWidgets

i have only battery widget active in lockwidgets
switched to default settings in kalm
only kalm and lockwidgets are enabled in icleaner
still same problem...

**Comment by himynameisubik** [comment]
Hmm, can you create a crashlog with Cr4shed please?

**Comment by vpww** [comment]
> Hmm, can you create a crashlog with Cr4shed please?

if its problem with lockwidgets - maybe i should send this crashlog to Conor?

**Comment by himynameisubik** [comment]
Yes. Closing

**Comment by vpww** [comment]
fyi: last update of lockwidgets (v2.0) fixes that problem for me, both tweaks work without any problem

**Comment by himynameisubik** [comment]
Thanks for the update!
