### ISSUE TITLE
Apple Maps lockscreen bug

### ISSUE THREAD

**Issue by ratohnhake** [himynameisubik/Kalm-support#47]
**Packix Username:**
Your Packix username

**Installed version:**
Current version of Kalm1.3.2

**Describe the bug**
The lockscreen stays black when I use apple Maps. I can swipe up to go on homescreen. But the lockscreen itself stays black.
No Problem when I deactivate Kalm throw icleaner

**How to reproduce**
1. Go to '...' route with apple maps
2. Click on '....' lock the screen see the error

**Expected behavior**

**Screenshots**

**iOS Version:** 13.3

**Device:** pro max

**Device language:** german

**Tweak list:**
Put it on www.pastebin.com
Other lockscreen tweaks: lisa dots

**Crashlog:**
Put it on www.pastebin.com

**Additional context:**
Add any other context about the problem

**Comment by himynameisubik** [comment]
Did you disable all other tweaks and try it again? Works fine here and shows the map/directions.

**Comment by himynameisubik** [comment]
Also provide your Packix Username. Thank you.

**Comment by ratohnhake** [comment]
Username : ratohnhake

The problem is with Lisa I think. maybe it conflicts.
 Unfortunately I have no issues when I disable Kalm

**Comment by himynameisubik** [comment]
Try without Lisa. If the issue still occurs please contact the dev of Lisa. I can't help you with that issue, sorry.
