### ISSUE TITLE
Apply saturation & brightness settings when using Colorflow Colors

### ISSUE THREAD

**Issue by p2kdev** [himynameisubik/Kalm-support#48]
**Packix Username:***
patilkiran08

**Request:**
For some tracks the colors are such that the Date Time labels are not legible. Hence, requesting you to apply the same saturation/brightness settings which are used for Wallpaper Colors as it will make it consistent & more legible

See below for a few screenshots of what I am talking about
![image](https://user-images.githubusercontent.com/51972743/76566495-e6409000-647a-11ea-9752-004542355b24.png)

![image](https://user-images.githubusercontent.com/51972743/76566513-f0628e80-647a-11ea-9214-67bda610bce0.png)

**Comment by himynameisubik** [comment]
This would also happen if you are using Artsy/ColorFlow without Kalm, no?

**Comment by p2kdev** [comment]
I am not sure about artsy but Colorflow will use a legible combination of BackGround/Text Colors for the music widget & hence it works. 
![image](https://user-images.githubusercontent.com/51972743/76564938-93b1a480-6477-11ea-9576-301b57fb667d.png)
![image](https://user-images.githubusercontent.com/51972743/76564966-a035fd00-6477-11ea-8b7f-f75b1cefcafc.png)


Whereas the date time labels are shown on the usual lockscreen wallpaper & their is no guarantee that the text will be still legible!

**Comment by himynameisubik** [comment]
I'm talking about the time and date are those not colored by CF and Artsy?

**Comment by p2kdev** [comment]
Not to my knowledge atleast by colorflow. Not used artsy personally

**Comment by himynameisubik** [comment]
Ah I see, I'll look into it

**Comment by himynameisubik** [comment]
This option is not useful since if you are using the option to show the album art as wallpaper this would also interefere with that option. I suggest you not to use third party coloring.
