### ISSUE TITLE
Feature request: color lockscreen status bar icons to match kalm

### ISSUE THREAD

**Issue by e-simpson** [himynameisubik/Kalm-support#52]
**Request:**

Color the status icons on the lockscreen to match the text colour applied by Kalm for aesthetic purposes.

**Comment by himynameisubik** [comment]
Not sure if I ever want to touch the statusbar again. Putting this on hold.

**Comment by e-simpson** [comment]
Thanks for the response. Alternatively, the ability to hide the status icons on the lockscreen would provide a solution

**Comment by e-simpson** [comment]
Apologies - I closed the issue by accident! Darn mobile-site 😂. Thanks for the response.

**Comment by CySxL** [comment]
Wait for this nice feature soooo long 🤣

**Comment by CySxL** [comment]
Hi! May I ask why this issue is closed ?
Because I didn't find this request being implemented in version 3.0.0 tho.

**Comment by himynameisubik** [comment]
Feature requests are closed for now as I don't have the time currently to work on even more features: https://github.com/himynameisubik/Kalm-support/issues/230
