### ISSUE TITLE
Feature request: Different Coloring of Lables

### ISSUE THREAD

**Issue by blackkbraddpitt** [himynameisubik/Kalm-support#55]
Love the tweak, I have no bugs or anything, I just have a request.

When enabling the colorizing of all lables, it does just as it says, but I think there should be a primary and secondary color i.e;

Weather [Primary Tint/Custom Color]
Time [Secondary Tint/Custom Color]
Date [Primary Tint/Custom Color] 
Up Next [Secondary Tint/Custom Color]
Calendar Event [Primary Color/Custom Color]

This would also help having a sense of unison to ColorFlow as it has two different colors of text. I understand you can un-colorise these parts, but the white text with a white background is hard to see!

Apologies for the way this post is laid out, it's the only way I could think of it.

**Comment by himynameisubik** [comment]
Thanks! I'll check if it's feasible to do that. Not sure if this will be added anytime soon tho.

**Comment by blackkbraddpitt** [comment]
Thanks for your response!
Not a problem, I figured I may as well ask. There’s a tweak from iOS 12 called Fabric by Creature Survive that had it this way, although I’m not sure if it’s open-sourced.

**Comment by himynameisubik** [comment]
Oh, it's not that it's a problem, but it'll require restructuring of the whole colors settings and change a lot of things. And possibly breaks the general look of Kalm.

**Comment by blackkbraddpitt** [comment]
Ooft. Sounds daunting, maybe one day. (;
Nah I’m just kidding, take care and thanks for listening!

**Comment by himynameisubik** [comment]
You too, thanks for understanding! Stay safe!

**Comment by himynameisubik** [comment]
Custom colors with a Colorpicker will be added with libSparkColourPicker. But two different colors – besides iOS Primary (white/black) + Kalm Color – will not be added.
