### ISSUE TITLE
Up Next items not appearing 

### ISSUE THREAD

**Issue by KoreanSeats** [himynameisubik/Kalm-support#57]
**Packix Username:**
KoreanSeats

**Installed version:**
1.3.3

**Jailbreak:**
Unc0ver 13.3

**Describe the bug**
When updated from 1.3.2 to 1.3.3 , the up next items disappear. I’ve tried the troubleshooting items on the Kalm Depiction page, including obvious reinstalls or enable / disable etc. 

**How to reproduce**
1. Update from 1.3.2 to 1.3.3
2. Up Next Items dissapear

**Expected behavior**
I would expect the items to appear or be there as they were before. No other items or tweaks had changed. 

**Screenshots**
Everything else looks great, just missing the Up Next now. No screenshot needed I don’t think

**iOS Version:**
13.3

**Device:**
iPhone 11 Pro Max

**Device language:**
English (USA)

**Tweak list:**
https://pastebin.com/TUu3DDAa

**Crashlog:**
Put it on www.pastebin.com

**Additional context:**
Add any other context about the problem

**Comment by himynameisubik** [comment]
Did you adjust "Time ahead" in Up Next settings?

**Comment by himynameisubik** [comment]
No further info provided
