### ISSUE TITLE
Seconds don't update properly when added to a Custom Time Format

### ISSUE THREAD

**Issue by connervieira** [himynameisubik/Kalm-support#59]
**Packix Username:**
vieirast

**Installed version:**
9.3.1

**Jailbreak:**
checkra1n

**Describe the bug**
When a custom time format including seconds is used, Kalm only updates the seconds when the lock screen/notification center is first displayed. In other words, the seconds don't move. They are loaded once when the view is first show, then aren't reloaded again until the minutes field refreshes.

**How to reproduce**
1. Open Kalm settings
2. Click "Date formats"
3. Enable "Custom Time Format"
4. In the "Format:" field, enter "HH:mm:ss"
5. Apply changes and re-spring
6. Observe that the seconds don't refresh properly

**Expected behavior**
It is expected that the seconds will update every second, as opposed to every minute.

**iOS Version:**
iOS 13.3.1

**Device:**
iPhone 7

**Device language:**
English

**Comment by himynameisubik** [comment]
Seconds (:ss) are not supported to be updated every second. This would lead to battery drain. You can accomplish that with other tweaks.
