### ISSUE TITLE
Multiple events

### ISSUE THREAD

**Issue by chatintok** [himynameisubik/Kalm-support#6]
If there are multiple events on my calendar today, only one of them shows.
It would be nice to show all the days If more than one event will take place.
Just like as the image below.
Thanks.

![image](https://user-images.githubusercontent.com/60657069/73750385-21f68480-476e-11ea-812f-08a17c03f67f.png)

**Comment by himynameisubik** [comment]
Thanks for the request, I have something similar already planned that will allow you to show 1-5 events.
