### ISSUE TITLE
Respring freeze with Weather enabled

### ISSUE THREAD

**Issue by himynameisubik** [himynameisubik/Kalm-support#60]
> Device: iPhone X
> iOS version: 13.4
> Jailbroken with checkra1n 0.9.9
> Kalm version: 1.3.3
> 
> I did quite a lot of testing, which required me to re-jailbreak my phone after every crash, and now I isolated the problem on my device:
> 
> Whenever I enable the weather feature in Kalm, my phone will freeze during any respring. If I then reboot it and re-jailbreak it then everything works again, even the weather feature of Kalm then successfully works. However, as long as I keep that feature enabled, my phone will keep on freezing whenever it needs to respring. Yes I've added a manual location in the Weather app and yes I've tried to reinstall the weather app, neither of those solutions worked. So for now I've just disabled the weather feature and now it doesn't freeze anymore during resprings.
> 
> Also I have installed cr4shed, but it hasn't recorded any crash unfortunately.

By @Evertt in #26

**Comment by himynameisubik** [comment]
**Packix Username:**
Your Packix username

**Device language:**

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Additional context:**
Add any other context about the problem

**Comment by himynameisubik** [comment]
Could you also try out Kalm 1.0.0?

**Comment by Evertt** [comment]
> Could you also try out Kalm 1.0.0?

Meh, I've reached the maximum amount of effort I'm willing to put into this. 😅

I'm okay with living without the weather feature for now. Also, me reporting this bug is not meant as "fix this now!", it's just meant as "hey I heard you like receiving this kind of info, so here's a little info from me, I hope it helps".

**Comment by himynameisubik** [comment]
> > Could you also try out Kalm 1.0.0?
> 
> Meh, I've reached the maximum amount of effort I'm willing to put into this. 😅
> 
> I'm okay with living without the weather feature for now. Also, me reporting this bug is not meant as "fix this now!", it's just meant as "hey I heard you like receiving this kind of info, so here's a little info from me, I hope it helps".

No worries! Wasn't taken like that :) Just wanted to fix your issue. Sorry if it's not working. Really don't know what it might be. Closing this for now.
