### ISSUE TITLE
Feature request: Select Calendars: group calendars by account

### ISSUE THREAD

**Issue by hnlkaitan** [himynameisubik/Kalm-support#64]
My personal and school emails have similarly-named calendars, and it'd be nice to be able to see exactly which calendars belong to which account (and others, like iCloud and the like). I understand COIVD-19 has everyone's hands tied but just thought I'd throw this out here before I forget!

**Comment by himynameisubik** [comment]
You mean in Settings?

**Comment by himynameisubik** [comment]
Also, please provide your Packix username.

**Comment by hnlkaitan** [comment]
Yes, in settings. Packix username: hnlkaitan

**Comment by himynameisubik** [comment]
I think the object I'm getting does not have the information needed for that grouping. Anyway, All right, I'll look into it when I got some time. Enhancements are on hold at the moment.

**Comment by hnlkaitan** [comment]
No worries, thanks for keeping me updated! Stay safe!

**Comment by himynameisubik** [comment]
This was added in 2.2.0
