### ISSUE TITLE
Bug: Widget page on iPad cuts off at bottom with custom notification padding

### ISSUE THREAD

**Issue by allendude51** [himynameisubik/Kalm-support#65]
Love the tweak but I ran into an issue on my iPad air on 12.4.6.

When I have a had a custom setting for custom notification padding(the value was a negative number), the widget page on the lockscreen displays a gap at the bottom that cuts the widgets off. I turned off the custom notification padding setting and the issue when away, but I'd like to have a custom setting without having this gap there.
![18E9B802-6712-447B-ADF0-B865A23334DD](https://user-images.githubusercontent.com/51012842/79185263-08139680-7ddc-11ea-9cb0-845beae44f98.jpeg)

**Comment by himynameisubik** [comment]
Please report a bug with the "bug report" template 
https://github.com/himynameisubik/Kalm-support/issues/new/choose
