### ISSUE TITLE
Clock moving up and down randomly.

### ISSUE THREAD

**Issue by yonigold1** [himynameisubik/Kalm-support#67]
General information:
===

**Kalm version:**
1.34

**Kalm preferences file:**
https://pastebin.com/FwNAnic3

Device information:
===

**iOS version and language:**
iOS 13.3
**Device:**
iPhone 8 Plus
**Jailbreak:**
Unc0ver 

Bug description:
===

**Describe the bug:**
The clock constantly moves up or down (basically will not stay in the given position) 
**How to reproduce:**

Steps to reproduce the behaviour:
Unknown how to reproduce it happens randomly

**Expected behavior:**
The clock will move up a noticeable amount or the clock will move far down

**Screenshots:**
VIDEO of it happening [video](https://imgur.com/gallery/PJIRKtQ) 

![7916D626-15A0-47E9-AA80-08CC4C5F46F5](https://user-images.githubusercontent.com/34217684/79493984-3d90cd80-7ff0-11ea-9c5b-fe247c7c1c96.jpeg)

![B13A82CE-1E65-448C-990E-549552B3AA9B](https://user-images.githubusercontent.com/34217684/79494055-6022e680-7ff0-11ea-9b62-77fc5ebe9650.jpeg)

**Comment by himynameisubik** [comment]
Tweak list please. And does it also happen with all other tweaks disabled?

**Comment by yonigold1** [comment]
sorry for the super late reply but it does occur with all other tweaks disabled

**Comment by himynameisubik** [comment]
Would need some kind of info how it happens as this was fixed in 1.3.4 for the other people that had this issue. And it doesn't happen for me at all.

**Comment by yonigold1** [comment]
Ok so i have been extensively debugging trying to figure out what what has been causing the clock to move up but so far it has occurred when all tweaks are disabled and i have been playing around trying to figure out what it is so i figured out that when im using Kalm and i have the up next section disabled and a few other small modifications that the clock tends to move up and down i have no clue why though i followed the other issue tab and saw that up next interval needs to be set to always or something so ive followed that (even tho up next is disabled cause i dont need it). So to be honest im kinda stumped the last thing i could do is play around with the preferences and see if its caused by a certain setting but other than that i have no clue what to do now as i have done everything suggested and idk what else to do ☹️ and i really dont want to stop using Kalm because i love it and it has **everything** i want for my lockscreen 😩. 

Im going to attach my the preference file (and my tweak list) so you can see the settings i have and try to set yours to them to see if you can reproduce but yea i hope that we can figure it out because i truly do love Kalm! 
[KalmPrefs.zip](https://github.com/himynameisubik/Kalm-support/files/4548486/KalmPrefs.zip)
[Tweaks.pdf](https://github.com/himynameisubik/Kalm-support/files/4548543/Tweaks.pdf)

**Comment by himynameisubik** [comment]
Oh, could you try enabling up next just for some time and try if it happens too?

**Comment by yonigold1** [comment]
sure however i dont know how long it could take for the issue to show up again so ill post as soon as i have an answer

**Comment by himynameisubik** [comment]
Sure, no worries. Just the only thing I'm seeing that might cause this. But again, this was fixed in 1.3.4 for everyone else, so I assume something else. But idk right now.

**Comment by yonigold1** [comment]
Hey Happy Saturday! :) So far it hasn’t occurred once with up next enabled! I have a question and i’m not sure if this would do anything but perhaps it might (i’m a noob with how tweaks or development of stuff like this works) but maybe try creating a version of kalm for me to test that has everything up next related removed i’m not sure if that would do anything (and lmk if that’s the stupidest thing u have ever heard 😂😂) but i guess it’s worth a shot.

**Comment by himynameisubik** [comment]
Should be fixed in the upcoming 1.4.0 version.
