### ISSUE TITLE
Notifications cut off on the bottom

### ISSUE THREAD

**Issue by ratohnhake** [himynameisubik/Kalm-support#69]
**Packix username: ratohnhake

**Kalm version: 1.3.4

**iOS version and language:** 13.3 german
11 pro max

Bug description:
You aren’t be able to scroll down to the bottom.
The homebar overlapping the notification.
It works perfectly with previous versions of Kalm 1.3.3 and below (I tested)

**How to reproduce:** When you get more then 8 notification
 Here are two pictures, one with the newest version of kalm and one with previous version

**Screenshots:**
![01F1413A-DC00-475C-88A6-C19E0F5ADF09](https://user-images.githubusercontent.com/62110831/79779689-0ea19100-833b-11ea-91b1-37bae69675d8.png)
![619F10E4-84B7-4F1E-BB41-CF16D16558A8](https://user-images.githubusercontent.com/62110831/79779721-1c571680-833b-11ea-828a-0adb20cd85fc.png)

**Comment by himynameisubik** [comment]
Should be fixed with the next update.

**Comment by juliencampy** [comment]
Any news about this fix? I read that it is planned to be released in 1.4.0 but I am having a hard time using kalm in the meantime, especially when the music player is displayed, I really cannot scroll at all :(
Thanks for your hard work!

**Comment by himynameisubik** [comment]
Sorry for the dealy, it's still in progress as there was a lot more added to 1.4.0. I hope you understand.
