### ISSUE TITLE
Feature request: Option to hide "Up Next" during set times

### ISSUE THREAD

**Issue by Whiteberrie** [himynameisubik/Kalm-support#7]
Option to hide "Up Next" during set times, for example I dont want to see "Up Next" when I'm not at work without having to manually disable it. 

Love the tweak!

**Comment by himynameisubik** [comment]
Thanks!

Good idea, I'll take it on my list but can't give an ETA.

**Comment by Whiteberrie** [comment]
Adding on to this - option to choose which days "Up Next" should be visible, me for example would only want it to be visible on weekdays.

**Comment by himynameisubik** [comment]
@Whiteberrie : I know this took some time, but here's a little preview: https://twitter.com/himynameisubik/status/1232028619343585283

**Comment by himynameisubik** [comment]
Added in 1.3.0. Submitted to Packix.
