### ISSUE TITLE
DND icon related overnight SpringBoard crash (iOS12)

### ISSUE THREAD

**Issue by gkeep** [himynameisubik/Kalm-support#70]
General information:
===

**Packix username:**
discord.184996189677158401

**Kalm version:**
1.3.4

**Kalm preferences file:**
https://pastebin.com/PkCQVfMy

Device information:
===

**iOS version and language:** 12.4.6, English

**Device:** 5s

**Jailbreak:** checkra1n

Bug description:
===

**Describe the bug:**
SpringBoard crashes during night DND time span (hence possibly DND icon related), but I'm not 100% sure. For now, I've disabled DND icon and will update the issue/add a comment if its the icon that triggers it.

**Crashlog:**
https://pastebin.com/SjEDxHWt

**Comment by himynameisubik** [comment]
Thanks for the report. Let me know if this happens again. Afaik it's a iOS 12 only issue.

**Comment by gkeep** [comment]
Yup, no crashes overnight with DND icon off. Looks like that's the problem. I can live without it, but could you look into this?

**Comment by himynameisubik** [comment]
I'll check it out, but can't promise any ETA.

**Comment by gkeep** [comment]
Hmm... I left the DND icon on for the last few days, but had no crashes overnight. Maybe the crashes were random or a different tweak crashed?

Anyway, I think I'll close the issue, since I don't experience the crashes anymore (will reopen if they reappear!).

**Comment by himynameisubik** [comment]
That's really weird, thanks for the update tho! Kinda busy atm couldn't really find anything on Kalm's end that could be it. But just let me know when it occurs again. Stay safe!

**Comment by gkeep** [comment]
Quick update. I think I've found the cause of crashes.

Kalm automatically hides the DND banner, right? Well, I had a [specific tweak](https://repo.packix.com/package/com.mrgcgamer.nodndbanner/) installed that did exactly that.

I think what happened is NoDNDBanner removed the DND banner, *but* Kalm tried to remove it too. Yet it did not "exist" already, so SpringBoard lost its mind and crashed.

You should add it NoDNDBanner to list of conflicting tweaks.

Stay safe!
