### ISSUE TITLE
Feature request: Third party color enhancement

### ISSUE THREAD

**Issue by CySxL** [himynameisubik/Kalm-support#72]
**Packix Username:***
Your Packix username
sxteven@gmail.com
(connect facebook)
**Request:**

1. Move the lockglyph icon from top to parallel with weather condition line (and reduce its size too) , in order to make more space from lockscreen.
(without the glyph just like JellyFish do, can make NextUp2 much more visible.)

2. Ability to set two independent override custom colors different from system light mode and dark mode. So that users with WallpaperLoader can set their color exactly compatible with their wallpaper.

3. Some little ColorFlow5 support.
Please make an option to make the Time
tinted and synced with the "second color" of ColorFlow5 using.

Due to I'm not familiar with uploading pictures here, please see some screenshots here in my twitter.  -->> https://twitter.com/cysxl/status/1255407368730546176?s=21

**Comment by CySxL** [comment]
![C4E0754C-1AF5-4196-9DC9-C9EC4B3CE290](https://user-images.githubusercontent.com/15531137/80573942-80f92c00-8a33-11ea-82f2-2a1d0faea34c.jpeg)

> @`
![8E0F6CCD-E673-4413-BFC7-F04F2D74E8FC](https://user-images.githubusercontent.com/15531137/80573960-88b8d080-8a33-11ea-89ab-5f592722adb8.jpeg)
![Uploading 54B8D17C-10DF-4943-83F8-95A2D275A555.jpeg…]()

`

**Comment by CySxL** [comment]
![D1E91943-7F27-4F74-BDC6-155654CCC912](https://user-images.githubusercontent.com/15531137/80574019-a25a1800-8a33-11ea-84e7-102073acf398.jpeg)

**Comment by himynameisubik** [comment]
Will look into it if it's feasible. No ETA.

**Comment by CySxL** [comment]
for more exact understanding
Here are some examples by JellyFish
![A6C3442E-CECE-450E-B98B-39023E43D237](https://user-images.githubusercontent.com/15531137/80784208-cf7f0580-8bae-11ea-92f4-8b4f23fa6b5b.jpeg)

**Comment by himynameisubik** [comment]
I know what you're requesting. But it's not planned atm.

**Comment by himynameisubik** [comment]
Third-party coloring will use secondary color of Artsy and Colorflow in 1.4.2.

**Comment by himynameisubik** [comment]
Please split the ticket up to separate requests if you have multiple requests.

**Comment by himynameisubik** [comment]
Added in 1.4.2.
