### ISSUE TITLE
AM/PM disappear

### ISSUE THREAD

**Issue by CySxL** [himynameisubik/Kalm-support#73]
General information:
===

**Packix username:**
sxteven@gmail.com
(connect facebook)

**Kalm version:**
1.3.4
**Kalm preferences file:**

https://pastebin.com/EqmwhEcd

File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
iOS13.3 / Taiwanese
**Device:**
iPhoneX
**Jailbreak:**
CheckRa1n

Bug description:
===
The AM/PM disappear while change song from AppleMusic/Spotify

**Describe the bug:**

**How to reproduce:**
Just Bring down the NC and change to next song with media control, it will suddenly disappear.

And if u re-launch NC again, it will show up again until you change to next song.

**Expected behavior:**

The AM/PM shall display as always.

**Screenshots:**
![7D2E10A2-E12D-4C26-B94A-FD63A02CA089](https://user-images.githubusercontent.com/15531137/80600284-bebf7a00-8a5e-11ea-985d-2f4dd58a5fad.png)

Additional information:
===
Tweaks on my lockscreen:
Grupi/Kalm/ColorFlow5/Lyricify/NextUp2/NiceBarX(iOS13)

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
No crash log

**Comment by himynameisubik** [comment]
Does this also happen with all other tweaks disabled?

**Comment by CySxL** [comment]
Still same after disabling all of those lockscreen relafed tweaks

![711CEC23-6FBE-4A40-978C-10B4DF09A6CF](https://user-images.githubusercontent.com/15531137/80912763-dace5e80-8d71-11ea-9281-b75f5c45cf15.png)

![A9CAF96D-D6E1-41F3-9288-C37D6A3D4AA3](https://user-images.githubusercontent.com/15531137/80912820-5d571e00-8d72-11ea-85d9-b00018ec77e8.png)

**Comment by himynameisubik** [comment]
> Does this also happen with **all** other tweaks disabled?

**Comment by CySxL** [comment]
yup
only Kalm and Substrate safe mode were enabled lol
![D2DCAC20-7330-4B16-BA75-F0E864988BFF](https://user-images.githubusercontent.com/15531137/80915721-b16bfd80-8d86-11ea-9b88-097e0085c4e7.png)

**Comment by himynameisubik** [comment]
That's really weird. I'll look into it, can't promise anything. As it does not seem to happen for me. Tested it with h:mm a in the last days.

**Comment by himynameisubik** [comment]
Just came to my mind, could you test if it happens if you align Kalm to the left?
