### ISSUE TITLE
notification padding in the wrong place

### ISSUE THREAD

**Issue by CySxL** [himynameisubik/Kalm-support#74]
General information:
===

**Packix username:**
sxteven@gmail.com
**Kalm version:**
version 1.3.4
**Kalm preferences file:**

https://pastebin.com/VUvL59eB

File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
iOS13.3, Taiwan
**Device:**
iPhoneX
**Jailbreak:**
Checkra1n

Bug description:
===

**Describe the bug:**
Sometimes swipe down NC, the notification padding would get lower than my setting, also pop up while playing music.

**How to reproduce:**
Randomly appears, but if u swipe down to the bottom of NC and don't release ur finger then swipe up NC, it will appear (hopes) again. 

**Expected behavior:**

Notification padding should be in the position where I set it for.

**Screenshots:**

Normal condition
![14EC4D04-A983-4F39-B11C-BB157DC06DB8](https://user-images.githubusercontent.com/15531137/80858934-92d70b00-8c8f-11ea-809b-ef4bd626215e.png)
:
![8DACE6F3-77C5-49DD-BE81-C4B06856385F](https://user-images.githubusercontent.com/15531137/80858928-85ba1c00-8c8f-11ea-981f-a3d66923555c.png)

Weird wrong position :
![4892D5A0-743E-46AA-AF8D-459258B18B3F](https://user-images.githubusercontent.com/15531137/80858947-aedaac80-8c8f-11ea-9c05-594619e38759.png)
![28F9359B-6D9F-48A3-95E2-B233CD810F2B](https://user-images.githubusercontent.com/15531137/80858953-bbf79b80-8c8f-11ea-8820-0f413c28942a.png)

As u can see, a bit of extra space show up between date and Grupi cell icon/album cover, and the NextUp2 even be cut off.
Additional information:
===

**Tweak list:**

Grupi/Kalm/NextUp2/ColorFlow5/ColorMeNotifs/NiceBarX/Lyricify on lockscreen

**Crashlog:**

No crash log present

**Comment by himynameisubik** [comment]
Does it happen with other tweaks disabled?

**Comment by CySxL** [comment]
I'll try, will let u know immediately/

**Comment by CySxL** [comment]
Yup, and I encountered this frequently, pretty annoying 
![56C9639E-5146-4EF3-A226-FF8773C77A65](https://user-images.githubusercontent.com/15531137/81155370-7270be80-8fb7-11ea-977d-f0d652b7df2f.png)
![75881768-538E-487F-980F-99F3A965C380](https://user-images.githubusercontent.com/15531137/81155424-82889e00-8fb7-11ea-82e0-1bf3ceccd7ae.png)

**Comment by himynameisubik** [comment]
I'll look into it, in the meantime try disabling custom position & notification padding.

**Comment by CySxL** [comment]
oKay. I'll try it and let u know

**Comment by CySxL** [comment]
![59855160-217D-4099-8F59-AE561D062F50](https://user-images.githubusercontent.com/15531137/81473374-93901400-9230-11ea-9ce9-ebc5085460f6.png)

Seems like it works all fine.
![A8AE6B20-26B2-44F5-A446-B12689C95FFD](https://user-images.githubusercontent.com/15531137/81473390-b1f60f80-9230-11ea-8d2d-15ada57fbc32.png)

**Comment by himynameisubik** [comment]
Linked with #67. Closing this. Will be fixed in next version.
