### ISSUE TITLE
Face ID hangs  when unlocking

### ISSUE THREAD

**Issue by Riohh** [himynameisubik/Kalm-support#77]
General information:
===

**Kalm version:**
1.3.4
**Kalm preferences file:**
https://pastebin.com/9x6MkgKu

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
iOS 13.3 English
**Device:**
iPhone X
**Jailbreak:**
Checkra1n

Bug description:
===

**Describe the bug:**
Unlocking the phone takes half a second longer when in the Face ID screen in the lock screen. 
**How to reproduce:**

Use the move clock option, respring, after some time the device will start to take longer to unlock when swiping up after waking the phone.

**Expected behavior:**
The device should take the same time to unlock like stock iOS

**Screenshots:**
A video explains the issue better:
https://imgur.com/a/1APjG41
As you can see, the first 3 tries are pretty fast but after that the bug happens and hangs in the Face ID prompt longer than usual.

Additional information:
===
I have found out that using the move clock up/down option seems to trigger this bug consistently, but I have also had it happen without using it. After the bug starts happening it doesn't get fixed unless disabling the move clock option, sometimes that doesn't fix it though.
**Tweak list:**
https://pastebin.com/5RssypsV

**Crashlog:**
No crash

**Comment by himynameisubik** [comment]
Does this happen without any other tweaks enabled (disable all tweaks in iCleaner)? I can lock & unlock my phone (iPhone X) 10 times without any slow down.

**Comment by Riohh** [comment]
> Does this happen without any other tweaks enabled (disable all tweaks in iCleaner)? I can lock & unlock my phone (iPhone X) 10 times without any slow down.

I did try it without any other tweaks and It would still happen, after reinstalling Kalm it doesn't seem to happen with Kalm alone, I'm trying now by enabling other tweaks one by one, I will reply after I'm done.

**Comment by Riohh** [comment]
> Does this happen without any other tweaks enabled (disable all tweaks in iCleaner)? I can lock & unlock my phone (iPhone X) 10 times without any slow down.

I think it conflicts with Latchkey, I tried only Kalm and Latchkey and the bug happens, with everything on except latchkey it does not happen. Specifically the move option in Latchkey, when using the default option it's all good. Maybe you can look into this? or is it something that the developer of Latchkey has to look into?

**Comment by himynameisubik** [comment]
Hmm, LatchKey and Kalm work fine together on my end. What options are you using? Please be specific. Might be something I or the dev of LatchKey have to look into. Don't know.

**Comment by himynameisubik** [comment]
No further information provided.
