### ISSUE TITLE
Crash when enabling DND and DND icon enabled (iOS12 only)

### ISSUE THREAD

**Issue by rkycyku** [himynameisubik/Kalm-support#78]
General information:
===

**Kalm version:**
1.3.4
**Kalm preferences file:**
https://pastebin.com/aPwxPuDC 

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
12.4.6 - Albanian
**Device:**
iPhone 6
**Jailbreak:**
Checkra1n

Bug description:
===

**Describe the bug:**
When enabling the DND the springboard crashes and puts my device o Safemode

**How to reproduce:**

1. Go to 'CC'
2. Click on 'DND button'
3. See error

**Expected behavior:**
The DND should be activated normal but it puts my device on safemode.

**Screenshots:**

Additional information:
===

**Tweak list:**
https://pastebin.com/Le8YaFci 

**Crashlog:**
https://pastebin.com/igrJvFJe

**Comment by himynameisubik** [comment]
It's related to the DND icon on iOS12. Please disable the DND icon. I'm looking into it.

**Comment by rkycyku** [comment]
Okay, i hope you fix it.

**Comment by himynameisubik** [comment]
Should be fixed in the next version.
