### ISSUE TITLE
Non-native calendar support

### ISSUE THREAD

**Issue by tdubwv** [himynameisubik/Kalm-support#8]
Specifically, Outlook...

I’d really like to use my work calendar with Kalm, but my employer only allows our Outlook accounts to be used on the official Outlook app, so I can’t add it to my phone for use with the native calendar app (they somehow have it blocked from being added directly to an iPhone).

**Comment by himynameisubik** [comment]
Will look into it, but not a priority right now.

**Comment by himynameisubik** [comment]
Looked into it a bit but I won't be able to make it happen. Also not with the recent(?) Jailbreak Detection added by MS to Outlook. Sorry.
