### ISSUE TITLE
Jailbreak error 79 after restarting

### ISSUE THREAD

**Issue by hassan2x7** [himynameisubik/Kalm-support#80]
When downloading the kalm package and restarting the iPhone and the jailbreak procedure, error 79 comes, but when deleting the package this error does not come, use jailbreak checkra1n iPhone 7p version 13.3.1

**Comment by himynameisubik** [comment]
Did you try these steps?
https://github.com/himynameisubik/Kalm-support#general-steps-to-try-before-creating-an-issue

**Comment by himynameisubik** [comment]
No further information provided.
