### ISSUE TITLE
Feature request: Make banner animation smother when having events on "Up Next"

### ISSUE THREAD

**Issue by libertig** [himynameisubik/Kalm-support#81]
I noticed that when you have events displayed on the "Up Next" section and have some notification banners on the NS, when you open the NS the animation of banner going down is a little bit glitchy. It would be great to make the position static or when the banner is going down to make it a little more fluid.

Sometimes this animation doesn't happen, so I don't know if it's a bug or just the way it works.

Here's an example: https://drive.google.com/file/d/1gImrxNoIHdlEVv5AEfix2wCIIeVumml8/

**Comment by himynameisubik** [comment]
Unfortunately the animation is coming from iOS itself as it adjusts the position of it more than with stock clock only. Can't do much about this. Sorry.
