### ISSUE TITLE
Safe mode after install and respring

### ISSUE THREAD

**Issue by cyberrastaflyte** [himynameisubik/Kalm-support#83]
I have an Iphone 6s with Ios 13.5 and Checkra1n jailbreak. After installation of Kalm and respring, the device goes to safe mode. I restarted, reinstalled the app, used icleaner and it doesn't solve this.
![FCF72EA1-AD9F-431A-8952-2100E8E5A5A9](https://user-images.githubusercontent.com/65843042/82746465-274bff00-9d5e-11ea-818a-0128d786cdb7.png)

**Comment by himynameisubik** [comment]
Please open a ticket with the provided template.
