### ISSUE TITLE
Battery % not aligned when showing after unlock

### ISSUE THREAD

**Issue by imfaridhasan** [himynameisubik/Kalm-support#84]
please fix this visual bug make text alignment to right position 
when battery show xx% Charged this text appears when unlocking the phone while charging 
![9D9671E3-0E14-4B1A-9E48-FF72952A8AD1](https://user-images.githubusercontent.com/32639695/82749429-64060d80-9dd3-11ea-9885-8eecfd829c05.png)

**Comment by himynameisubik** [comment]
Issue will be fixed with the next update. Please use the provided template to report issues next time.
