### ISSUE TITLE
Colors don’t change with dark/light mode change

### ISSUE THREAD

**Issue by Swordee** [himynameisubik/Kalm-support#85]
General information:
===

**Kalm version:**
1.3.4

**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
13.5, English

**Device:**
iPhone XS Max

**Jailbreak:**
unc0ver v5.0.0

Bug description:
===

**Describe the bug:**
Change your phone theme, the colors don’t change with the wallpaper update.

**How to reproduce:**

1. Switch phone theme
2. View lock screen 

**Expected behavior:**
Colors are not updated to fit the wallpaper change. May be hard to see text.

**Screenshots:**

Additional information:
===

**Tweak list:**
https://pastebin.com/R3FDuxnH

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Please provide an example.

**Comment by Swordee** [comment]
I feel really bad doing this, but I’d like to request a refund. I just bought Quart, which also changes the lock screen. I read your refund policy, and chance my mind decisions are allowed within 24 hours, I hope you accept this :). I can still provide a screenshot of the bug, if you’re interested.

**Comment by ZacBytes** [comment]
I’m experiencing this issue too, its stuck on purple. iPhone XR 13.5 Unc0ver 5.0.0

**Comment by himynameisubik** [comment]
This issue will be fixed with the next update of Kalm. If you want a refund request it via your Chariz Dashboard.

**Comment by Swordee** [comment]
I’ll keep it, thanks for fixing the issue!
