### ISSUE TITLE
Bootloop when stock calendar app not installed

### ISSUE THREAD

**Issue by ZacBytes** [himynameisubik/Kalm-support#86]
General information:
===

**Kalm version: 1.3.4**

(Cant send preferences file because enabling the calendar pref will crash me)

Device information:
===

**iOS version and language:**
iOS 13.5 English

**Device:**
iPhone XR

**Jailbreak:**
Unc0ver 5.0.0

Bug description:
===

**Describe the bug:**
When you delete the stock calendar app and enable calendar in Up Next in Kalm settings, respringing will cause bootloop.

**How to reproduce:**

1. Delete stock calendar app
2. Enable Calendar events in Up Next in Kalm Settings
3. Apply & Respring

**Expected behavior:**
Bootloop

**Comment by himynameisubik** [comment]
Having the stock Calendar app is a requirement.

**Comment by ZacBytes** [comment]
yeah but shouldn't the tweak prevent you from enabling that option to prevent boot looping someone

**Comment by himynameisubik** [comment]
It's not a bootloop. But I'll look into disabling that option if calendar is not installed.
