### ISSUE TITLE
[Conflict with LowPowerDND] Enabling DND crashes on 13.5

### ISSUE THREAD

**Issue by zibo29** [himynameisubik/Kalm-support#87]
General information:
===

**Kalm version:**
1.3.4
**crash log**
https://pastebin.com/fhuPNLV9
**Kalm plist config**
https://pastebin.com/U9RkRMse
Device information:
===

**iOS version and language:**
13.5
**Device:**
iPhone X
**Jailbreak:**
Checkra1n 

Bug description:
===
Enabling and disabling DND from LS CC make springboard crash (happening 7 times o out of 10)
**Describe the bug:**
I also have LowpowerDND but I don’t think it’s related.

**to 
**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Can you please try disabling other tweaks? It doesn't happen on my end and I can toggle it 10+ times in a row without a problem. And I'm also running an iPhone X with 13.5 on checkra1n.

**Comment by zibo29** [comment]
> Can you please try disabling other tweaks? It doesn't happen on my end and I can toggle it 10+ times in a row without a problem. And I'm also running an iPhone X with 13.5 on checkra1n.

Just tested, it is some incompatibility between Kalm and LowpowerDND - I can use both individually with no problem but when active together I have a crash rate of 7/10 or above - I’m already in contact with the dev of LowpowerDND but I don’t know who has to fix what - sorry for that

**Comment by himynameisubik** [comment]
Probably needs to be something he needs to do, but tell him to contact me if he needs anything. Afaik I'm using the standard method of detecting if DND is active.

**Comment by zibo29** [comment]
Thanks! I'll forwarded your message to the dev of LowpowerDND, anyway this wasn't happening on 13.4 so maybe something has changed

**Comment by himynameisubik** [comment]
All right, thanks @zibo29!

**Comment by himynameisubik** [comment]
Any update on this @zibo29 ?

**Comment by zibo29** [comment]
I really don’t know what’s changed but with Kalm 1.4.x the problem is solved. (Gets back if I downgrade to 1.3)

**Comment by zibo29** [comment]
(The dev stated no issues on his end)

**Comment by himynameisubik** [comment]
That's weird, but great if it works now though. Thanks for the update!
