### ISSUE TITLE
animation bug when pulling down notification center

### ISSUE THREAD

**Issue by imfaridhasan** [himynameisubik/Kalm-support#88]
General information:
===

**Kalm version:** 1.3.4

**Kalm preferences file:** https://pastebin.com/8J9Seadn

Device information:
===

**iOS version and language:** 13.4.1

**Device:** iPhone 7

**Jailbreak:** unc0ver 5.0.1

Bug description:
===

**Describe the bug:**
Visual animation glitch on notifications while pulling down notification center.

**How to reproduce:**

1. Up Next must be “enabled”
2. Pull down notification center slowly

**Expected behavior:**
Notifications cards shows glitchy animation like suddenly little bit down after pulling down notification center, here i attach the video when the glitch occur vs not, hopefully you see the difference.

**Screenshots:** https://imgur.com/gallery/oeWMHhd

Additional information:
===

**Tweak list:** https://pastebin.com/LT83YRXR

**Crashlog:** none

**Comment by himynameisubik** [comment]
This can happen since the view needs to update the position of the notifications. Sorry for the inconvenience, but this can't be fixed at this time.
