### ISSUE TITLE
Lock alignment

### ISSUE THREAD

**Issue by tVance20** [himynameisubik/Kalm-support#9]
I am running 13.2.3 on an iPhone X. The initial release of this tweak was fine. Once I went to update tweak the lock icon immediately started to overlap with the weather band conditions. It also removes the calendar when you go to put reminders in next up.

![94AFBC0D-CBB1-431A-8088-2A5644C4EDBF](https://user-images.githubusercontent.com/51184313/73843627-9a982800-47e4-11ea-9244-59c33e703c23.png)

**Comment by himynameisubik** [comment]
Hi there, sorry for the inconvenience, please follow the template of submitting an issue. Also try to disable all other tweaks in iCleaner except Kalm and try if this fixes the issue. It might be a conflicting tweak.

**Comment by himynameisubik** [comment]
Closing this since no new info was provided.
