### ISSUE TITLE
Crash on respring

### ISSUE THREAD

**Issue by DeVaulted** [himynameisubik/Kalm-support#92]
For some reason Kalm hard crashes my phone when I respring. Only booting into jail broken mode without loading tweaks & deleting the plist files & reinstalling the tweak helps. 

//edit: this happens every time.

**Steps to reproduce:**
1.) Install & setup the tweak
2.) Respring for any reason

**Installed Tweaks:**
AppList (applist) v1.5.16 by Ryan Petrich  via BigBoss
APT (apt) v1.8.2-3 by Unknown via Bingner/Elucubratus
APT (apt-key) (apt-key) v1.8.2-1 by Unknown via Bingner/Elucubratus
APT 1.4 Transitional (apt1.4) v1:0 by Unknown via Bingner/Elucubratus
Base Structure (base) v1-5 by Unknown via Bingner/Elucubratus
Bourne-Again SHell (bash) v5.0.3-2 by Unknown via Bingner/Elucubratus
Berkeley DB (berkeleydb) v6.2.32-1 by Unknown via Bingner/Elucubratus
tweakCompatible (bz.jed.tweakcompatible) v0.1.5 by treAson  via BigBoss
bzip2 (bzip2) v1.0.6-1 by Unknown via Bingner/Elucubratus
CA Certs (ca-certificates) v0.0.2 by Unknown via Bingner/Elucubratus
ipadify (codes.rambo.ipadify) v0.0.3 by Guilherme Rambo via Packix
AppStore++ (com.cokepokes.appstoreplusplus) v0.9.10 by CokePokes via Phantom Apps LLC 
libnotifications (com.cokepokes.libnotifications) v0.2-4 by CokePokes  via BigBoss
Scorpion (com.esquilli.scorpion) v1.4.1 by Unknown via Dynastic Repo
Substitute (com.ex.substitute) v0.1.13 by comex  via Bingner/Elucubratus
iCleaner Pro (com.exile90.icleanerpro) v7.8.2 by Ivano Bilenchi  via Karen/あけみ's Repo
Dayn (com.jannikcrack.devvix.dayn) v1.0 by Devvix, JannikCrack  via Chariz
Locale Profiles in UTF-8 (com.linusyang.localeutf8) v1.0-1 by Linus Yang  via BigBoss
WiFi Passwords (com.malcolmhall.wifipasswords) v3.0.1 by Malcolm Hall  via BigBoss
ColorMeNotifs (com.mrgcgamer.colormenotifs) v1.4.2 by MrGcGamer via Packix
libMRYIPC (com.muirey03.libmryipc) v1.0 by Muirey03 via Dynastic Repo
CCSupport (com.opa334.ccsupport) v1.2.2 by opa334  via BigBoss
FiveDock13 (com.p2kdev.fivedock13) v1.0 by P2KDev  via Packix
Grupi (com.peterdev.grupi) v2.0 by Soongyu Kwon & Timeloop via Packix
RocketBootstrap (com.rpetrich.rocketbootstrap) v1.0.9 by Ryan Petrich  via rpetrich
HideLabels13 (com.ryannair05.hidelabels13) v1.0.0 by Ryan Nair via Packix
Liberty Lite (Beta) (com.ryleyangus.libertylite.beta) v0.2.12 by Ryley Angus via A repo for my tweaks
SwitchPatch (com.ryleyangus.switchpatch) v0.0.1 by Ryley Angus via A repo for my tweaks
Substrate Safe Mode (com.saurik.substrate.safemode) v0.9.6003 by Jay Freeman (saurik)  via Bingner/Elucubratus
BatteryPercentX (com.spark.batterypercentx) v1.4.1-33 by Spark via SparkDev
HideBarX (com.spark.hidebarx) v0.0.4 by Spark via SparkDev
libSparkAppList (com.spark.libsparkapplist) v1.0.9 by Spark via SparkDev
libsparkcolourpicker (com.spark.libsparkcolourpicker) v1.0.0 by Spark via SparkDev
LowBatteryBanner (com.spark.lowbatterybanner) v1.0.2 by Spark via SparkDev
Filza File Manager (com.tigisoftware.filza) v3.7.5-9 by TIGI Software  via BigBoss
NoClutter (com.twickd.quix.noclutter) v1.1.3 by Quix  via Twickd
Messenger ++ (com.unlimapps.fbmpp) v1.0r-68 by UnlimApps Inc. via UnlimApps
Instagram ++ (com.unlimapps.gramplus) v1.8r-327 by UnlimApps Inc.  via UnlimApps
Musical.ly ++ (com.unlimapps.musiclypp) v1.0r-22 by UnlimApps Inc.  via UnlimApps
Twitter ++ (com.unlimapps.twitterpp) v1.2r-82 by UnlimApps Inc  via UnlimApps
uasharedtools (com.unlimapps.uasharedtools) v2.2r-94 by UnlimApps Inc.  via UnlimApps
uasharedtools (iOS 11) (com.unlimapps.uasharedtools.nostash) v2.2r-94 by UnlimApps Inc.  via UnlimApps
YT ++ for YouTube (com.unlimapps.ytpp) v1.4r-106 by UnlimApps Inc  via UnlimApps
Core Utilities (coreutils) v8.31-1 by Unknown via Bingner/Elucubratus
Core Utilities (/bin) (coreutils-bin) v8.31-1 by Unknown via Bingner/Elucubratus
Cydia Installer (cydia) v1.1.33 by Jay Freeman (saurik)  via Bingner/Elucubratus
Cydia Translations (cydia-lproj) v1.1.32~b1 by Jay Freeman (saurik)  via Bingner/Elucubratus
Darwin Tools (darwintools) v1.1-1 by Unknown via Bingner/Elucubratus
Debian Utilities (debianutils) v4.8.6-1 by Unknown via Bingner/Elucubratus
Diff Utilities (diffutils) v3.6-1 by Unknown via Bingner/Elucubratus
diskdev-cmds (diskdev-cmds) v593.221.1-1 by Unknown via Bingner/Elucubratus
Debian Packager (dpkg) v1.19.7-1 by Unknown via Bingner/Elucubratus
Essential (essential) v0-2 by Unknown via Bingner/Elucubratus
file (file) v5.35-2 by Unknown via Bingner/Elucubratus
Find Utilities (findutils) v4.6.0-2 by Unknown via Bingner/Elucubratus
iPhone Firmware (/sbin) (firmware-sbin) v0-1 by Unknown via Bingner/Elucubratus
GNU Cryptography (gcrypt) v1.8.3-1 by Unknown via Bingner/Elucubratus
gettext (gettext) v0.19.8-1 by Unknown via Bingner/Elucubratus
GnuPG (gnupg) v2.2.11-2 by Unknown via Bingner/Elucubratus
GnuTLS (gnutls) v3.5.19-1 by Unknown via Bingner/Elucubratus
grep (grep) v3.1-1 by Unknown via Bingner/Elucubratus
gzip (gzip) v1.9-1 by Unknown via Bingner/Elucubratus
Kalm (hi.my.name.is.ubik.kalm) v1.3.4 by ubik  via Chariz
Launch Daemon Controller (launchctl) v23-1 by Unknown via Bingner/Elucubratus
Link Identity Editor (ldid) v2:2.1.2+g5420cb5-1 by Jay Freeman (saurik)  via Bingner/Elucubratus
APT Strict (lib) (libapt) v1.8.2-1 by Unknown via Bingner/Elucubratus
APT (libapt-pkg) (libapt-pkg5.0) v1.8.2-1 by Unknown via Bingner/Elucubratus
Assuan (libassuan) v2.5.1-1 by Unknown via Bingner/Elucubratus
GNU Multiple Precision Arithmetic Library (libgmp10) v6.1.2-1 by Unknown via Bingner/Elucubratus
GnuPG Errors (libgpg-error) v1.32-1 by Unknown via Bingner/Elucubratus
libidn2 (libidn2) v6.1.2-1 by Unknown via Bingner/Elucubratus
KSBA (libksba) v1.3.5-1 by Unknown via Bingner/Elucubratus
libplist (libplist) v2.0.0-2 by Unknown via Bingner/Elucubratus
OpenSSL 1.0 Libraries (libssl1.0) v1.0.2s-1 by Unknown via Bingner/Elucubratus
OpenSSL 1.1.1 Libraries (libssl1.1.1) v1.1.1c-1 by Unknown via Bingner/Elucubratus
libtasn1 (libtasn1) v4.13-1 by Unknown via Bingner/Elucubratus
libunistring (libunistring) v0.9.10-1 by Unknown via Bingner/Elucubratus
LZ4 (lz4) v1.7.5-1 by Unknown via Bingner/Elucubratus
LZMA Utils (lzma) v2:4.32.7-2 by Unknown via Bingner/Elucubratus
AirPods Case Low Battery (me.scenicjaguar101.tweak.airpodscaselowbattery) v1.0.0 by Unknown via Dynastic Repo
New Curses (ncurses) v6.1+20181013-1 by Unknown via Bingner/Elucubratus
New Curses (ncurses5-libs) v5.9-1 by Unknown via Bingner/Elucubratus
AppSync Unified (net.angelxwind.appsyncunified) v76.0 by Linus Yang, Karen/あけみ  via Karen/あけみ's Repo
KarenLocalizer (net.angelxwind.karenlocalizer) v1.0.5 by Karen/Akemi (angelXwind)  via BigBoss
KarenPrefs (net.angelxwind.karenprefs) v1.5 by Karen/Akemi  via BigBoss
mikoto (net.angelxwind.mikoto) v4.0.3 by Karen/あけみ (angelXwind)  via Karen/あけみ's Repo
PreferenceOrganizer 2 (net.angelxwind.preferenceorganizer2) v4.0.8 by Karen/あけみ  via Karen/あけみ's Repo
Nettle (nettle) v3.4.1-1 by Unknown via Bingner/Elucubratus
New GNU Portable Threads (npth) v1.6-1 by Unknown via Bingner/Elucubratus
OpenSSH (openssh) v8.1-1 by Unknown via Bingner/Elucubratus
BigBoss Icon Set (org.thebigboss.repo.icons) v1.0 by Unknown via Bingner/Elucubratus
p11-kit (p11-kit) v0.23.12-1 by Unknown via Bingner/Elucubratus
7-zip (POSIX) (p7zip) v16.02-1 by Unknown via Bingner/Elucubratus
PreferenceLoader (preferenceloader) v2.2.4 by Sam Bingner  via BigBoss
Profile Directory (profile.d) v0-1 by Unknown via Bingner/Elucubratus
readline (readline) v8.0-1 by Unknown via Bingner/Elucubratus
Unc0ver Policy Softener (science.xnu.substituted) v1.0.0 by pwn20wnd  via Local Repository
sed (sed) v4.5-1 by Unknown via Bingner/Elucubratus
shell-cmds (shell-cmds) v118-8 by Unknown via Bingner/Elucubratus
system-cmds (system-cmds) v790.30.1-2 by Unknown via Bingner/Elucubratus
Tape Archive (tar) v1.30-2 by Unknown via Bingner/Elucubratus
HideDots (tk.1di4r.hidedots11) v1.5 by 1di4r  via BigBoss
SSH Toggle and Port (u.blanxd.sshoncc) v1.3.5 by BlanxdH  via BigBoss
UIKit Tools (uikittools) v1.1.17-1 by Unknown via Bingner/Elucubratus
unrar (unrar) v5.6.4-1 by Unknown via Bingner/Elucubratus
unzip (unzip) v6.0+deb9u1-1 by Unknown via Bingner/Elucubratus
Utubed (utubed.ws) v1.0.8 by WS  via Packix
Alderis Color Picker (ws.hbang.alderis) v1.0 by HASHBANG Productions  via Chariz
Cephei (ws.hbang.common) v1.15 by HASHBANG Productions  via Chariz
NewTerm (iOS 10 – 13) (ws.hbang.newterm2) v2.4 by HASHBANG Productions  via Chariz
Zebra (xyz.willy.zebra) v1.1.9 by Wilson Styres  via Zebra
XZ Utils (xz) v5.2.4-4 by Unknown via Bingner/Elucubratus
zip (zip) v2.32-1 by Unknown via Bingner/Elucubratus

**Comment by himynameisubik** [comment]
Sorry for the inconvenience and issue you're facing. Please create an issue with the correct template.
