### ISSUE TITLE
Changing settings and respringing puts device in respring loop

### ISSUE THREAD

**Issue by DeVaulted** [himynameisubik/Kalm-support#93]
General information:
===

**Kalm version:**
1.3.4

**Kalm preferences file:**
https://pastebin.com/YW4ebQh9

Device information:
===

**iOS version and language:**
13.5, English (US)

**Device:**
iPhone 11 Pro Max 256GB

**Jailbreak:**
unc0ver 5.0.1

Bug description:
===

**Describe the bug:**
For some reason Kalm hard crashes my phone when I respring. Only booting into jail broken mode without loading tweaks & deleting the plist files & reinstalling the tweak helps. This happens every time after the initial respring required to install & setup the tweak.

**Further findings:**
* Deleting the plist & tweak before a known respring and reinstalling after helps
* Any changes to Kalm that require a respring won't work because the respring will trigger said hard crash
* Deleting the plist without removing the tweak while tweaks are unloaded will reboot the phone when trying to re-jailbreak
* Deleting the plist before a known respring is also enough to not trigger the behaviour

**How to reproduce:**

1.) Install & setup the tweak
2.) Respring for any reason

**Expected behavior:**
A regular respring.

Additional information:
===

**Tweak list:**
https://pastebin.com/Y3SW6xiK

**Comment by himynameisubik** [comment]
Does this happen with only Kalm active? And what are the settings that you change, that put's your device into a respring loop?

**Comment by DeVaulted** [comment]
1) No. I'm trying to figure out which other tweak is responsible, gonna take a minute tho, testing takes time.

2) I don't even need to change anything, just triggering a respring with an existing plist file is enough.

**Comment by himynameisubik** [comment]
1. Sure, no worries. Just disable all of them with iCleaner for example and try with only Kalm enabled.
2. Hmm, that's weird. If you delete the plist file there should not be any hi.my.name.is.ubik.kalm.plist in your preferences folder.

**Comment by DeVaulted** [comment]
> 1. Sure, no worries. Just disable all of them with iCleaner for example and try with only Kalm enabled.

That's what I've been doing :)

> 2. Hmm, that's weird. If you delete the plist file there should not be any hi.my.name.is.ubik.kalm.plist in your preferences folder.

Well, after I delete the plist I can respring without crashing, but on said respring Kalm automatically creates a new plist file. It doesn't matter for what reason I'm respringing. 

So, basically, as long as a plist file exists, a respring for any reason will crash the phone.

**Comment by DeVaulted** [comment]
Further Findings:
* A respring without any other tweaks loaded causes the same behavior, so my earlier assessment of this not being the case was either wrong or I missed something on the first try (settings: https://pastebin.com/Hmn4rScr)

* It appears any change to the settings will cause the behavior

**Comment by himynameisubik** [comment]
Hmm, does Cr4shed or something provide a crashlog? I don't see any way of helping you out here as I have no idea what's happening.

**Comment by DeVaulted** [comment]
I found the setting responsible. 

 ` <key>maxDaysAhead</key>
    <integer>72</integer>`

As soon as this setting is introduced into the plist, the phone crashes on respring. All other changes work.

**Comment by himynameisubik** [comment]
Okay that's really weird. You selected 3 days I assume (72 hours). But what, this makes no sense at all. I have mine set to 3 days as well.

Did you try step 3 here:?
https://github.com/himynameisubik/Kalm-support#general-steps-to-try-before-creating-an-issue

Which items do you have active in Up Next?

**Comment by DeVaulted** [comment]
Ahh, that helped. I didn’t reinstall the Calendar app because I thought it was still installed. Sorry to have bothered you with this. Is there any way for you to make it so Kalm doesn’t have to rely on the standard Calendar app? I’m not using it and I prefer not having useless apps on my phone.

**Comment by himynameisubik** [comment]
Hmm, do you even use Up Next? If yes, Reminders, Alarms? And do you have Calendars disabled in Kalm - Up Next - Settings?

**Comment by DeVaulted** [comment]
I do use Up Next, I simply replaced the Calendar App with Week Calendar - Cloud Calendar on my phone. Funnily enough, without a respring Kalm seems to be able to access the calendars from said app, otherwise I would’ve been clued in earlier on it being a calendar issue.

**Comment by himynameisubik** [comment]
Hmm, that's also very weird to hear. I'll try to find a solution, but I'm not too sure as Kalm does not officially support 3rd party calendar apps. Glad it works now tho! And thanks for all the information you provided!
