### ISSUE TITLE
Up Next Not Showing

### ISSUE THREAD

**Issue by ianduc** [himynameisubik/Kalm-support#94]
General information:
===

**Kalm version:** latest version 1.3.4.

Just installed on iOS 13.5. Everything works fine except UP NEXT not showing.

**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:**
13.5
**Device:**
XR
**Jailbreak:**

Yes

Bug description:
===

**Describe the bug:**

**How to reproduce:**

**Expected behavior:**

**Screenshots:**

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment]
Schedule was not selected in Kalm Settings. Fixed via email support.
