### ISSUE TITLE
Conflicting issue with Kalm and Photon

### ISSUE THREAD

**Issue by SamuraiJackEPCI** [himynameisubik/Kalm-support#96]
General information:
===

**Kalm version:**
1.3.4

**Kalm preferences file:** (sorry, I couldn't figure out the pastebin website)
[cuFfkBP9.txt](https://github.com/himynameisubik/Kalm-support/files/4689870/cuFfkBP9.txt)

Device information:

**iOS version and language:**
iOS 13.5 - English
**Device:**
iPhone 11,6 (10xs Max)
**Jailbreak:**
unc0ver 5.0.0

Bug description:
Photon is a tweak that allows OLED displays to have an always-on display, with this tweak installed and Kalm installed at the same time it does not work as intended. The screen will continue to fade in and out and eventually, it even breaks photons colored notification dots that sit right below the camera (making them move all around the screen. What is supposed to happen is the screen will show the time and the tweak complications with the rest of the screen off. I have done some small troubleshooting and when kalm is installed the screen will fade in and out (not intended) but without it installed Photon works perfectly. "Working perfectly" notification dots stay at the top of the screen, only clock, and complications show. I thought it might have something to do with quart but everything works fine with quart, complications, and photon installed. 

**How to reproduce:**
To have the exact setup would be:
1. Quart
2. Kalm
3. Complications
4. Photon 
Simply lock the screen and it will automatically start pulsing and eventually (maybe a few minutes) the notification dots will start to move around the screen. 

**Expected behavior:**
The screen shows clock, complications, and notification dots at the top of the screen (stay in the same spot), screen slightly dims after a minute or 2, OLED pixel burn-in prevention will active (part of photon) and every so often will slightly move the items around. 

**Screenshots:**
Bug is happening (with kalm)
![IMG_2552](https://user-images.githubusercontent.com/61169349/83041431-77e98380-a00e-11ea-957b-ce144e8f72d4.png)

The way it is supposed to function. (without kalm, cant be seen but the screen is dim on the actual phone)
![IMG_2557](https://user-images.githubusercontent.com/61169349/83041496-8899f980-a00e-11ea-8e29-82e93ffa235f.png)

Additional information:
===

**Tweak list:**
Couldn't figure out how to get the tweak list into Pastebin (this excludes kalm)
![IMG_2558](https://user-images.githubusercontent.com/61169349/83041649-b5e6a780-a00e-11ea-8430-4d7f60b6df1a.png)

**Crashlog:**
no crash log, does not crash

**Comment by himynameisubik** [comment]
I am in contact with the developer of Photon to fix this issue. I can't do much about it at the moment. Sorry for the inconvenience. Will update as soon as I know more.

**Comment by SamuraiJackEPCI** [comment]
That is perfectly fine, I just wanted to make sure it was known and on file. Thanks for all the hard work and can't wait for the update :).

**Comment by himynameisubik** [comment]
This should be fixed with the next update of Photon.

**Comment by SamuraiJackEPCI** [comment]
Incredible! Thank you so much :)

**Comment by himynameisubik** [comment]
Was fixed in the latest Photon update.
